### ISSUE TITLE
SDK v1.0.9 fails to install on Windows 10

### ISSUE THREAD

**Issue by pankajksingh** [dotnet/orleans#807] opened 2015-09-18 17:51 UTC
On my Windows 10 box, installing msi does not copy over Binaries(see output of dir) for version 1.0.9.
I have to go back to get version 1.0.8 where I can find Orleans.dll under Binaries folder. But since samples have moved up a version, I am stuck. Note: There is not error message during msi installation. 

C:\Microsoft Project Orleans SDK v1.0.9\SDK
>dir /B
Docs
OrleansVSTools.vsix
README.TXT
Samples
UninstallOrleansVSTools.cmd

**Comment by sergeybykov** [comment] 2015-09-18 17:58
1.0.9 msi doesn't install binaries anymore. They only come via NuGet. The samples use NuGets, too.

We are deprecating the msi in 1.0.10 altogether.

**Comment by sergeybykov** [comment] 2015-09-18 18:03
And the project templates are already in VS gallery - https://visualstudiogallery.msdn.microsoft.com/36903961-63bd-4eec-9ca4-cf2319dc75f4.

Along with the BigPark's more advanced solution template - https://visualstudiogallery.msdn.microsoft.com/b61c87e7-0655-4a6e-8e4f-84192950e08c.

No need for the msi anymore.

**Comment by sergeybykov** [comment] 2015-09-18 21:11
Closing this as by design.

**Closed by sergeybykov** 2015-09-18 21:11 UTC
Labels: question
