### ISSUE TITLE
Front Ends for orleans services, Error 101027 Runtime.Messaging.GatewayAcceptor

### ISSUE THREAD

**Issue by dalestone** [dotnet/orleans#581] opened 2015-07-05 12:48 UTC
Hi,

I have created a basic Orleans Dev/Test Host, Grain Class Collection and Grain Interface Collection where I have a simple grain that sends a mobile alert, this is all working fine running from the console application. I want to create a frontend using Web API.

I have added the following to my ASP.NET Web API:
1.	Added ClientConfiguration.xml to the root of the project.
2.	Added Orleans.GrainClient.Initialize(Server.MapPath(“ClientConfiguration.xml”)) to Global.asax (I assumed OrleansClient has been changed to GrainClient as I couldn’t find OrleansClient?)

After that I did the following:
1.	StartLocalSilo.cmd from the SDK folder (Successfully started Orleans silo ‘Primary’ as a Primary node.)
2.	Run and build ASP.NET Web API Application
3.	Looking at the silo logs I can see one error:

ERROR  	101017	Runtime.Messaging.GatewayAcceptor/1	127.0.0.1:11111]	!!!!!!!!!! Exception trying to process 39 bytes from endpoint 127.0.0.1:51660 at offset 39 in phase Body CurrentLength=39 HeaderLength=254 BodyLength=39	
Exc level 0: System.Runtime.Serialization.SerializationException

You can see the log here: https://github.com/dalestone/BasicOrleans.Host/blob/master/logs/Primary-2015-07-05-12.36.58.120Z.txt and the code here: https://github.com/dalestone/BasicOrleans.Host

The problem is it never seems to initialize the Web API and I just get a blank white screen with it stuck loading. Any pointers where I might be going wrong would be appreciated!  

Regards,
Dale.

**Comment by gabikliot** [comment] 2015-07-05 13:28
Can you please also share the client log?

**Comment by dalestone** [comment] 2015-07-05 14:11
These two are generated when running the Orleans Dev/Test Host (BasicOrleans.Host)

https://github.com/dalestone/BasicOrleans.Host/blob/master/logs/Client-2015-07-05-14.01.07.723Z.txt
https://github.com/dalestone/BasicOrleans.Host/blob/master/logs/Dale-PC-2015-07-05-14.00.53.240Z.txt

I don't seem to get any logs created when running the Web API project though

**Comment by gabikliot** [comment] 2015-07-06 20:18
Someone had a similar issue here: https://github.com/dotnet/orleans/issues/146 and he was able to resolve it:
"So I've a successful deployment of a cloud service with the silo + web api when I carefully reread the documentation to make sure I had everything set up correctly using the AzureWebSample Project"

**Comment by sergeybykov** [comment] 2015-07-06 23:20
The logs look clean to me - the client successfully connects to the silo gateway. I don't see any error or exception like you mentioned. I'm a bit confused.

**Comment by gabikliot** [comment] 2015-07-06 23:25
I think what @dalestone describes is that he tried 2 setups:

1) Orleans Dev/Test Host (BasicOrleans.Host) - all works, both silo and client connect and all works.

2) Silo runs as Orleans Dev/Test Host while client runs as Web API. He could not find the log for client, and the silo has "Exception trying to process 39 bytes from endpoint 127.0.0.1:51660 " in the silo log.
There must be a client log somewhere, since client must be running (since there is a SerializationException in the silo). I suspect there is some mis-configuratin in this setup, just like it was in #146 this case.

**Comment by dalestone** [comment] 2015-07-07 08:40
So the strange thing is I did manage to get it working for a while yesterday after a fresh install of the SDK and a rebuild with the Web API as the start project.

However  after making some code changes and rebuilding, the error has reappeared when trying to initialize the Web API to connect to the local silo. I also tried running it on another machine in VS2012 but it just seems to be stuck on the same thing Orleans.GrainClient.Initialize. I have run it in Visual Studio 2012 Professional, 2013 community and 2015 community RC.

I will take a look at #146, as you say there must be some incorrect configuration somewhere.

**Comment by gabikliot** [comment] 2015-07-07 16:12
Based on what you just wrote, I think the problem is that after you rebuild, the new binaries are not being deployed to the right location, so when you run again it uses a mixture of old and new binaries on the client and silo (client might be running the old binaries and silo the new, or via versa).
Please make sure that the latest binaries are deployed correctly to the right place.

**Comment by gabikliot** [comment] 2015-07-09 21:07
@dalestone , were you able to validate that it was a dll mismatch issue and fix it?

**Comment by dalestone** [comment] 2015-07-10 21:16
No luck yet unfortunately, I am going to spend some time tomorrow looking at it.

**Comment by dalestone** [comment] 2015-07-11 10:39
So starting from scratch I will describe what I am doing and tell me if you spot something I am missing or doing wrong.

VS2013:

1. Create Orleans Dev/Test Host -> Builds and runs fine.
2. Create Orleans Grain Interface Collection.
3. Create Orleans Grain Class Collection -> Add Reference to Orleans Grain Interface Collection.
4. Add References to Grain Interface Collection and Grain Class Collection in Orleans Dev/Test Host -> Builds and Runs fine.
5. Create a ASP.NET Web API Project -> Add Nuget Orleans Client Libaries -> Add References to Grain Class Collection and Grain Interface Collection.
6. Edit Global.asax in ASP.NET Web API Project and add the following:       
```csharp 
   Orleans.GrainClient.Initialize(Server.MapPath("DevTestClientConfiguration.xml");
```
7. Build and Run Orleans Dev/Test Host -> Builds and runs fine.
8. Debug and Start new instance of ASP.NET Web API Project.
9. Looking at Orleans Dev/Test Host cmd window:
```
 ERROR 101027 Runtime.Messaging.GatewayAcceptor ProcessReceivedBuffer exception with RemoteEndPoint 127.0.0.1:55518  System.Runtime.Serialization.SerilaizationException: Attempt to read past the end of the input stream
```

**Comment by gabikliot** [comment] 2015-07-11 15:44
Do you have the logs for both silo and the client for this run?

**Comment by dalestone** [comment] 2015-07-11 20:58
Silo: https://gist.github.com/dalestone/dace56f9fd14f7a8c3cc
Client: https://gist.github.com/dalestone/a3a665861024c7d88755


I also had a look at event viewer when this was run and there are a few errors from sources such as PerfNet, Perflib with event IDs 1008, 1022, 1023, 2004 if that's any further hints to why it seems to fail.

**Comment by gabikliot** [comment] 2015-07-12 04:24
Silo log has:

[2015-07-11 20:38:47.690 GMT    32	INFO   	101301	Orleans.Messaging.Gateway	127.0.0.1:11111]	Recorded opened socket from endpoint 127.0.0.1:53667, client ID *cli/b1a453b1.	
[2015-07-11 20:38:47.737 GMT    36	INFO   	100000	Runtime.Messaging.GatewaySender.GatewaySiloSender_0/1	127.0.0.1:11111]	Starting AsyncAgent Runtime.Messaging.GatewaySender.GatewaySiloSender_0/1 on managed thread 36	
[2015-07-11 20:39:33.709 GMT    33	INFO   	101301	Orleans.Messaging.Gateway	127.0.0.1:11111]	Recorded opened socket from endpoint 127.0.0.1:53674, client ID *cli/791820a5.

Which means that the client connects twice to the silo. This should not be happening in the regular setup.
It makes me wonder how do you handle Client.Initialize in your ASP.NET code? Is it possible that you are initializing it in every call? ASP.NET is weird in the way they handle app domains - sometime reuse them and sometimes not. Please try also to look for more client logs. If you are indeed starting multiple clients each should have it's log.
Of course, in general, connecting with multiple unrelated clients should work, but there might be some additional weirdness here.

**Comment by dalestone** [comment] 2015-07-12 12:24
Yes sorry I left a GrainClient.Initialize in the Dev/Test Host console application. The same error still occurs though when initializing from the Web API.


```
[2015-07-12 12:14:21.197 GMT     9	INFO   	100402	OrleansSiloHost	127.0.0.1:11111]	Silo DaleSurfacePro3 started successfully	
[2015-07-12 12:15:03.217 GMT    30	INFO   	101301	Orleans.Messaging.Gateway	127.0.0.1:11111]	Recorded opened socket from endpoint 127.0.0.1:56824, client ID *cli/9b033bb8.	
[2015-07-12 12:15:03.292 GMT    30	ERROR  	101017	Runtime.Messaging.GatewayAcceptor/1	127.0.0.1:11111]	!!!!!!!!!! Exception trying to process 39 bytes from endpoint 127.0.0.1:56824 at offset 39 in phase Body CurrentLength=39 HeaderLength=238 BodyLength=39	
Exc level 0: System.Runtime.Serialization.SerializationException: Attempt to read past the end of the input stream: CurrentPosition=9, n=133891, totalLength=238
   at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Boolean& safeToUse)
   at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n)
   at Orleans.Serialization.BinaryTokenStreamReader.ReadString()
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaderDictHelper(BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaders(BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message..ctor(List`1 header, List`1 body)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceivedBuffer(Int32 bytes)
[2015-07-12 12:15:03.314 GMT    30	ERROR  	101027	Runtime.Messaging.GatewayAcceptor/1	127.0.0.1:11111]	!!!!!!!!!! ProcessReceivedBuffer exception with RemoteEndPoint 127.0.0.1:56824: 	
Exc level 0: System.Runtime.Serialization.SerializationException: Attempt to read past the end of the input stream: CurrentPosition=9, n=133891, totalLength=238
   at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Boolean& safeToUse)
   at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n)
   at Orleans.Serialization.BinaryTokenStreamReader.ReadString()
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaderDictHelper(BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaders(BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message..ctor(List`1 header, List`1 body)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceivedBuffer(Int32 bytes)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallback(IAsyncResult result)
[2015-07-12 12:15:03.322 GMT    30	INFO   	101302	Orleans.Messaging.Gateway	127.0.0.1:11111]	Recorded closed socket from endpoint 127.0.0.1:56824, client ID *cli/9b033bb8.	
[2015-07-12 12:15:03.346 GMT    30	INFO   	101301	Orleans.Messaging.Gateway	127.0.0.1:11111]	Recorded opened socket from endpoint 127.0.0.1:56825, client ID *cli/9b033bb8.	
[2015-07-12 12:15:03.353 GMT    34	INFO   	100000	Runtime.Messaging.GatewaySender.GatewaySiloSender_0/1	127.0.0.1:11111]	Starting AsyncAgent Runtime.Messaging.GatewaySender.GatewaySiloSender_0/1 on managed thread 34	
[2015-07-12 12:15:16.292 GMT    14	INFO   	100507	Catalog	127.0.0.1:11111]	Before collection#2: memory=24MB, #activations=2, collector=<#Activations=1, #Buckets=1, buckets=[1h:59m:43s.721ms->1 items]>.	
[2015-07-12 12:15:16.307 GMT    14	INFO   	100508	Catalog	127.0.0.1:11111]	After collection#2: memory=24MB, #activations=2, collected 0 activations, collector=<#Activations=1, #Buckets=1, buckets=[1h:59m:43s.700ms->1 items]>, collection time=00:00:00.0210285.
```

I only initialize it once in the Global.asax

```csharp
    public class WebApiApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {            
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            Orleans.GrainClient.Initialize(Server.MapPath("DevTestClientConfiguration.xml"));
        }
    }
```

**Comment by gabikliot** [comment] 2015-07-13 04:48
Lets first remove the redundant GrainClient.Initialize from the Dev/Test Host console application.

The real issue I suspect is related to how you call `Orleans.GrainClient.Initialize`.
You should be doing it inside Page_Load:

           if (!GrainClient.IsInitialized)
                {
                    AzureGrainClientClient.Initialize(clientConfigFile);
                }

Please take a loot at AzureWebSample:
https://github.com/dotnet/orleans/blob/master/Samples/AzureWebSample/WebRole/Default.aspx.cs

**Comment by dalestone** [comment] 2015-07-15 18:56
@gabikliot  So I ended up taking another approach, I am not sure how well this would deploy though.

Create a WebAPI Wrapper (I took inspiration from one of the Orleans templates, I would link to it but I don't seem to be able to find it!)
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Net;
using System.Diagnostics;

using Microsoft.Owin.Hosting;
using Owin;
using System.Web.Http;
using Microsoft.Owin.Cors;
using System.Reflection;
using System.Web.Http.Dispatcher;
using Host;

namespace OrleansDemo.Host
{
    internal class WebApiWrapper : IDisposable
    {
        internal class Startup
        {
            // Configure Web API. The Startup class is specified as a type parameter in the WebApp.Start method
            public void Configuration(IAppBuilder appBuilder)
            {
                // Configure Web API for self-host
                HttpConfiguration config = new HttpConfiguration();
                config.MapHttpAttributeRoutes(); // enables route attributes
                config.Services.Replace(typeof(IAssembliesResolver), new SelfHostAssemblyResolver());
                config.Routes.MapHttpRoute(
                    name: "DefaultApi",
                    routeTemplate: "api/{controller}/{id}",
                    defaults: new { id = RouteParameter.Optional });

                config.IncludeErrorDetailPolicy = IncludeErrorDetailPolicy.Always;

                appBuilder.UseCors(CorsOptions.AllowAll);
                appBuilder.UseWebApi(config);
                
            }
        }

        private IDisposable _webApp = null;

        public string Url { get; set; }

        public bool Run()
        {
            bool ok = false;

            try
            {
                var startOptions = new StartOptions();
                startOptions.Urls.Add(string.Format("{0}://{1}:{2}", "http", Dns.GetHostName(), "81"));
                Url = startOptions.Urls[0];
                Trace.TraceInformation(String.Format("Starting OWIN at {0}", startOptions.Urls[0]), "Information");
                _webApp = WebApp.Start<Startup>(startOptions);
                ok = true;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            return ok;
        }


        public void Dispose()
        {
            Dispose(true);
        }

        protected virtual void Dispose(bool dispose)
        {
            _webApp.Dispose();
            _webApp = null;
        }
    }
}

```
Initialize the WebAPI in Dev/Host console application main method.
```csharp
using System;
using OrleansDemo.GrainInterfaces;
using Orleans.Runtime;

namespace OrleansDemo.Host
{
    /// <summary>
    /// Orleans test silo host
    /// </summary>
    public class Program
    {
        static void Main(string[] args)
        {
            // The Orleans silo environment is initialized in its own app domain in order to more
            // closely emulate the distributed situation, when the client and the server cannot
            // pass data via shared memory.
            AppDomain hostDomain = AppDomain.CreateDomain("OrleansHost", null, new AppDomainSetup
            {
                AppDomainInitializer = InitSilo,
                AppDomainInitializerArguments = args,
            });

            Orleans.GrainClient.Initialize("DevTestClientConfiguration.xml");

            // intializing HTTP front end for accepting incoming requests.
            webApiWrapper = new WebApiWrapper();
            if (!webApiWrapper.Run())
            {
                Console.Error.WriteLine("Failed to initialize web api.");
            }
            else
            {
                Console.WriteLine(string.Format("Started web host at: {0}", webApiWrapper.Url));
            }
            

            Console.WriteLine("Orleans Silo is running.\nPress Enter to terminate...");
            Console.ReadLine();

            hostDomain.DoCallBack(ShutdownSilo);
        }

        static void InitSilo(string[] args)
        {
            hostWrapper = new OrleansHostWrapper(args);

            if (!hostWrapper.Run())
            {
                Console.Error.WriteLine("Failed to initialize Orleans silo");
            }
        }

        static void ShutdownSilo()
        {
            if (hostWrapper != null)
            {
                hostWrapper.Dispose();
                GC.SuppressFinalize(hostWrapper);
            }
        }

        private static OrleansHostWrapper hostWrapper;
        private static WebApiWrapper webApiWrapper;
    }
}

```
Create a values api controller:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;
using OrleansDemo.GrainInterfaces;

namespace OrleansDemo.Host
{
    public class ValuesController : ApiController
    {
        // GET api/values 
        public IEnumerable<string> Get()
        {
            var grain = MobileAlertGrainFactory.GetGrain(0);
            var message = new { To = "+4400000000000", Body = "A SMS message sent with orleans on " + DateTime.Now };
            var task = grain.SendSMSAlert(message.To, message.Body);

            task.Wait();

            return new string[] { task.Result };
        }
}
```
When I run and build the Dev/Test Orleans Host I now have an endpoint `dalesurfacepro3:81/api/values` which I can make http requests to.

I would next like to work how to deploy this to Azure, I will take a read of [this](http://dotnet.github.io/orleans/Step-by-step-Tutorials/Cloud-Deployment)

**Comment by gabikliot** [comment] 2015-07-24 22:19
@dalestone, were you able to resolve this? Can we close this issue or do you need more help with it?

**Closed** 2015-07-28 22:35 UTC
Labels: question, under-investigation
