### ISSUE TITLE
Potential grain directory corruption

### ISSUE THREAD

**Issue by cvalusek** [dotnet/orleans#2399] opened 2016-11-08 16:21 UTC
I had a chain reaction Friday that caused us some pain in a non-production environment. We had 3 silos running with SqlMembershipProvider on v1.2.3. One of the silos crashed early Friday morning. I think the crash may be related to issues in a custom storage provider. That part, I can work on, but when it failed... It managed to corrupt the grain directory on the other 2 servers. They correctly marked the silo as dead, but left it in the grain directory. Request for the corrupted grain addresses would in turn get queued up to the dispatcher with the dead silo and then get "Transient Rejection" because the dispatcher already knows "silo is known to be dead". This caused the request to spin on the caller side as it never responded back until it timed out. The latter part here exacerbated the issue. So... I have 2 things to better understand here. This first is how to prevent the grain directory corruption. The second is how to get request like this that will fail to do so quickly.

Here is an example from one of the silos that did not crash (names, ips and ports changed):
```[2016-11-05 15:17:47.182 GMT    13	WARNING	100534	Catalog	10.0.0.1:3000]	Failed to InvokeActivate for [Activation: S10.0.0.1:3000:215851596*grn/5DDFAB7B/00000000+mykeyext@d7707e82 #GrainType=MyGrain.MyGrain Placement=RandomPlacement State=Invalid].	
Exc level 0: Orleans.Runtime.OrleansException: Silo S10.0.0.1:3000:215851596 is rejecting message: Request S10.0.0.1:3000:215851596*grn/5DDFAB7B/00000000+mykeyext@d7707e82->S10.0.0.2:3000:215857134*grn/E421F2FC/aa917ab6+mykeyext@45d6889e #36397240[ForwardCount=1]: global::MyGrain.MyOtherGrain:Initialize(). Reason = Target S10.0.0.2:3000:215857134 silo is known to be dead
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyGrain.MyGrain.<OnActivateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<CallGrainActivate>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__51.MoveNext()```

**Comment by cvalusek** [comment] 2016-11-08 16:38
Looks like this message was getting logged for request bouncing from 1st to 3rd silo.
```[2016-11-05 15:17:47.182 GMT    12	WARNING	100148	Dispatcher	10.0.0.1:3000]	No target activation S10.0.0.3:3000:212720806*grn/5DDFAB7B/00000000+mykeyext@5ca03c9a for response message: Transient Rejection (info: Silo S10.0.0.1:3000:215851596 is rejecting message: Request S10.0.0.3:3000:212720806*grn/5DDFAB7B/00000000+mykeyext@5ca03c9a->S10.0.0.2:3000:215857134*grn/DCAC523A/00000000+mykeyext@6d81069c #843011033[ForwardCount=1]: global::MyGrain.MyYetAnotherGrain:IsEnabled(). Reason = Target S10.0.0.2:3000:215857134 silo is known to be dead) Response S10.0.0.2:3000:215857134*grn/DCAC523A/00000000+mykeyext@6d81069c->S10.0.0.3:3000:212720806*grn/5DDFAB7B/00000000+mykeyext@5ca03c9a #843011033: global::MyGrain.MyYetAnotherGrain:IsEnabled()```

**Comment by cvalusek** [comment] 2016-11-08 17:54
To my surprise, these log messages go back as far as Thursday morning.

There is something interesting just prior to that:
```[2016-11-04 06:13:44.136 GMT    12	WARNING	100064	Catalog	10.0.0.1:30001]	Failed to RegisterActivationInGrainDirectory for [Activation: S10.0.0.1:30001:215851596*grn/E4FCB112/ab374ab8+tronc@6618e8ae #GrainType=MyGrain.MyGrain Placement=RandomPlacement State=Invalid].	
Exc level 0: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S10.0.0.1:30001:215851596Catalog@S0000000e->S10.0.0.2:30001:215935943DirectoryService@S0000000a #26610358: global::Orleans.Runtime.IRemoteGrainDirectory:RegisterAsync(). Target History is: <S10.0.0.2:30001:215935943:DirectoryService:@S0000000a>.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.<RegisterAsync>d__90.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass0_0`1.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<RegisterActivationInGrainDirectoryAndValidate>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__51.MoveNext()```

**Comment by cvalusek** [comment] 2016-11-08 19:30
Looks like the nightly jobs are spiking the CPU on all the silos and causing the timeouts on the grain directory calls. It might be difficult, but I am going to see if I can produce a unit test that reproduces the issue.

**Comment by sergeybykov** [comment] 2016-11-09 18:44
What CPU utilization are you seeing? Directory runs at the system priority. So it shouldn't be timing out unless 1) CPU is consistently overloaded or 2) what we see more often - memory allocations in the app code run amok with GC freezing the process for longer and longer periods of time.

The first thing I would check is .NET memory perf counters, % time in GC in particular. If there's an object leak, the quickest thing to do is to take a memory dump and look at the object counts by type in debugger.

**Comment by cvalusek** [comment] 2016-11-09 19:05
The CPU utilization is coming from some background jobs that we have running on the thread pool. We are going to offload those to an infrastructure that is better at those processes in the long-term. I suspect spawning dedicated threads (TaskCreationOptions.LongRunning) for these specific processes may help clear up some of the blocking as well. No watchdog errors logged in these time periods.

Also, the directory did not recover later when the CPU load returned to normal. What is strange is that the silo kept running for a good day before it actually crashed when the CPU spiked again. In this time period the other silos had internally marked it dead, based on the above errors.

**Comment by sergeybykov** [comment] 2016-11-09 19:34
So you filled the thread pool in the silo process with some long running tasks that consumed a lot of CPU cycles?

The non-recovery part doesn't make sense to me still. If you could privately share full logs, that should help clear what was going on there.

**Comment by gabikliot** [comment] 2016-11-10 05:55
Is it possible that the problem is not in the grain directory but in the membership?
@cvalusek , can you check in the logs that the silo was correctly detected as dead by ALL other silos? It should appear in the logs.

**Comment by cvalusek** [comment] 2016-11-10 16:24
Looks like I won't be able to provide the full logs. I'll see if i can find where the other silos decided it was dead. Some more pressing issues have come up, so I may not get to this until EOD tommorrow.

Thanks for the rapid response.

**Comment by sergeybykov** [comment] 2016-11-10 18:01
Good point by @gabikliot - take a look at the `OrleansSiloInstances` table (the cluster membership table) to see the full history of what silo got suspected and voted dead by what other silos at what time, etc. Maybe you can at least share the table?

**Comment by gabikliot** [comment] 2016-11-10 19:52
I think he is using SQL, which made me suspicious.

**Comment by cvalusek** [comment] 2016-11-10 22:59
For the failing silo, looks like it's about a minute before the error occurred:
```10.0.0.1:3000@215851596,2016-11-04 06:12:21.134 GMT
10.0.0.3:3000@212720806,2016-11-04 06:12:23.713 GMT```

I'll see if I can find anything significant around that time. I am using the SqlMembershipProvider and also thought it might be some kind of issue there. I mentioned the grain directory because I didn't realize how distinct they are (membership and grain directory).

**Comment by cvalusek** [comment] 2016-11-10 23:03
```    <Liveness LivenessType="SqlServer" ProbeTimeout="10s" TableRefreshTimeout="60s" DeathVoteExpirationTimeout="120s" NumMissedProbesLimit="3" NumProbedSilos="3" NumVotesForDeathDeclaration="2" />```

**Comment by veikkoeeva** [comment] 2016-11-11 13:59
I'll subscribe myself to this thread too. Reading
> They correctly marked the silo as dead, but left it in the grain directory. Request for the corrupted grain addresses would in turn get queued up to the dispatcher with the dead silo and then get "Transient Rejection" because the dispatcher already knows "silo is known to be dead".

could mean that the table query and/or update logic does not work correctly on the storage level, but if the entries look correct, the problem looks like being elsewhere. The operations  are fairly well covered by the current tests, though my gut feeling is that especially tests through [MembershipOracle](https://github.com/dotnet/orleans/blob/8d6153f46763a3ec97db483142ce17b9d90dc9c9/src/OrleansRuntime/MembershipService/MembershipOracle.cs) would be useful. I remember we had some problem uncovered whenthe extraneous columns got removed from the ADO.NET provider.

**Comment by moorle1** [comment] 2016-11-15 17:42
More logging from the same incident that @cvalusek is talking about. This is what the other two silos logged at the same time frame.

[Silo_01-2016-11-03.txt](https://github.com/dotnet/orleans/files/592718/Silo_01-2016-11-03.txt)
[Silo_02-2016-11-03.txt](https://github.com/dotnet/orleans/files/592719/Silo_02-2016-11-03.txt)

**Comment by cvalusek** [comment] 2016-11-15 17:45
Silo_02-2016-11-03.txt was the failing one, we are still scrubbing the third one.

**Comment by cvalusek** [comment] 2016-11-15 17:47
Wanted to just comment that this recurred today and we found that the membership tables have state 3 (alive), but the messages are getting logged from the other servers that "silo is known to be dead".

**Comment by cvalusek** [comment] 2016-11-15 17:53
Getting a clean shutdown of the failing silo (which was still running) did not resolve the issue.

```Exc level 0: Orleans.Runtime.OrleansException: The target silo is no longer active: target was S10.0.0.2:3000:216631070, but this silo is S10.0.0.2:3000:216928068. The rejected message is Request S10.0.0.2:3000:216374572*grn/B5B47671/00000000+mykeyext@40dc7f95->S10.0.0.2:3000:216631070*grn/B715D5C0/965ff5a8+mykeyext@08832cb4 #83053898[ForwardCount=1]: global::MyOtherGrain:Synchronize().
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyGrain.<SyncPeriod>d__16.MoveNext()```

**Comment by cvalusek** [comment] 2016-11-15 17:57
More info on the recovery... restarting the non-failing silos fixed the problem.

**Comment by veikkoeeva** [comment] 2016-11-15 20:56
@cvalusek Does
> Exc level 0: System.Data.SqlClient.SqlException: Invalid column name 'Sequence'.

come from your custom provider? It is strange it has failed to an invalid column name if it has existed. Could there have been an incident in the storage that influenced both the custom storage table and membership tables? It seems the trouble has started earlier than the storage related exception happened.

To my untrained eye it looks almost as if silo 1 tries to call a grain, it is tried to be instantianted in silo 2 and it fails to assembly loading exception (same dlls?) and consequently the deployment and activation fail. Soon after fails also the loading of custom state due to the invalid column exception. Then to silo 1 this looks as if the grain call takes a long time, the call is stalled and so on. But then gain there seem to be in silo 1 the socket connection is refused (port exhaustion, firewall?) and since calls won't be make inter-silo progress, they're declared dead.

With this reading doesn't make sense, hmm. I let the more knowledgeable know something and hit the hay. :)

**Comment by cvalusek** [comment] 2016-11-15 21:26
That error is from some operational issues that lead to a table being out of sync with what our custom provider was expecting. It does cause those grains to fail to activate. That one we need to resolve, but left it in as it might help with the investigation.

**Comment by sergeybykov** [comment] 2016-11-15 21:57
@cvalusek Can you also share a dump of the membership table? This looks fishy, and might be SQL provider specific. If would also help if you could share, even if privately, fuller logs. Otherwise, some guessing and assumptions are required, which may be misleading.

Here's what I see in the log snippets you posted.
At 6:12:01 Silo1 (10.0.0.1:3000) logged that it is unable to connect to Silo2 (10.0.0.2:3000)
>[2016-11-04 06:12:01.102 GMT    15	WARNING	101021	Runtime.Messaging.SiloMessageSender/PingSender	10.0.0.1:3000]	Exception getting a sending socket to endpoint S10.0.0.2:3000:215857134

I see messages about failed pings from Silo1 to Silo2, failed calls to Silo2's directory, failed grain calls, etc., everything that is expected to be happening until Silo2 is declared dead. Then there are a couple of GC related messages that may or may not be part of the problem, as it's "only" a 7 second stall.
>[2016-11-04 06:12:33.337 GMT   247	WARNING	100150	Watchdog	10.0.0.1:3000]	.NET Runtime Platform stalled for 00:00:07.2970414 - possibly GC? We are now using total of 1575MB memory. gc=26727, 11710, 454	

There are reports of multiple 101032 (forwarding failed) and 100071 warnings, but no previous warnings in the snippet. Finally, there is an unawaited Task warning and unobserved exception error that may point to a problem in the grain code, but likely unrelated.

Now, looking at Silo2, I can only assume that it got restarted, as it is reporting some of the startup activities at 6:12:24 and later. The following line tells me there was also Silo3 (10.0.0.3:3000), and Silo2 is failing to communicate with it for some reason. How many silos did you have in the cluster? Did Silo3 fail, too? Can you share its log?
>[2016-11-04 06:13:28.502 GMT   241	WARNING	100157	CallbackData	10.0.0.2:3000]	Response did not arrive on time in 00:00:30 for message: Request S10.0.0.2:3000:215935943MembershipOracle@S0000000f->S10.0.0.3:3000:212720806MembershipOracle@S0000000f #71: global::Orleans.Runtime.IMembershipService:SiloStatusChangeNotification(). Target History is: <S10.0.0.3:3000:212720806:MembershipOracle:@S0000000f>. About to break its promise.	

This is important, because Silo2 is trying to send a membership gossip message here. Notice also that it's about a minute after the beginning of the log snippet. Why is it taking the silo so long to initialize? Did you take out any log lines in between?

Then at 6:13:53 Silo2 is failing to register an activation with the grain directory on SIlo1:
>[2016-11-04 06:13:53.736 GMT    20	WARNING	100064	Catalog	10.0.0.2:3000]	Failed to RegisterActivationInGrainDirectory for [Activation: S10.0.0.2:3000:215935943*grn/7AF4CFDD/99a617ac+mykeyext@62ddafaa #GrainType=MyProject.MyGrain Placement=RandomPlacement State=Invalid].	
Exc level 0: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S10.0.0.2:3000:215935943Catalog@S0000000e->S10.0.0.1:3000:215851596DirectoryService@S0000000a #82: global::Orleans.Runtime.IRemoteGrainDirectory:RegisterAsync(). Target History is: <S10.0.0.1:3000:215851596:DirectoryService:@S0000000a>.

Was Silo1 alive at the time?
Then there are SQL errors that prevent grains from being activated, as expected.
Then the following message points explicitly to the fact that Silo2 is rejecting a message sent to its previous incarnation (epoch number 215857134) before it restarted as 215935943.
>[2016-11-04 06:14:24.204 GMT    22	ERROR  	100513	Catalog	10.0.0.2:3000]	!!!!!!!!!! Error calling grain's OnActivateAsync() method - Grain type = MyProject.MyGrain Activation = [Activation: S10.0.0.2:3000:215935943*grn/E4FCB112/ab374ab8+mykeyext@f8eeaf98 #GrainType=MyProject.MyGrain Placement=RandomPlacement State=Activating]	
Exc level 0: Orleans.Runtime.OrleansException: The target silo is no longer active: target was S10.0.0.2:3000:215857134, but this silo is S10.0.0.2:3000:215935943. The rejected message is Request S10.0.0.2:3000:215935943*grn/E4FCB112/ab374ab8+mykeyext@f8eeaf98->S10.0.0.2:3000:215857134*grn/643D27AE/ab374ab8+mykeyext@fa73a587 #138[ForwardCount=1]: global::MyProject.MyGrain:MyFunction().

Reading between the lines, literally because a lot of information is missing in the log snippets, I can only guess that there were multiple silos failures or restarts that either didn't properly propagate through the membership table or got resolved later. It's impossible for me to tell more precisely because I cannot see any log messages about suspecting that a silo is dead, writing votes to the table, declaring a silo dead after enough votes, etc. The content of the membership table and the omitted logs should shed some light on what actually happened.

For example, if the membership table is not of the right schema or there's some other issue with it, I can imagine silo being unable to write their votes into it. But it's a pure speculation. I can only say that we've never seen the membership protocol not working with the Azure Table provider. It is robust and battle tested. So I'm guessing there might be something is wrong with SQL - either with the database or maybe a bug in the SQL provider code, but the latter is probably less likely, as that functionality has been tested and is used in production by folks like Gigya and others.

**Comment by sergeybykov** [comment] 2016-11-21 16:22
@cvalusek, are we in agreement that there was no directory corruption here, and the issue was triggered by continuous multi-second GC pauses? I'm trying to decide what to do with this issue.

**Comment by cvalusek** [comment] 2016-11-21 19:45
Going to update the issue with what I mentioned in chat.

Sorry. I haven't had time to write that unit test. I'm not in agreement that there isn't something like directory corruption going on. I just am not familiar enough with some of the internals (yet  ) to articulate what I think is happening. There is definitely some defect that causes the silo internally get out of sync with the membership provider under these conditions. It is probably one of the harder defects to really ferret out. I was kind of hoping a light bulb would go off for a team member once we got enough recon on what you have to do to cause it. I know it is expected that it would recover, but from this scenario it doesn't until I restart the non-failing silos. I think my specific issue will go away when we switch to 64-bit because the memory pressure is being caused by that.

I'll try to see if I can reproduce this in a unit test this week.  

Here is my plan for the test:
* Start up 3 silos. I'll try without SqlMembership first and then try that later if I can't reproduce without it. I will use an aggressively low timeout setting on messaging (2-4s or so) and Liveness settings.
* Make a grain that forwards to itself on a different id repeated by the number on an argument provided to it.
* Start up a background thread calling the grain.
* Create a bunch of small objects that amount to a decent amount of memory to give the GC something to think about.
* Call GC.Collect() in a nested loop with a sleep on the outer portion to simulate repeated runtime stalls that I should see logged by the Watchdog.

**Comment by cvalusek** [comment] 2016-11-30 17:40
I tried really hard to reproduce this with a unit test and could not get the scenario to occur in a unit test.  It was impressive what kind of terrible things I through at the silos and they actually handled it nicely. I have let the issue remain in our environment. It does happen every couple of times I put the silos into these conditions. I think most Orleans implementations will not hit this issue. I think it requires a runtime stall (via GC) longer than your timeouts. I will keep trying to find a way to reproduce it consistently.

Here is the class I am using to disrupt the runtime:
```    /// <summary>
    /// This little guy will stall the runtime.
    /// </summary>
    public class RuntimeGremlin
    {
        private readonly object _lock;
        private readonly long _stallFor;
        private readonly int _sleepFor;
        private readonly int _memoryBlockSize;

        private CancellationTokenSource _cancelation;
        private Task _task;
        private List<SomeData<int>> _memoryBlock;

        public RuntimeGremlin(long stallFor, int sleepFor, int memoryBlockSize = 30000000)
        {
            this._lock = new object();
            this._stallFor = stallFor;
            this._sleepFor = sleepFor;
            this._memoryBlockSize = memoryBlockSize;
        }

        public void HaveFun()
        {
            lock (this._lock)
            {
                if (this._task != null)
                {
                    return;
                }

                this.AllocateMemoryBlock();

                this._cancelation = new CancellationTokenSource();
                this._task = Task.Factory
                                 .StartNew(
                                     Run,
                                     this._cancelation.Token,
                                     TaskCreationOptions.LongRunning,
                                     TaskScheduler.Default);
            }
        }

        public void AllocateMemoryBlock()
        {
            if (this._memoryBlock != null)
            {
                return;
            }

            this._memoryBlock = Enumerable.Range(0, this._memoryBlockSize)
                                          .Select(_ => new SomeData<int>())
                                          .ToList();
        }

        private void Run()
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();
            while (!this._cancelation.IsCancellationRequested)
            {
                GrainClient.Logger.Info($"starting stall @ {DateTime.Now}");

                stopwatch.Restart();
                while (stopwatch.ElapsedMilliseconds < this._stallFor)
                {
                    GC.Collect();
                }

                if (this._sleepFor > 0)
                {
                    Thread.Sleep(this._sleepFor);
                }
            }
            stopwatch.Stop();
        }

        public void TimesUp()
        {
            lock (this._lock)
            {
                this._cancelation.Cancel();
                this._memoryBlock = null;
            }
        }

        public class SomeData<TElementType>
        {
            public TElementType Item1 { get; set; }
            public TElementType Item2 { get; set; }
            public TElementType Item3 { get; set; }
            public TElementType Item4 { get; set; }
            public TElementType Item5 { get; set; }
            public TElementType Item6 { get; set; }
            public TElementType Item7 { get; set; }
            public TElementType Item8 { get; set; }
            public TElementType Item9 { get; set; }
            public TElementType Item10 { get; set; }
            public TElementType Item11 { get; set; }
            public TElementType Item12 { get; set; }
            public TElementType Item13 { get; set; }
            public TElementType Item14 { get; set; }
            public TElementType Item15 { get; set; }
            public TElementType Item16 { get; set; }
        }
    }```

**Comment by cvalusek** [comment] 2016-11-30 17:45
Here are the bad Liveness and Messaging timeout settings I am using to try to help with causing the failure in testing:
```    <Messaging ResponseTimeout="1s"/>
    <Liveness LivenessType ="MembershipTableGrain"
              ProbeTimeout="2s"
              TableRefreshTimeout="5s"
              DeathVoteExpirationTimeout="10s"
              NumMissedProbesLimit="2"
              NumVotesForDeathDeclaration="2" />```

**Comment by cvalusek** [comment] 2016-11-30 17:48
And lastly, here is an nunit test (sorry about that) that doesn't see the scenario yet (impressed this doesn't fall apart completely):
```    public interface IForwardingGrain : IGrainWithGuidKey
    {
        Task DoForward(int forwardCount, int sleep);
        Task Start(int forwardCount, int sleep, int inner, int outer);
        Task<bool> IsCompleted();
    }

    public class ForwardingGrain : Grain, IForwardingGrain
    {
        private Task _task;

        public Task DoForward(int forwardCount, int sleep)
        {
            return forwardCount > 0
                ? this.TryForward(forwardCount - 1, sleep)
                : Task.Delay(sleep);
        }

        public Task Start(int forwardCount, int sleep, int inner, int outer)
        {
            var dispatcher = new Dispatcher(TaskScheduler.Current);
            this._task = Task.Factory.StartNew(
                () =>
                {
                    foreach (var o in Enumerable.Range(0, outer))
                    {
                        Task.WhenAll(Enumerable.Range(0, inner)
                                               .Select(i => dispatcher.Dispatch(() => this.TryForward(forwardCount, sleep))))
                            .Wait();
                        Thread.Sleep(sleep);
                        this.GetLogger("ForwardingGrain")
                            .Info($"Finished outer iteration {o} on {this.GetPrimaryKey()} @ {this.RuntimeIdentity}");
                    }
                },
                CancellationToken.None,
                TaskCreationOptions.LongRunning, 
                TaskScheduler.Default);
            return TaskDone.Done;
        }

        public async Task TryForward(int forwardCount, int sleep)
        {
            try
            {
                await this.GrainFactory
                          .GetGrain<IForwardingGrain>(Guid.NewGuid())
                          .DoForward(forwardCount - 1, sleep);
            }
            catch (Exception e)
            {
                this.GetLogger("ForwardingGrain")
                    .Error(200001, "Failure", e);
            }
        }

        public Task<bool> IsCompleted()
        {
            return Task.FromResult(this._task.IsCompleted);
        }
    }

    /// <summary>
    /// This class helps run tasks on another task scheduler.
    /// </summary>
    internal class Dispatcher
    {
        private readonly TaskScheduler _scheduler;

        public Dispatcher(TaskScheduler scheduler = null)
        {
            this._scheduler = scheduler ?? TaskScheduler.Current;
        }

        /// <summary>
        /// This helper function routes the action over to run on the task scheduler provided to the constructor.
        /// </summary>
        public Task Dispatch(Func<Task> action)
        {
            return this.Dispatch(action, CancellationToken.None);
        }

        /// <summary>
        /// This helper function routes the action over to run on the task scheduler provided to the constructor.
        /// </summary>
        public Task Dispatch(Func<Task> action, CancellationToken token)
        {
            return Task.Factory
                       .StartNew(
                           action,
                           token,
                           TaskCreationOptions.None,
                           this._scheduler)
                       .Unwrap();
        }

        /// <summary>
        /// This helper function routes the action over to run on the task scheduler provided to the constructor.
        /// </summary>
        public Task<T> Dispatch<T>(Func<Task<T>> action)
        {
            return this.Dispatch(action, CancellationToken.None);
        }

        /// <summary>
        /// This helper function routes the action over to run on the task scheduler provided to the constructor.
        /// </summary>
        public Task<T> Dispatch<T>(Func<Task<T>> action, CancellationToken token)
        {
            return Task.Factory
                       .StartNew(
                           action,
                           token,
                           TaskCreationOptions.None,
                           this._scheduler)
                       .Unwrap();
        }
    }

    public class ForwardingDefectTests
    {
        [Test]
        public async Task TryBackgroundJob()
        {
            var scale = 3;

            var host = new TestingSiloHost();
            host.StartAdditionalSilos(1);

            var grain = GrainClient.GrainFactory
                                   .GetGrain<IForwardingGrain>(Guid.Empty);
            await grain.Start(5, 100, 20, 100*scale);

            Thread.Sleep(5000);

            var gremlin = new RuntimeGremlin(10000, 1000);
            gremlin.HaveFun();

            GC.Collect();
            GC.Collect();
            GrainClient.Logger.Info($"Currently using {GC.GetTotalMemory(false) / (1024 * 1024)}MB of memory");

            Thread.Sleep(5000);

            host.StopAdditionalSilos();

            Thread.Sleep(10000 + 5000*scale);

            gremlin.TimesUp();

            var completed = false;
            while (!completed)
            {
                await Task.Delay(1000);
                try
                {
                    completed = await grain.IsCompleted();
                }
                catch (Exception)
                {
                    // just wait for the silo to stabilize
                }
            }

            host.StopAllSilos();
        }
    }```

**Comment by sergeybykov** [comment] 2016-11-30 18:57
>DeathVoteExpirationTimeout="10s"

This one seems like the most dangerous setting of all. You'd have to have to death votes happen with 10 seconds, which isn't easy with multi-second GC pauses.

**Comment by sergeybykov** [comment] 2017-01-07 00:45
I'm closing this because we don't have a repro of the issue in a sensible setting. So I don't see anything actionable here. Feel free to reopen if there is a repro case.

**Closed by sergeybykov** 2017-01-07 00:45 UTC
Labels: bug, under-investigation
