### ISSUE TITLE
Different de/serializers used for grain state vs streams

### ISSUE THREAD

**Issue by jeoffman** [dotnet/orleans#3405] opened 2017-09-15 20:15 UTC
Similar to issue #1881 except this time we had a class that was passed via streams as well as saved into a Grain's state. The failure was intermittent and infrequent.

We are using Orleans version 1.4.0

**Comment by sergeybykov** [comment] 2017-09-15 23:23
Can you try it with 1.5.1?

**Comment by jeoffman** [comment] 2017-09-16 17:44
I just upgraded this repo:
https://github.com/jeoffman/OrleansSerializationExceptionTesting_1881_3405
to Orleans v - 1.5.1

The test has the same behavior - use the #define "CAUSE_THE_TEST_TO_FAIL_WITH_SERIALIZATION_EXCEPTION_SOMETIMES"
to cause/remove a SerializationException

Should we continue the conversation back on #1881 or do you suppose these are even related?

**Comment by sergeybykov** [comment] 2017-09-18 21:24
Looks like this is a duplicate of #1881. Let's continue there, and close this one then.

**Closed** 2017-09-21 21:01 UTC
