### ISSUE TITLE
Memory providers (dependency) broken with 2.0.0-rc1?

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#4117] opened 2018-03-03 10:07 UTC
Hi,

Thanks for an amazing solution. I've been enjoying and working with it for awhile now, and it's great! Things starts to shape up for the 2.0.0 release, and I'm excited to see the release when ready.

However, maybe there is an issue with memory providers dependency since the 2.0.0-rc1 release, and I noticed it when the streams in my old solution didn't work anymore. Following the instructions from the documentation, configuring the silo host, and then adding memory grain storage (as a test), like so:

       private static async Task<ISiloHost> StartSilo()
        {
                // define the cluster configuration
                var siloPort = 11111;
                int gatewayPort = 30000;
                var siloAddress = IPAddress.Loopback;

                var builder = new SiloHostBuilder()

                        .AddMemoryGrainStorageAsDefault()

                        //configure ClusterOptions to set CluserId and ServiceId
                        .Configure(options => options.ClusterId = "helloworldcluster")
        ...

The following exception is thrown at silo startup:

	Exc level 0: System.ArgumentException: Cannot find an implementation class for grain interface: Orleans.Storage.IMemoryStorageGrain. Make sure the grain assembly was correctly deployed and loaded in the silo.
	   at Orleans.GrainFactory.GetGrainClassData(Type interfaceType, String grainClassNamePrefix)
	   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix)
	   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
	--- End of stack trace from previous location where exception was thrown ---

The solution is using the NuGet package 'Microsoft.Orleans.Server' (version 2.0.0-rc1), that itself depends on 'Microsoft.Orleans.OrleansProviders (>= 2.0.0-rc1)'. I've added (not needed, but to try) the NuGet package 'Microsoft.Orleans.OrleansProviders' (version 2.0.0-rc1), but it doesn't help.

Looking into the respository, I see that there is indeed an implementation for IMemoryStorageGrain, at [MemoryStorageGrain](https://github.com/dotnet/orleans/blob/1186a967944607aac20e28221365a8707176cfb9/src/OrleansProviders/Storage/MemoryStorageGrain.cs), with namespace 'Orleans.Storage'.

It's easy to verify that the implementation is known in the solution by simply referring to it, e.g.

        var p0 = new Orleans.Storage.MemoryGrainStorage()

But for some reason it's not found by the silo when it starts.

I have no idea why it fails.

Kind regards,
Jan

**Comment by jan-johansson-mr** [comment] 2018-03-03 10:34
Hi,

I've solved the issue, by adding the 'MemoryGrainStorage' as an application part:

        private static async Task<ISiloHost> StartSilo()
        {
                // define the cluster configuration
                var siloPort = 11111;
                int gatewayPort = 30000;
                var siloAddress = IPAddress.Loopback;

                var builder = new SiloHostBuilder()

                        .AddMemoryGrainStorageAsDefault()

                        //configure ClusterOptions to set CluserId and ServiceId
                        .Configure(options => options.ClusterId = "helloworldcluster")

                        //Configure local primary silo using DevelopmentClustering
                        .UseDevelopmentClustering(options => options.PrimarySiloEndpoint = new IPEndPoint(siloAddress, siloPort))

                        //Configure silo endpoint and gatewayport
                        .ConfigureEndpoints(siloAddress, siloPort, gatewayPort)
                                
                        // Add assemblies to scan for grains and serializers.
                        // For more info read the Application Parts section
                        .ConfigureApplicationParts(parts => {
                                parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences();
                                parts.AddApplicationPart(typeof(MemoryGrainStorage).Assembly).WithReferences();
                        })
                        ...

I'm unsure if this is the right way of resolving the issue, by including framework grains as an application part in the solution.

Thanks,
Jan

**Comment by trevex** [comment] 2018-03-03 11:08
I had the same issue when upgrading. Looking at the samples I noticed `Microsoft.Orleans.Server` is not used anymore and updated my dependencies accordingly ([SiloHost.csproj](https://github.com/dotnet/orleans/blob/master/Samples/2.0/AccountTransfer.NetCore/src/SiloHost/SiloHost.csproj)). This resolved the issue for me.

**Comment by jan-johansson-mr** [comment] 2018-03-04 18:46
I got the same as you. The **parts.AddFromAppDomain()** could be used to scaffold whatever out-of-the-box implementation that exists. But maybe it only works with localhost.

**Comment by ReubenBond** [comment] 2018-03-04 21:01
The part for `MemoryStorageGrain` is supposed to be added automatically for you. The issue was fixed in https://github.com/dotnet/orleans/pull/4091 and the fix will be included in RC2 at the end of this week.

**Comment by sergeybykov** [comment] 2018-03-05 18:50
Closing as a duplicate of #4084. Please reopen if that's not the case.

**Closed by sergeybykov** 2018-03-05 18:50 UTC
