### ISSUE TITLE
The latest code is often compiled with exceptions

### ISSUE THREAD

**Issue by luohuazhiyu** [dotnet/orleans#4802] opened 2018-07-28 03:23 UTC
Asynch agent Runtime.Messaging.IncomingMessageAgent/Application encountered unexpected exception The Stage will be restarted.

Value cannot be null. 

 at System.Threading.Monitor.Exit(Object obj)
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take()
   at Orleans.Runtime.Messaging.InboundMessageQueue.WaitMessage(Categories type)
   at Orleans.Runtime.Messaging.MessageCenter.WaitMessage(Categories type, CancellationToken ct)
   at Orleans.Runtime.Messaging.IncomingMessageAgent.Run()
   at Orleans.Threading.FiltersApplicant`1.Apply(T action)

**Comment by ReubenBond** [comment] 2018-07-28 03:43
@dvakulen any initial impressions on this?

@luohuazhiyu do you have any more information?

**Comment by luohuazhiyu** [comment] 2018-07-28 06:17
@ReubenBond Grain is very busy, and many requests over 30 seconds will throw this error and the Silo will restart

**Comment by dVakulen** [comment] 2018-07-29 18:15
Indeed it looks alike https://github.com/dotnet/orleans/issues/1350#issuecomment-176641395. 

This is happening due to collection disposal, probably at the silo shutdown, but if that is not the case - more log entries of what happened before exception are needed in order to continue investigation.

**Comment by luohuazhiyu** [comment] 2018-07-30 07:45
@dVakulen @ReubenBond The system is magically back to normal.There's no more error log.

**Comment by ReubenBond** [comment] 2018-08-01 02:00
@luohuazhiyu if the issue is resolved, can we close it? We can open it again if the symptoms reappear.

**Closed** 2018-08-01 04:36 UTC
