### ISSUE TITLE
Startup Task fails when old member in membership table

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#4415] opened 2018-04-07 08:19 UTC
I cannot reproduce it yet, but sometimes my application fails to start. When I have old members in the membership table I sometimes get this error:

```
S192.168.43.245:11111:260784881 is rejecting message: Request S192.168.43.245:11111:260784881*stg/14/0000000e@S0000000e->S191.168.43.245:11111:260780891*stg/10/0000000a@S0000000a #4: . Reason = Exception getting a sending socket to endpoint S191.168.43.245:11111:260780891
```

(I just changed the IP address of the entry to simulate it, therefore the message might be not 100% correct). 

For me it seems that the startup tasks are running before the state of the old entries is clarified.  In my startup tasks I run a method on a grain to activate it.

**Comment by benjaminpetit** [comment] 2018-04-13 21:32
I don't reproduce it locally using Azure membership. 

I assume you do not reproduce this issue ith a clean membership table? How do you stop your silos?

**Comment by SebastianStehle** [comment] 2018-04-13 22:00
Yes, I have old members in the table that are still marked as active. I experienced the problem after a node went down in kubernetes and then I reproduced it the following way:

1. Start the silo
2. Stop the silo
3. Change the IP address of the old entry.
4. Restart the silo.

In this case the silo was checking the old entry in the background and marked it as dead after several minutes, but AFTER the startup task was initiated.

**Comment by SebastianStehle** [comment] 2018-04-13 22:13
For me it seems that the placement strategy selects a random silo from the active silos. But there is no guarantee, that a active silo is alive. So the only solutions would be:

1. Wait the 3 minutes to verify the silos
2. Only use the local silo during startups.
3. Retry until succeeded.

**Comment by SebastianStehle** [comment] 2018-04-13 22:16
Btw: I also tested PreferLocalPlacement and it happened less often, but it still happened.

**Comment by benjaminpetit** [comment] 2018-04-16 21:55
When a silo tries to join the cluster, by default, it will try to ping ALL silos marked as active in the membership table before effectively change its status to active. I don't see it in your sample, but you didn't changed the value of `ClusterMembershipOptions.ValidateInitialConnectivity`, correct?

**Comment by benjaminpetit** [comment] 2018-04-16 23:30
Ok some progress here

For some reason I cannot install MongoDB on my dev machine (installer fail at the end). But I confirm with your sample converted to use Azure instead, the new silo will NOT start if it cannot ping a silo marked as "Alive". I see this in the logs:

``` 
fail: Orleans.Runtime.MembershipService.MembershipOracleData[100661]
      -Failed to get ping responses from all 1 silos that are currently listed as Active in the Membership table. Newly joining silos validate connectivity with all pre-existing silos that are listed as Active in the table and have written I Am Alive in the table in the last 00:10:00 period, before they are allowed to join the cluster. Active silos are: ....
```

BUT I can reproduce what you are experiencing if the "Alive" entry is older than 10min. I will dig more

**Comment by benjaminpetit** [comment] 2018-04-17 16:15
After digging in the code and discussing with  @sergeybykov , I believe the current behavior is correct.
The membership protocol has been battle-tested over the year, and the code didn’t change much (for a reason!). But it was written with Azure Cloud Services in mind.

If the silo process is terminated abruptly (like in your case, the silo doesn’t have the time to update its entry in the membership table), in Cloud Services, the process will restart on the same machine, that wil have the same IP address. We have logic to handle this case (see `MemberhipOracle. DetectNodeMigration`)

Not sure if we could implement something like this for container, here when the process crash, a new container will be created with a new IP address, ect. I wonder if K8s/Swarm could set a unique hostname per container based on the container number.

In the meantime, I think you should:

-	Handle errors in your startup tasks
-	Reduce the number of ping allowed to be missed/timeout between pings

**Comment by SebastianStehle** [comment] 2018-04-17 17:18
Not in my case (kubernetes). I think the best approach would be to use stateful sets with kubernetes and propagate the host name. I am not sure, if this is possible now.

**Comment by sergeybykov** [comment] 2018-06-14 21:50
Closing as a duplicate of #4680.

**Closed by sergeybykov** 2018-06-14 21:50 UTC
