### ISSUE TITLE
Grain activation NullReferenceException and code generation

### ISSUE THREAD

**Issue by JaktensTid** [dotnet/orleans#8240] opened 2022-12-24 14:11 UTC
Getting the following error while trying to invoke any method on the grain interface

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Runtime.Catalog.GetOrCreateActivation(GrainId& grainId, Dictionary`2 requestContextData) in /_/src/Orleans.Runtime/Catalog/Catalog.cs:line 271
   at Orleans.Runtime.Messaging.MessageCenter.ReceiveMessage(Message msg) in /_/src/Orleans.Runtime/Messaging/MessageCenter.cs:line 486
--- End of stack trace from previous location ---
   at Orleans.Serialization.Invocation.ResponseCompletionSource`1.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 230
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Orca.Web.Core.HostAllocator.AllocateHosts() in .Orca.Web\Orca.Web\Core\HostAllocator.cs:line 66
```

The object returned by GetGrain is not null, it fails exactly when I call any method on this object
Could you help me please?

**Comment by ReubenBond** [comment] 2022-12-24 20:35
Is that the entire stack trace? What happens when you attach a debugger to the silo, do you see where the exception is coming from?

**Comment by JaktensTid** [comment] 2022-12-24 20:44
Right, thats everything that I have.
How can I attach debugger to the silo? Where should I put my breakpoint?

**Comment by JaktensTid** [comment] 2022-12-24 20:46
Ok, looks like it is fixed, but I still don't see what was the issue. I moved my dependency injection registrations with IServicesCollection below .UseOrleans call and it works right now. However exception above is cryptic and is not helpful at all

**Comment by ReubenBond** [comment] 2022-12-24 20:48
Could you show the code for your service registration?

**Comment by JaktensTid** [comment] 2022-12-24 20:50
I am using IntelliJ Rider, put the checkbox to see all the exceptions. Exception occures in 

`if (!SiloStatusOracle.CurrentStatus.IsTerminating())`
 on line 271 in `Catalog.cs` file.

SiloStatusOracle object is null for some reason

` public static void Configure(IServiceCollection serviceCollection, ConfigurationManager configurationManager)
    {
        serviceCollection.AddTransient<IHostAllocator, HostAllocator>();
        serviceCollection.AddHostedService<HostAllocatorBackgroundService>();
        serviceCollection.AddDbContextFactory<DbService>(options =>
            options.UseNpgsql(configurationManager.GetConnectionString("postgres")));
        serviceCollection.AddSingleton<IVirtualMachinesStorage, VirtualMachinesStorage>();
        serviceCollection.AddSingleton<ICloudHostPlanMapper, CloudHostPlanMapper>();
        serviceCollection.AddSingleton<ICloudProvider, CloudProvider>();
        serviceCollection.AddScoped<IUserProvider, UserProvider>();
    }`

This is my services registration.
I have one more issue. Will open in a separate thread

**Comment by ReubenBond** [comment] 2022-12-24 20:50
This is how you tell VS to break when an exception is thrown: https://learn.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2022#tell-the-debugger-to-break-when-an-exception-is-thrown

**Comment by ReubenBond** [comment] 2022-12-24 20:53
Ok, so the issue is fixed by moving the configuration after .UseOrleans because you have a background service which is trying to call into Orleans, but Orleans wouldn't have been started by that time. Hosted services are started in registration order and UseOrleans registers a hosted service (the silo).

**Comment by JaktensTid** [comment] 2022-12-24 20:54
Got it. Thank you for your help!

**Closed** 2022-12-24 20:54 UTC
Labels: Needs: triage :mag:
