### ISSUE TITLE
[2.0][question] Is it possible to opt out (partially) from CodeGen?

### ISSUE THREAD

**Issue by lmagyar** [dotnet/orleans#4437] opened 2018-04-09 21:21 UTC
When I have a custom serializer for the grain state, is it necessary to generate anything for it?

Currently I refer System.Activities + related .dll-s, codegen goes berserk and generates the whole world and beyond, it generates 2k lines of code, even for `System.Func`. But when I use XAML and there are generated .cs files from XAML, it generates 5k lines. The generation is slow, the build is slow, the startup is slow. :(

[2k line repro](https://github.com/OrleansContrib/Orleans.Activities/tree/samples-master)
[2k line repro "permalink"](https://github.com/OrleansContrib/Orleans.Activities/tree/577e7651df59e8d80dfda3642a059e4ec8ca7a2b)
**NOTE:** This is the plain/coded (.cs) activity version. This version runs.

[5k line repro](https://github.com/lmagyar/Orleans.Activities/tree/samples-xaml)
[5k line repro "permalink"](https://github.com/lmagyar/Orleans.Activities/tree/75f54b293bd06a1a71d4ce490e864117b7d5571d)
**NOTE:** This is the designed (.xaml) activity version. *It builds, but won't run! Xaml codegen is another Vietnam.* :/ WIP

The HelloGrain's State:
```
    public class WorkflowState : IWorkflowState
    {
        public IDictionary<XName, InstanceValue> InstanceValues { get; set; }
        public WorkflowIdentity WorkflowDefinitionIdentity { get; set; }
    }
```

There is a custom serializer in the Orleans.Activities NuGet pkg for the first field (the other is a string/int bag). The InstanceValue dictionary contains eg. the WF state, depends heavily on the DataContract/DataMember world, there is a good chance, it will always require a custom serializer.
```
    [Serializer(typeof(Dictionary<XName, InstanceValue>))]
    public static class InstanceValueDictionarySerializer
    { ... }
```
**NOTE:** It refers the `Dictionary` class, not the `IDictionary` interface.

Is it somehow possible to opt out on some level from codegen? Eg. opt out the complete chain starting from System.Activities and other assemblies, and optionally opt in some simple types???

**Comment by ReubenBond** [comment] 2018-04-10 02:00
You *can* fully avoid code generation if you want, but there's currently no way to instruct the code generator to be so selective about what it examines.

When you say it generates code for Func for example, you mean that it adds a "known type" for Func, not that it generates an entire serializer for it, right?

**Comment by lmagyar** [comment] 2018-04-10 08:51
Yes there are only endless `feature.AddKnownType(...` calls.

To opt out codegen should I add something next to my `[Serializer(typeof(MyType))]` decorated POCO serializer? Will this be automatically executed at startup?
```
[assembly: FeaturePopulator(typeof(MyFeaturePopulator))]
...
internal sealed class MyFeaturePopulator : IFeaturePopulator<SerializerFeature> {
    public void Populate(SerializerFeature feature) {
        feature.AddSerializerType(typeof (...Dictionary<...XName, ...InstanceValue>), typeof (...InstanceValueDictionarySerializer));
    }
}
```

Or should I use `IExternalSerializer` and `options.SerializationProviders.Add(typeof(MySerializer).GetTypeInfo());`? Developers will forget to add it. :(

But in this case nobody will register the Grain implementation with `feature.Classes.Add()` and nobody will generate serializer for custom, descendant grain states. :(

I think we can't opt out completely in grain implementation projects.

Only the endless AddKnownType should be cut shorter, everything else seems to be perfect. I know nothing about the codegen internals, if there is a recursive discovery, it should stop at a property that has a custom serializer in one of the referred assemblies, or decorated explicitly with some new otp-out attribute. Is it viable or nonsense? I've tried hard not to tinker with Orleans internals, maybe I should get used to it. :)

**Comment by ReubenBond** [comment] 2020-01-14 18:12
Closing this as a duplicate of #5021 - both are valid & ought to be remedied

**Closed by ReubenBond** 2020-01-14 18:12 UTC
