### ISSUE TITLE
Failed to register activation in grain directory

### ISSUE THREAD

**Issue by xelanrok** [dotnet/orleans#8622] opened 2023-09-04 17:19 UTC
Hi there!

Orleans version: 7.2.1

I've got an error when I call grain's method from orleans client. It happens not for all grains of this type. Thousands of grains are working but some of them are not(~1%) and calling the grain methods are not executed on some silo.

Client side error:
``One or more errors occurred. (Forwarding failed: tried to forward message 
Request [S10.58.5.19:11001:52830029 sys.client/24a06511131d4dd5a309aaf87054434e]->[S10.58.4.210:11001:52829714 devicemodel/device] SharedGrainLibrary.IDeviceGrain.GetState() #1924109[ForwardCount=2] 
for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now. )
``

I use migration functionality and maybe it affects the registration process for grain. For example:
`
var device = _grainFactory.GetGrain<IDeviceGrain>(identity);
`
`
device.Cast<IGrainManagementExtension>().MigrateOnIdle();
` 

I have no idea if it is related or not  but I found many errors that I didn't get in the previous orleans version.

``
Error while migrating 33 grain activations to S10.58.4.210:11001:52829714 System.NotSupportedException: Type encoding version 32 is not supported
``
Full trace log for the error  [trace.log](https://github.com/dotnet/orleans/files/12515583/trace.log)

Thanks

**Comment by ReubenBond** [comment] 2023-11-03 18:19
Apologies for getting to this so late. Are you able to reproduce this? If we can create a repro (minimal or otherwise), then we can may be able to identify and fix the issue. If there's any more information which you can provide, such as any custom serializer registrations (including JSON, etc) or grain migration hooks (`IGrainMigrationParticipant`), then that will be helpful.

**Comment by ReubenBond** [comment] 2023-11-08 04:51
I believe you are seeing two issues. The directory registration issue was fixed in v7.2.3, and the issue you are seeing with migration will be fixed in the next release, soon (#8709).

**Comment by ReubenBond** [comment] 2023-11-11 18:39
Closing for now since I believe this is fixed

**Closed by ReubenBond** 2023-11-11 18:39 UTC
Labels: Needs: author feedback
