### ISSUE TITLE
Rename Microsoft.Orleans.OrleansServiceBus package to Microsoft.Orleans.Streaming.EventHubs

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6954] opened 2021-02-11 14:20 UTC
The current package name is very unintuitive. This change needs to be made to the Orleans.Streaming.EventHubs.csproj file's PackageId property.

See also #6787

**Comment by QueenCitySmitty** [comment] 2021-02-18 19:11
Hey Reuben,

Two questions on this:
1. Dupe of #6718?
2. Is this just a simple rename of the csproj and the references?  I'm trying to figure out how the packages are published to nuget but it isn't apparent. I did a rename locally and have the package building locally, but just wanted to make sure this package is built right e2e:
![image](https://user-images.githubusercontent.com/8077887/108408511-f65c0600-71d9-11eb-83ea-b63623468233.png)

LMK any other complexities, and I can put out a PR for this.

**Comment by ReubenBond** [comment] 2021-02-18 19:26
Total dupe, you're right, thanks.

I think your change is all that's needed (changing the PackageId). I would probably also change the RootNamespace property in that project to match (or delete it).

**Comment by QueenCitySmitty** [comment] 2021-02-22 00:52
Can we close this?

**Comment by ReubenBond** [comment] 2021-02-22 00:54
Yep, thanks. We can auto-close issues with PRs if the PR description includes wording like "Fixes #xxxx" or "Closes #xxxx"

**Closed** 2021-02-22 00:54 UTC

**Comment by QueenCitySmitty** [comment] 2021-02-22 00:56
Gottcha, I'll do that in the future.
