### ISSUE TITLE
Multi-cluster deployment not auto-detecting cluster failure

### ISSUE THREAD

**Issue by jfreitasTrustev** [dotnet/orleans#5153] opened 2018-10-31 16:17 UTC
Hi
I'm currently trying to run a modified version of the orleans tic tac toe sample app (modified to have state), over a multi-cluster configuration.
While I was able to deploy and run the application successfully over two separate azure regions, this deployment doesn't withstand a region shutdown.
We're trying to do this to prove out using multi-cluster configuration as a viable option to create an active-active solution for our product, which is based on a single orleans cluster.
I was expecting that once one of the clusters shuts down, the cluster that is up and running would keep functioning, but looking at the orleans dashboard logs, it looks like it keeps trying to connect to the other region.
I've also noticed that the gossip channels aren't updated (azure tables), which is why I think the active cluster keeps trying to connect to the other cluster.
At the moment we're using a static configuration that looks like this:

`<MultiClusterNetwork
  ClusterId="##ORLEANSCLUSTERID##"
  DefaultMultiCluster="##ORLEANSCLUSTERIDARRAY##"
  BackgroundGossipInterval="30s"
  UseGlobalSingleInstanceByDefault="true"
  GlobalSingleInstanceRetryInterval="5s"
  GlobalSingleInstanceNumberRetries="1"
  MaxMultiClusterGateways="10">
  <GossipChannel  Type="AzureTable"  ConnectionString="##GOSSIPCHANNELCONNECTIONSTRING##"/>
  <GossipChannel  Type="AzureTable"  ConnectionString="##GOSSIPCHANNELCONNECTIONSTRING_2##"/>
</MultiClusterNetwork>`

The cluster only returns back to normal once all the clusters are restarted.
Question is, should I expect the application to work once one cluster is shutdown? Am I missing something on my configuration to get this to work with only one cluster up and running?

Running this sample app on v1.5 which will be the version we aim to run our production deployment on as well.

Thanks.

**Comment by sergeybykov** [comment] 2018-10-31 16:24
@sebastianburckhardt Please correct me if I'm wrong here.

Multi-cluster does not (by design) have auto-detection of a cluster failure. That requires an explicit action by an operator or some external monitoring solution to inject an updated configuration with the failed cluster removed.

http://dotnet.github.io/orleans/Documentation/deployment/multi-cluster_support/Overview.html
>Multi-Cluster Configuration Injection. At runtime, the service operator can specify and/or change the multi-cluster configuration, which contains a list of cluster ids, to specify which clusters are part of the current multi-cluster. This is done by calling the management grain in any one of the clusters.

**Comment by sergeybykov** [comment] 2018-10-31 16:27
BTW, why are you targeting 1.5, and not 2.1? 1.5 might only get critical bug fixes going forward as all new development moved to 2.x.

**Comment by jfreitasTrustev** [comment] 2018-10-31 16:30
Our end goal is to move to 2.0, but our application is currently running 1.0.10 and we felt it was a easier move to go up first to 1.5 and then plan the move to 2.x.

**Comment by sebastianburckhardt** [comment] 2018-10-31 17:02
Right, clusters are not automatically marked "down". 

The idea is that the grains can keep working even if they are not receiving responses from a remote cluster. Exactly what that means depends on the grain you are using.

**Comment by jfreitasTrustev** [comment] 2018-10-31 17:16
Not sure if I'm following how that would work.
The scenario we are currently seeing is the following:
Grain A lives on Silo A that is part of cluster A.
We shut down cluster B, and can no longer access Grain A, and looking at the logs, Silo A seems busy trying to connect to Silo B on Cluster B which is no longer accessible.

The same thing occurs if we shut down cluster A where the grain we tried to access lives.

**Comment by sebastianburckhardt** [comment] 2018-10-31 17:40
Sounds like your are using the Global-Single-Instance grain.

> Silo A seems busy trying to connect to Silo B on Cluster B which is no longer accessible
It is normal to see failing connection attempts in the log. Those should however not impact availability.

> Since one cluster is down, shouldn't the active cluster's silos be able to create a doubtful activation of any grain we tried to access?
Yes, that is my understanding as well. Not sure why this is not happening in your case.

**Comment by jfreitasTrustev** [comment] 2018-10-31 17:45
Yes. That's correct. All grains are marked as GlobalSingleInstance grains.
Like you previously said I was expecting new activations to occur after that one cluster went down.

Since there is no mechanism to automatically mark clusters down, is this still the expected behavior?

**Comment by sergeybykov** [comment] 2018-10-31 17:47
New activations should be able to get created on silos in cluster A when cluster B is down, even before it is officially removed from the configuration.

**Comment by sebastianburckhardt** [comment] 2018-10-31 19:06
I did a bit of testing (using just the HelloGeoSample we had for 1.x) and I can repro the problem... I will have to investigate more but it looks like for some reason the stale entry (i.e. the cache entry pointing at a no longer existing or reachable silo) does not get removed, so a new instance does not get created.

**Comment by pmgriffin** [comment] 2018-11-02 12:01
Hi Folks,

i'm a colleague of Joao's, we're wondering if this issue has been addressed in 2.x ?  

Paul.

**Comment by sergeybykov** [comment] 2018-11-02 20:53
No, it hasn't been addressed in 2.x. We'd need to fix it in `master` and then backport to 1.5.x if needed.

**Comment by sebastianburckhardt** [comment] 2018-11-13 15:04
The problem is in the grain directory logic. It seems that the process for removing cached grain references to remote clusters is rather ad-hoc - it works in some cases (e.g. when a CacheInvalidationHeader is present, or when the activation is removed in a normal situation without failures) but there are many other cases that are not covered. I don't think this has been thought through very well, and a fix will likely require some work. The best solution I can think of at the moment is to have the grain directory maintainer do a constant, slow periodic background ping to remote clusters and remove all cached references to clusters that are non-responsive.

By the way, only the Global-Single-Instance grain is affected, the JournaledGrain does not have this problem (because each cluster always has its own copy of the grain).

**Comment by sergeybykov** [comment] 2018-11-15 17:29
>The best solution I can think of at the moment is to have the grain directory maintainer do a constant, slow periodic background ping to remote clusters and remove all cached references to clusters that are non-responsive.

Isn't this rather the case that we need to remove all cached references for to a cluster that got removed? Just like what we do when a silo is removed from a cluster. "Non-responsive" is in the eye of the beholder here. Since multi-cluster config gets explicitly updated by an authoritative operator, I think that should treated as an unambiguous signal for clearing caches associated with any cluster that's not in the configuration anymore.

**Comment by sebastianburckhardt** [comment] 2018-11-15 17:52
I think it is worth the effort to design the mechanism so grains remain available even if there is no administrator that watches for failed clusters and removes them. That was always the intention, and we are almost there.

> Isn't this rather the case that we need to remove all cached references for to a cluster that got removed? 

We should definitely do that also.

**Comment by sergeybykov** [comment] 2020-09-26 23:24
Closing this because support for multi-cluster was removed in 3.2.0.

**Closed by sergeybykov** 2020-09-26 23:24 UTC
