### ISSUE TITLE
Turn based timers

### ISSUE THREAD

**Issue by Vhab** [dotnet/orleans#4497] opened 2018-04-20 09:06 UTC
Based on a discussion over at gitter (https://gitter.im/dotnet/orleans?at=5ad930be7c3a01610dfe587d), as well as a need we have internally:

A feature request for a middleground between reminders and timers; timers that participate in the turn based execution on non-reentrant grains.
To phrase it differently, a timer who's callbacks will not interleave with other methods executed on the grain.

**Comment by sergeybykov** [comment] 2018-04-23 06:44
I believe this is a duplicate of #2574.

**Comment by Vhab** [comment] 2018-04-23 06:51
Yep, looks like it is.
Feel free to close this one.

**Closed as completed** 2018-04-23 07:20 UTC
