### ISSUE TITLE
Orleans Streams unclear SequenceToken usage

### ISSUE THREAD

**Issue by yoniabrahamy** [dotnet/orleans#695] opened 2015-08-13 14:14 UTC
In the Orleans documentation it says the `SequenceToken` will be used for 2 purposes:
1. *"Applications can also control their own stream delivery ordering, by using StreamSequenceToken."* 
2. *"Rewindable streams allow to subscribe from an arbitrary point in time in the past by using StreamSequenceToken"*

But when inspected it can be seen that the `PersistentStreamProducer` (the class that is responsible for producing to a stream and is wrapped by `StreamImpl` - the implementation for `IAsyncStream`) does not pass the `SequenceToken` it receives on the function `OnNextAsync` and `OnNextBatchAsync` (the functions that produce events to the stream)

![image](https://cloud.githubusercontent.com/assets/10047833/9249399/3d91a518-41cd-11e5-8ac8-4c2936a961b6.png)

This means that the producer cannot assign it's own `SequenceToken` when producing events, which means it cannot have any control on ordering or making the stream rewindable.

Furthermore, I think the two aforementioned purposes can contradict each other. Purpose no. 1 states that the producer can supply any arbitrary SequenceToken that will be passed to the consumer for controlling ordering, but in order to implement rewindability based on `SequenceToken` the `QueueAdapter` must know how to translate a `SequenceToken` to a physical queue location. How can the `QueueAdapter` do that?

**Comment by gabikliot** [comment] 2015-08-13 22:44
Great question and great catch!
Indeed, we should change the QueueAdapter Interface to accept the token and pass it. It will be up to the adapter how to use it and what it means.
Feel free to submit a PR with that fix, if you wish.
 
Now to a harder question of "how to translate a  `SequenceToken`a physical queue location". The answer is that depends on the physical queue implementation and the adapter implementation.
For example, take a look in [AQ stream provider](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs#L88).
It just uses a local counter that it increments to assign sequence tokens. Is that the right thing to do for AQ? Probably not. This stream provider is more like an example of what can be done. The user of this stream provider needs to understand what sequence number means.
An alternative impl. might be to store the token together with the iten, in the same object, push that into the physical queue and upon receive pass back. It will provide the usage scenario  number 1 from above, but this stream provider will not be rewindable.
Yet a third impl. is not to pass any sequence token on the producer side, but on the receiver side use a sequence token provided from the physical queue (if it provides it). For example, Event Hub stream provider can use the sequence number/offset parameter that EH provides and turn that into Orleans SequenceToken. Such a provider will be also rewinadble.

Since there is such a wide range of physical queue implementations, and potential ordering semantics, we did not want to impose any specific one and wanted to allow any semantics to be implemented, via custom queue adapter. The last example with EH is what we are using in our internal stream provider, and this is why the missing token that was not passed to the adapter was never an issue in our specific usage and thus we missed that bug.

Does that makes sense?

**Comment by jason-bragg** [comment] 2015-08-13 23:33
[yoniabrahamy] “This means that the producer cannot assign it's own SequenceToken when producing events, which means it cannot have any control on ordering or making the stream rewindable.”

Yup, this is incorrect and should be fixed.  This has not been an issue for us because our application level ordering/uniqueness information has been in the event itself, so the token was not needed.  In this pattern the producer generated ordering/uniqueness info is transferred from the event to the sequence token in the adapter.  As Gabriel has also confirmed, this issue you’ve identified is clearly a bug, but if you needed to work around it until the next Orleans update, I’d suggest passing the ordering info in as part of the event.

[yoniabrahamy] “1 states that the producer can supply any arbitrary SequenceToken that will be passed to the consumer for controlling ordering, but in order to implement rewindability based on SequenceToken the QueueAdapter must know how to translate a SequenceToken to a physical queue location. How can the QueueAdapter do that?”
[gabikliot] “use a sequence token provided from the physical queue”

There are two layers here, the producer provided ordering guarantees (which ‘should’ be able to be provided by a producer via passing sequence tokens), and the ordering guarantees provided by the underlying queueing system you’ve selected.  **Queues like EventHub, or Kafka provide strong ordering guarantees that can reduce (if not eliminate) the need for producer provided ordering info**, but the most reliable ordering strategies will take advantage of both application and queue ordering info.  This requires the queue adapter to encode application layer ordering guarantees into the data persisted in the queue on send, and for the queues adapter receiver to use both queue provided ordering info and application layer ordering info to construct a token that has both the details of where the data is in the queue and which order the producer expected the data to be processed.

**Comment by veikkoeeva** [comment] 2015-08-14 06:29
Great information here. Thanks @yoniabrahamy for asking and @jason-bragg and @gabikliot for answering. I link this to https://github.com/dotnet/orleans/issues/634 so that it's readily available.

**Comment by randa1** [comment] 2015-08-16 08:33
@jason-bragg So, if I'm understanding you correctly, the `SequenceToken` will have to be split into two different entities - an application provided `SequenceToken` and a QueueAdapter provided `RewindToken` or such?

**Comment by jason-bragg** [comment] 2015-08-17 20:01
@randa1, I wouldn’t go so far as say ‘have to’ as much as ‘could’.

This really depends on the degree of reliability one needs.  For instance, if one was using EventHub one could use the event hub sequence number in sequence token, without any information from the producer at all, and cover most reliability/recoverability issues.  However if a producer gets a timeout call while sending events to event hub, there may be a question as to how to recover from this.  If one resends the data, there is a risk of duplicating data, because there is no way to know if the timed out send succeeded or not.  If one doesn’t resend, there is a possibility of data loss.  This may or may not be important.  If it is, then this could be resolved by the producer providing ordering information in the events that can also be encoded into the sequence token when this data is read from event hub.  Using this approach the event hub offset/sequence Id could be used to recover from a specific location in event hub, while the application specific sequence Id could be used to drop duplicates in cases where retransmission from the producers was necessary.

This can be generalized into a token containing two entities (application and queue), but such a general abstraction would only really be necessary if you wanted to write general recovery logic that worked for any queue and any application.  We’ve not done this because we’ve not (yet) seen a simple general pattern that is widely applicable.  This is, in part, why we’ve left this to the adapter developers.  Adapter developers can write logic custom to their applications.  Maybe some will develop general components that can be contributed back (hint, hint), but solutions targeted to one’s specific problem are probably more practical.

**Closed** 2015-08-20 15:44 UTC
Labels: bug, question
