### ISSUE TITLE
silo.StopAsync()  indefinite wait

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/orleans#3968] opened 2018-02-05 09:33 UTC
private static async Task StopSilo()
        {
            Console.WriteLine("Start Silo stop");

            await silo.StopAsync();
            
            Console.WriteLine("Silo stopped");

        }

**Comment by benjaminpetit** [comment] 2018-02-06 17:20
Can you post more details? 

- What version of Orleans are you using?
- If using the beta, which OS?
- Can you post more of your code?

Thanks

**Comment by galvesribeiro** [comment] 2018-02-06 18:14
That is the same problem I have here on Windows with 2.0 beta3.

The silo hangs. I noticed that when that method is called, a `TaskCancelledException` is swallowed by the runtime and I have no idea where it is coming from.

**Comment by benjaminpetit** [comment] 2018-02-06 20:26
Using streaming?

**Comment by veikkoeeva** [comment] 2018-02-08 18:27
The `StopAsync` function is for some reason very slow (it doesn't hang, as far as I know). I have not researched the cause further, but stopping can take some minutes even. On the other hand, calling `.Dispose` is pretty much instant.

**Comment by galvesribeiro** [comment] 2018-02-08 18:31
But I _think_ `.Dispose()` will not gracefully shutdown the silo (and essentially not mark the silo as dead on MBR), right?

**Comment by hanxinimm** [comment] 2018-02-10 10:14
@benjaminpetit 
this code 
```
public class Program
    {
        private static ISiloHost silo;
        private static readonly ManualResetEvent siloStopped = new ManualResetEvent(false);
        private static IConfiguration Configuration { get; set; }
        public static void Main(string[] args)
        {
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;

            var EnvironmentName = Environment.GetEnvironmentVariable("NETCOREAPP_ENVIRONMENT");

            silo = CreateSilo(EnvironmentName);

            Task.Run(StartSilo);

            AssemblyLoadContext.Default.Unloading += context =>
            {
                Console.WriteLine("ProcessExit fired");
                Task.Run(StopSilo);
                siloStopped.WaitOne();
            };

            siloStopped.WaitOne();
        }

        private static void TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
        {
            e.SetObserved();

            Console.WriteLine(string.Format(
                    "Identity CommandServer:" +
                    "Exception of non-public type '{0}' has been wrapped."
                    + " Original message: <<<<----{1}{2}{3}---->>>>",
                    e.Exception.GetType().FullName,
                    Environment.NewLine,
                    e.Exception,
                    Environment.NewLine));

            Console.WriteLine("ProcessExit fired");
            Task.Run(StopSilo);
            siloStopped.WaitOne();
        }

        private static async Task StartSilo()
        {
            await silo.StartAsync();
            Console.WriteLine("Silo started");
        }

        private static async Task StopSilo()
        {
            await silo.StopAsync(); //indefinite wait
            Console.WriteLine("Silo stopped");
            siloStopped.Set();
        }
    }
}
```

**Comment by galvesribeiro** [comment] 2018-02-10 17:14
Similar here.

**Comment by SebastianStehle** [comment] 2018-02-12 13:52
For me too. I co-host orleans and would like to let ASP.NET Core manage it.

Can you make an option for this line: https://github.com/dotnet/orleans/blob/master/src/Orleans.Runtime/Silo/Silo.cs#L382

My approach is to register it: https://github.com/Squidex/squidex/blob/orleans3/src/Squidex/Config/Orleans/SiloWrapper.cs

**Comment by benjaminpetit** [comment] 2018-02-12 18:58
> Can you make an option for this line: 

@SebastianStehle I created #4016 for this. I don't think this is related to this issue?

@hanxinimm you say you are using docker, I suppose you are using Linux container in this case? In your current code, could the issue be that in `UnobservedTaskException` you wait for a `siloStopped` event and then again in the main?

**Comment by benjaminpetit** [comment] 2018-03-09 17:59
Closing this issue, if you have any update feel free to reopen it

**Closed by benjaminpetit** 2018-03-09 17:59 UTC
