### ISSUE TITLE
Orleans clustering using consul

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4644] opened 2018-06-01 15:39 UTC
Code using consul clustering
++++++++++++++++++++

var builder = new SiloHostBuilder()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = ConfigurationManager.AppSettings["ClustId"];
                        options.ServiceId = ConfigurationManager.AppSettings["ServiceId"];
                    })
                    .UseServiceProviderFactory(HostStartUp.ConfigureServices)
                    .UseConsulClustering(gatewayOptions =>
                    {
                        gatewayOptions.Address =
                            new Uri("http://10.203.106.62:8500/");
                      })
                    .ConfigureEndpoints(siloPort: Convert.ToInt32(ConfigurationManager.AppSettings["SiloPort"]), 
                        gatewayPort: Convert.ToInt32(ConfigurationManager.AppSettings["GatewayPort"]), hostname: Dns.GetHostName() )
                    .AddMemoryGrainStorageAsDefault();
This is a working code with consul but recently we have ACL enabled in consul and we are not sure how to pass the ACL token from the Orleans silo. 

Do you know how we can pass this token from the Application side?

**Comment by sergeybykov** [comment] 2018-06-08 00:31
Closing as a duplicate of #4652.

**Closed by sergeybykov** 2018-06-08 00:31 UTC
