### ISSUE TITLE
Question/Suggestion: Streams with string/long ids

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1549] opened 2016-03-10 15:20 UTC
Orleans streams currently support only Guid ids. While I understand how long ids can be converted to Guid ids, I don't understand what can be done with string ids. Let's say I want to have a stream of events for a particular Azure VM, that its natural id is a string (the Azure resource id). I'd like to have a grain implicitly subscribed to this stream, with a string id. How do you usually solve the problem of mapping between a natural string id to a surrogate Guid id required by the stream?

**Comment by sergeybykov** [comment] 2016-03-10 16:43
There's already https://github.com/dotnet/orleans/issues/1121 opened for that. In the meantime, you could try hashing strings to 128 bit integers.

**Comment by gabikliot** [comment] 2016-03-12 05:44
Closing, as this is duplicate of #1121.

**Closed by gabikliot** 2016-03-12 05:44 UTC
Labels: duplicate, question
