### ISSUE TITLE
New code generator fails (2.1-RC2)

### ISSUE THREAD

**Issue by srollinet** [dotnet/orleans#5017] opened 2018-09-22 11:06 UTC
Using the new generator, one of my project fails with the following error:

>  Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
>        Task "Exec"
>          "/usr/share/dotnet/dotnet" "/home/sro/.nuget/packages/microsoft.orleans.codegenerator.msbuild/2.1.0-rc2/build/../tasks/netcoreapp2.0/Orleans.CodeGenerator.MSBuild.dll" SourceToSource "/home/sro/projects/xxx/src/Core.Grains/obj/Debug/netstandard2.0/Core.Grains.orleans.g.args.txt"
>          Orleans.CodeGenerator - command-line = SourceToSource /home/sro/projects/xxx/src/Core.Grains/obj/Debug/netstandard2.0/Core.Grains.orleans.g.args.txt
>          -- Code Generation FAILED -- 
>          
>          Exc level 0: System.InvalidOperationException: Unable to find type with metadata name "System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute".
>             at Orleans.CodeGenerator.WellKnownTypes.<FromCompilation>g__Type|0_0(String type, <>c__DisplayClass0_0& )
>             at Orleans.CodeGenerator.WellKnownTypes.FromCompilation(Compilation compilation)
>             at Orleans.CodeGenerator.CodeGenerator..ctor(Compilation compilation, ILogger log)
>             at Orleans.CodeGenerator.MSBuild.CodeGeneratorCommand.<Execute>d__39.MoveNext()
>          --- End of stack trace from previous location where exception was thrown ---
>             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>             at Microsoft.Orleans.CodeGenerator.MSBuild.Program.SourceToSource(String[] args)
>             at Microsoft.Orleans.CodeGenerator.MSBuild.Program.Main(String[] args)
>    1:7>/home/sro/.nuget/packages/microsoft.orleans.codegenerator.msbuild/2.1.0-rc2/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets(122,5): error MSB3073: The command ""/usr/share/dotnet/dotnet" "/home/sro/.nuget/packages/microsoft.orleans.codegenerator.msbuild/2.1.0-rc2/build/../tasks/netcoreapp2.0/Orleans.CodeGenerator.MSBuild.dll" SourceToSource "/home/sro/projects/xxx/src/Core.Grains/obj/Debug/netstandard2.0/Core.Grains.orleans.g.args.txt"" exited with code 3. [/home/sro/projects/xxx/src/Core.Grains/Core.Grains.csproj]
>        Done executing task "Exec" -- FAILED.

In total, I have 4 projects using the generator and only 1 fails.
I use dotnet 2.1.402

I don't know how to provide you more information about the problem.

**Comment by ReubenBond** [comment] 2018-09-22 11:17
Thanks for reporting, @srollinet. Could you include the failing csproj?

Could you also try setting `<OrleansCodeGenLogLevel>Trace</OrleansCodeGenLogLevel>` and post the resulting build log?

It seems we need to be either erroring or skipping that attribute if it's not accessible (likely because the relevant assembly is not referenced).

**Comment by srollinet** [comment] 2018-09-22 11:40
Here is the csproj

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
            <TargetFramework>netstandard2.0</TargetFramework>
            <LangVersion>7.3</LangVersion>
            <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        </PropertyGroup>
        <ItemGroup>
            <PackageReference Include="JetBrains.Annotations" Version="2018.2.1" />
            <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.2" />
            <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.2" />
            <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.1" />
            <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.1.0-rc2" />
            <PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="2.1.0-rc2" />
            <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.1.1" />
            <PackageReference Include="NullGuard.Fody" Version="1.8.3" />
        </ItemGroup>
        <ItemGroup>
            <ProjectReference Include="..\Common\Common.csproj" />
            <ProjectReference Include="..\Core.Contracts\Core.Contracts.csproj" />
        </ItemGroup>
        <PropertyGroup>
            <DefineConstants>$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
        </PropertyGroup>
    </Project>

And the code gen logs:

        Orleans.CodeGenerator - command-line = SourceToSource /home/sro/projects/xxx/src/Core.Grains/obj/Debug/netstandard2.0/Core.Grains.orleans.g.args.txt
         dbug: Orleans.CodeGenerator[0]
               ProjectGuid: 
         dbug: Orleans.CodeGenerator[0]
               ProjectID: (ProjectId, #63e998e1-63f7-41fb-97d2-90699c79c52f - )
         dbug: Orleans.CodeGenerator[0]
               Project: Microsoft.CodeAnalysis.ProjectInfo
         info: Orleans.CodeGenerator[0]
               Workspace creation completed in 483ms.
         info: Orleans.CodeGenerator[0]
               GetCompilation completed in 403ms.
         -- Code Generation FAILED -- 
         
         Exc level 0: System.InvalidOperationException: Unable to find type with metadata name "System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute".
            at Orleans.CodeGenerator.WellKnownTypes.<FromCompilation>g__Type|0_0(String type, <>c__DisplayClass0_0& )
            at Orleans.CodeGenerator.WellKnownTypes.FromCompilation(Compilation compilation)
            at Orleans.CodeGenerator.CodeGenerator..ctor(Compilation compilation, ILogger log)
            at Orleans.CodeGenerator.MSBuild.CodeGeneratorCommand.<Execute>d__39.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Microsoft.Orleans.CodeGenerator.MSBuild.Program.SourceToSource(String[] args)
            at Microsoft.Orleans.CodeGenerator.MSBuild.Program.Main(String[] args)

**Comment by rmja** [comment] 2018-09-22 15:46
I am getting the exact same exception. It also only happens for one out of four projects that references Microsoft.Orleans.CodeGenerator.MSBuild

**Comment by ReubenBond** [comment] 2018-09-22 22:18
Is there any Nitschke difference between those projects?

**Comment by ReubenBond** [comment] 2018-09-24 05:32
Could you also show the relationship between these projects?

**Comment by rmja** [comment] 2018-09-24 15:27
I will see what I can do from my side tomorrow...

**Comment by rmja** [comment] 2018-09-24 18:45
@ReubenBond I found out what is causing the problem. The project that is failing is referencing the `Microsoft.AspNetCore.App` metapackage. You can reproduce it yourself by creating an empty application with this csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.Orleans.Client" Version="2.1.0-rc2" />
        <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" Version="2.1.0-rc2" />
        <PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="2.1.0-rc2" PrivateAssets="All" />
    </ItemGroup>

</Project>
```

Note that it does not fix the issue to explicitly add `System.Diagnostics.Tools` as a dependency.
Just for information: I have tried to run a custom build of the code generator where I have [removed the well known type](https://github.com/dotnet/orleans/blob/master/src/Orleans.CodeGenerator/WellKnownTypes.cs#L22). This lets the generator complete without any other error.

**Comment by sergeybykov** [comment] 2018-09-24 19:46
@rmja I'm curious, why are you using codegen for this project? The typical use cases are grain interfaces and grain implementation projects, not application/exe.

**Comment by srollinet** [comment] 2018-09-24 19:54
In my case, I don't have `Microsoft.AspNetCore.App` in my failing project. But it is the only one that references EntityFrameworkCore.

**Comment by SebastianStehle** [comment] 2018-09-24 20:06
@sergeybykov With the local silo client you can build a monolith with a single project. Very likely not a good idea, but I think the code generator should handle it if possible.

**Comment by rmja** [comment] 2018-09-24 20:36
@sergeybykov I don't know actually. I am still in the early days of learning Orleans, so it must have ended up there by accident. But I am still a little confused after reading the docs. Do I need to include the codegen in all projects that have types which are parameters for grains?

**Comment by sergeybykov** [comment] 2018-09-24 21:35
>Do I need to include the codegen in all projects that have types which are parameters for grains?

Normally, it's enough to include codegen only into grain interfaces/implementation projects. Sometimes, when grain methods use interfaces for argument types and the actual classes are defined in another assembly, you need to explicitly specify those extra types or assemblies for codegen, still within your grain interfaces/implementation projects.

**Comment by ReubenBond** [comment] 2018-09-25 02:51
Current hypothesis is that Roslyn is seeing ambiguities with that type, so it's returning null. I have a solution that I'm testing. Thank you all for your patience and help in resolving this.

**Closed** 2018-09-25 15:41 UTC
