### ISSUE TITLE
Client hangs in 2.0

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#4414] opened 2018-04-07 07:36 UTC
In 2.0rc1 I used the following config. The client is co-hosted in the same process

```
// HOST
builder.UseMongoDBClustering()
builder.ConfigureEndpoints(Dns.GetHostName(), 11111, 40000, listenOnAnyHostAddress: true)

// Client
builder.UseLocalhostClustering(40000)
```

In 2.0 I see the following log entry and the client just hangs in  the connect method.

 ```
fail: Orleans.Runtime.Messaging.IncomingMessageAcceptor[101311]
Gateway received unexpected non-proxied connection from *sgn/01111111-1111-1111-1111-111111111111/11111111 at source address 127.0.0.1:51086
```

It works when I change it to:

    builder.ConfigureEndpoints(IPAddress.Loopback, 11111, 40000, listenOnAnyHostAddress: true)

But I have no idea how the advertised IP address is related to the client connection.

**Comment by SebastianStehle** [comment] 2018-04-13 16:05
A comment would be awesome. This is currently a showstopper.

**Comment by benjaminpetit** [comment] 2018-04-13 16:15
Do you reproduce this issue using azure clustering?

**Comment by SebastianStehle** [comment] 2018-04-13 17:34
No, but I ensured that the cluster protocoll works with other endpoint settings.

**Comment by SebastianStehle** [comment] 2018-04-17 09:39
Here it is: https://github.com/SebastianStehle/OrleansBug

**Comment by benjaminpetit** [comment] 2018-04-17 16:48
Testing it, but you should remove the connection string and revoke the keys!

**Comment by SebastianStehle** [comment] 2018-04-17 17:16
I know, thx.

**Comment by benjaminpetit** [comment] 2018-04-17 17:50
I finally identified the issue: I think this is caused by #4254 

The following check in `Gateway.TryToReroute` is not valid when you don't declare the same IP address in the silo and in the client

``` charp
if (msg.TargetGrain.IsSystemTarget && !this.gatewayAddress.Matches(msg.TargetSilo))
    return msg.TargetSilo;
```

The fix should be trivial for the `localhost` case, but not for the general use case....

**Comment by SebastianStehle** [comment] 2018-04-17 18:00
It is working fine with RC1, not sure about RC2, skipped it. I am co-hosting orleans and asp.net core. Therefore the setting makes sense for me.

**Comment by benjaminpetit** [comment] 2018-04-17 18:18
As a workaround, for now, you need to specify the same IP address in the silo and the client config for the gateway.

On the client you should use the `UseStaticClustering` method

**Comment by benjaminpetit** [comment] 2018-04-17 19:44
After thoughts, I am less pessimistic: it doesn't make sense to use IP A in the silo config and IP B in the cluster config, except for this localhost case.

I will open a PR to fix that

**Comment by SebastianStehle** [comment] 2018-04-18 11:54
I am fine to use the same IP ;)

**Comment by benjaminpetit** [comment] 2018-04-23 20:57
Do you have time to check a recent nightly build to see if your use case is fixed?

**Comment by SebastianStehle** [comment] 2018-04-25 12:56
Seems to work now :)

**Comment by benjaminpetit** [comment] 2018-04-26 17:09
I can close it then! Thanks!

**Closed by benjaminpetit** 2018-04-26 17:09 UTC

**Comment by stephenlautier** [comment] 2018-04-30 11:44
We have a similar issue as this, however, we are not co-hosting it in the same process, we are using docker swarm.

It used to work in rc2 and now when we moved to 2.0.0 its not working anymore.
We did not have the IP address set as mentioned above and we were getting the same error mentioned 
e.g.

```
Gateway received unexpected non-proxied connection from *sgn/01111111-1111-1111-1111-111111111111/11111111 at source address 10.0.4.79:46253
```
Now we set them as the same IP and its throwing a different error

```
Unable to connect to gateway at address gwy.tcp://10.0.4.15:30000/0 on trial 1 (Exception: Could not connect to 10.0.4.15:30000: ConnectionRefused)
```

Any help would be highly appriciated, thanks!

**Comment by stephenlautier** [comment] 2018-04-30 16:42
Nevermind this specific issue seems oki

**Comment by Neftedollar** [comment] 2019-08-29 15:35
@stephenlautier how did you fix it?

**Comment by stephenlautier** [comment] 2019-08-29 18:39
> @stephenlautier how did you fix it?

I forgot the exact issue, but I believe it was incorrect configuration for the silo port/address or something similar
