### ISSUE TITLE
Generic grain extension call causes it's activation request to fail.

### ISSUE THREAD

**Issue by dVakulen** [dotnet/orleans#1624] opened 2016-03-30 23:19 UTC
The first request to generic grain using it's non-generic or generic with different from the grain's type arguments extension reference leads to the following exception: 

`Orleans.Runtime.OrleansException : Orleans.Runtime.OrleansException: Error creating activation for UnitTests.Grains.GenericGrain``1. Message NewPlacement Request S127.0.0.1:6515:197015154*cli/cfede2a7c->S127.0.0.1:6516:197015164*grn/CE1C219C/b47826ad@6595bbbc: global::Orleans.Async.IGenericGrainExtension:Test() ---> System.ArgumentException: Cannot create an instance of UnitTests.Grains.GenericGrain``1[T] because Type.ContainsGenericParameters is true.\r\n at System.RuntimeType.CreateInstanceCheckThis()\r\n at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)\r\n at System.Activator.CreateInstance(Type type, Boolean nonPublic)\r\n at System.Activator.CreateInstance(Type type)\r\n at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments) in src\OrleansRuntime\Catalog\Catalog.cs:line 624\r\n at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericInterface) in \src\OrleansRuntime\Catalog\Catalog.cs:line 468\r\n at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary2 requestContextData, Task& activatedPromise) \src\OrleansRuntime\Catalog\Catalog.cs:line 454\r\n at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message) in src\OrleansRuntime\Core\Dispatcher.cs:line 85\r\n --- End of inner exception stack trace ---\r\n at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message) in src\OrleansRuntime\Core\Dispatcher.cs:line 127`

This is regression after https://github.com/dotnet/orleans/pull/1604.

**Comment by jasonholloway** [comment] 2016-03-31 20:32
This'd be because casting now over-optimistically discards the generic type info of the original grain reference, whereas previously it erroneously carried it about as its own.

I think, in the case of references to already-activated grains, the rash discarding causes no problem, as after activation the only thing required is information about the interface you're approaching the grain by, and the cast reference correctly has that (whereas before it did not, just to re-emphasise!)

But as soon as the virtual reference needs to activate as well as access - either because of deactivation or because (as in your test) no prior activation has taken place at all - then the newly-cast reference's type information is found wanting, maybe even (depending on the registration of concrete types) contradictory.

The unpalatable ideal solution, I think, would be for cast virtual references to retain a link to the original, virtually 'creating' reference, so that in the happy client-side world of GrainReferences all the type information necessary for future activations is retained.

**Comment by jasonholloway** [comment] 2016-03-31 20:39
This would though require an extended way of communicating this info to whatever agent it is that orchestrates activations. I think.

**Comment by dVakulen** [comment] 2016-04-01 00:32
@jasonholloway Will you try to make a fix? If not I'll do it.

**Comment by jasonholloway** [comment] 2016-04-01 08:08
Go for it - have also sent a PR to your PR with some further testing

**Comment by gabikliot** [comment] 2016-04-02 05:48
@jasonholloway , something does not sound right in your above explanation.
The rule that we should follow is:
If the Cast succeeds, the new grain reference should have all the information that is needed to uniquely identify (and activate) a grain, without any prior knowledge of any prior activation.
If that is not possible (to have all the information in that Grain Reference), then the Cast should not have been allowed (the Cast should fail).

If somehow the rule is not followed now, than its a bug and we should fix it.

Cc: @sergeybykov , @ReubenBond .

**Comment by jasonholloway** [comment] 2016-04-02 14:28
I think we're just disagreeing on how things should be packaged up - you're imagining the cast reference as being independent and self-sufficient, but retaining the ``GrainId`` determined by the original reference request.

This amounts to the same as what I was talking about, but is much less over-complicated, and is what is in place now, so we're in agreement really, and all is fine.

The problem is, as you say, with bugginess: a ``GrainId`` passed between references should retain all the type info needed to activate correctly. The ``GenericReference.GenericArguments`` prop should have nothing to do with it (and this is what #1604 changed) - and so, yes, my above explanation was wrong.

**Comment by jasonholloway** [comment] 2016-04-02 16:00
The exception generated here is because, in the target silo, ``Catalog.CreateGrainInstance`` is receiving a null ``genericArguments`` argument.

So, an upstream bug (or indeed, a design flaw) is meaning that this isn't being communicated once a reference has been cast to a non-generic interface.

But (and to qualify the 'design flaw' accusation) why is this information being provided in parallel in the first place? Shouldn't all the requisite type information be encoded in the successfully-received ``GrainId``?

**Comment by dVakulen** [comment] 2016-04-02 16:59
I'm actually wondering about possible use cases of the #1604. 
[Here's the test grain implementation](https://github.com/dotnet/orleans/pull/1604/files#diff-0b8e4c7041f12f0891823f612560c2ecR628). and  [ test of it's casting](https://github.com/dotnet/orleans/pull/1604/files#diff-60378c03392e3dfd3bef2684ec7857bfR658)  that should've shown it. And such casting requires knowing about implementation including it's generic type arguments, plus for this concrete grain there is only 1 valid cast to it's generic implementation - `as ISomeGenericGrain<string>` - all other casts will fail at runtime. Not to mention that implementing multiple `IGrainWith...Key` is highly error prone as the key types may differ. Wouldn't the better solution be to just describe clean interface hierarchy so that no implementation detail could leak outside?

**Comment by gabikliot** [comment] 2016-04-02 17:04
So it looks like we should be able to write another test, without using extensions, when we start with generic grain ref, not activate, and then cast to non-generic and activate. 
Your test in #1604 was doing the other way around - first non-generic, cast to generic and activate next. I don't want extension (as in #1625) to be any concern/complication in that story. They are internal and different beast.

I would argue that we should start by having those 2 tests together and not just one, and either both pass or if only one, we should either fix it, or revert your #1604 to preserve back ward compat and the think longer term how to fix both.

Can you please start by adding this extra reverse direction test?

**Comment by gabikliot** [comment] 2016-04-02 17:14
@dVakulen , can you start by reproducing the current problem without using extensions?

**Comment by dVakulen** [comment] 2016-04-02 17:17
@gabikliot Yes, will add it to the #1625

**Comment by jasonholloway** [comment] 2016-04-02 21:11
@gabikliot I've already added exactly such a test to #1625, which fails - see [here](https://github.com/dotnet/orleans/pull/1625/commits/25a1b5c89baf4c0dcfcb3a7b9c74c26c1e1fc471#diff-60378c03392e3dfd3bef2684ec7857bfR696).

**Comment by jasonholloway** [comment] 2016-04-02 21:20
@dVakulen my original use case was, I reckon, legit: I had a grain that returned another, differently-typed interface via a method (a collection, as it happens) - and it was entirely an internal matter for the grain implementation whether it returned a reference to a completely different grain to fulfil this, or whether it just returned itself via a cast (which was needed for the serialization to work, I seem to remember). In such a case I think a cast outside of the interface hierarchy is reasonable, because the concrete grain knows its own capabilities.

**Comment by gabikliot** [comment] 2016-04-03 01:07
Ok, I think I understand the problem now.
In short: the generic to non-generic should succeed, while the non-generic to generic should not work, by design. Thus, you change in #1624 turn it up side down, and broke it.

Explanation: lets start by taking a step back and looking systematically:
1) `Grain GenericGrain<T> : IFoo<T>`
2) `IFoo<int>gr1 = GrainFactory.GetGrain<IFoo<int>>(1)`
3) `Foo<string>gr2 = GrainFactory.GetGrain<IFoo<string>>(1)`

gr1 and gr2 are references to 2 **different grains**, pointing to 2 grains of different grain types. `IFoo<int>` and `IFoo<string>` are different types and therefore gr1 and gr2 are different types. A Cast from gr1 to gr2 should fail, as trying to Cast incompatible types. This is consistent with standard .NET generics semantics: List<int> and List<float> are different types. If you will try to use gr1 and gr2, they will activate different activation of of different grains.
This was the key point, everything else simply follows in an attempt to preserve the above semantics.

----
**Down Cast**:
Now lets say `GenericGrain<T>` also implement `ISimple` which is non generic, you have gr1 and you are trying to Cast (Cast or AsReference) to ISimple gr3. 
`ISimple gr3 = gr1.AsReference<ISimple>()`
This should be allowed. BUT, the gr3 you get back MUST have the original type of g1 in it (it must carry inside the generic arg int). This is since Cast from gr1 to gr3 is merely an "alias". Underlying the grain ref it points to the same grain.  If we were to loose the generic arg from gr3, we would have a different type pointing to a different grain type. Why? See below.

----
**Half baked type**:
Now lets say you want to go the other way around: you start with gr3:
`ISimple gr3 =  GrainFactory.GetGrain<ISimple>(1)`
this should simply not be allowed, since it does  not have the generic arg. If we did allow it, and used gr3 directly to send msg to the grain, what generic arg would we use to activate it? What would be the type of that grain? So we should throw on such GetGrain. We should not allow to create "half-baked" type.

The outcome is that gr3 (non -generic reference to a generic grain) has always to be a fully qualified type upon first creation or Cast and it cannot loose the original generic arg. 

---

This should be preserved of course transitively.

Also, notice that in this whole discussion I never mentioned activations. This is since this is all totally unrelated to activations. Its about **grain type system**.

I suspect your PR #1604 broke the above rules (we used to preserve the generic arg and you removed it), allowing wrong Cast, and as a result dis-allowing down Cast. We should probably revert and it also enforce correct casts, by throwing when attempted and by preserving the generic arg in down Casts.

**Comment by dVakulen** [comment] 2016-04-03 01:27
Great explanation, @gabikliot!  The tests from https://github.com/dotnet/orleans/pull/1625 probably still should be merged to prevent such changes in future.

**Comment by jasonholloway** [comment] 2016-04-03 09:57
My laptop's about to die, so I won't be able to respond properly for a bit, but just wanted to pick fault with the first part of your post: normal .NET semantics lead the programmer to understand casting as operating on the underlying type of the variable, not on its interface. Special knowledge of types has its place, though I agree it shouldn't be encouraged. Interrogative attempted casting of types definitely has its place.

Another way of approaching it: your assumption that gr1 and gr2 are different types because their interfaces are doesn't hold. And I don't mean to say that as if I'm laying down a principle - I mean, given how types are resolved in Orleans, it's always entirely possible - and transparent to the programmer - that the same type fulfils both.

Anyway, will respond properly this evening hopefully!

**Comment by gabikliot** [comment] 2016-04-03 18:06
Don't see how this could be argued against:
`GenericGrain<int>` and `GenericGrain<string>` are two different types, obviously not castable to each other.
Therefore, `GenericGrain<int>(1)` - grain of type `GenericGrain<int>` and `GenericGrain<string>(1)` - grain of type `GenericGrain<string>` are two different grains (since they are (logical) instances of different types), and therefore gr and gr2 must be grain references of different, non castable types.
The story has to be consistent.
End of story.

**Comment by jasonholloway** [comment] 2016-04-04 07:39
I had this kind of thing in mind:
``Grain LakeGrain : IRemoteBag<Fish>, IRemoteBag<Boat>``
(with ``IRemoteBag<T>`` itself being a grain interface)

1) in this case, if casting is regulated according to the implementing grain type rather than the exposed interface, then you should be able to cast between normally incompatible interfaces.

2) also in this case, as soon as a reference to an ``IRemoteBag<Fish>`` is made, and is resolved to LakeGrain, you immediately have another generic argument specified for another potential interface (amounting to ``IRemoteBag<Boat>``). That is, generic arguments should be scoped to only the interfaces they apply to, to allow possibilities like the above.

**Comment by jasonholloway** [comment] 2016-04-04 07:45
What this really amounts to, is that Orleans has to recreate a fair portion of the .NET type system - the cost of doing its own binding.

**Comment by gabikliot** [comment] 2016-04-04 08:01
I am not sure what is your question.
Also, if you do have a question, please write down the code samples that you would want to write and we can look together if they indeed should work or not.

> Orleans has to recreate a fair portion of the .NET type system - the cost of doing its own binding.

Now sure about the exact size of the "fair portion", but we definitely needed to do quite a lot of "stuff". The Orleans runtime was a multi-year work and is a big undertaking.

**Comment by gabikliot** [comment] 2016-04-05 03:20
@sergeybykov , did you see this issue?
My recommendation, given that you agree with the above, is:
1) Revert #1604.
2) Add more tests to check that disallowed Cast operations are indeed fail and not by mistake create wrong grain references. I hope @dVakulen may want to help with that.
3) Update the runtime with enforcing correct Cast in case some errors are revealed in 2.
4) Add tests for the extra cases mentioned by @jasonholloway above in https://github.com/dotnet/orleans/issues/1624#issuecomment-205176658.
5) Update the runtime to support those cases in 4 or cleanly disallow them, based on the investigation of those cases.

**Comment by sergeybykov** [comment] 2016-04-05 03:33
@gabikliot It was my fault to merge https://github.com/dotnet/orleans/pull/1604.

I agree that we need to revert it. Then we need to re-enable the tests added by @dVakulen that are now being skipped. That's the minimum I think we have to do for 1.2.0.

I agree with the rest of the plan, too. But it doesn't have to be implemented for 1.2.0.

**Comment by gabikliot** [comment] 2016-04-05 05:58
Yes,

**Comment by gabikliot** [comment] 2016-04-05 05:58
Yes,

**Comment by gabikliot** [comment] 2016-04-05 05:59
Yes, totally agree. Closed and reopened the issue by mistake.
What is important I think is not to ship 1.2 with this breaking change.

**Comment by jasonholloway** [comment] 2016-04-05 08:00
For what it's worth, I completely agree as well - I got the function of the ``genericArguments`` value wrong. Sorry.

``genericArguments`` should definitely be renamed, btw: it's actually the full name of the activating interface.

There are still various issues with the generics mechanism I'd like to pursue, but I'll use other threads to stop everything getting mixed up and messy..

**Comment by jasonholloway** [comment] 2016-04-05 23:48
@gabikliot just to be clear: is casting between unrelated grain interfaces supposed to be supported on concrete grains that implement both?

**Comment by sergeybykov** [comment] 2016-04-06 00:26
@jasonholloway The limitation is that all the interfaces and the grain class that implements them must have an identical set of generic type arguments.

**Comment by gabikliot** [comment] 2016-04-06 06:03
@jasonholloway , it would be easier to answer if you wrote a short code snippet with the example.

I think what we will find out, as @sergeybykov mentioned, that not all cases that are supported by standard .NET generics are supported now by Orleans. But probably a large part of them are, the ones that we thought will be most widely used. Not all cases being supported is not a limitation of the model, but rather just a practical approach to prioritization. As you said "Orleans has to recreate a fair portion of the .NET type system - the cost of doing its own binding.".

**Closed** 2016-10-03 17:11 UTC
Labels: bug
