### ISSUE TITLE
Deadlocks on recursive calls

### ISSUE THREAD

**Issue by justmara** [dotnet/orleans#5331] opened 2019-01-24 14:19 UTC
The #3185 issue was closed a year ago, but we're still getting problems with reentrant calls (using orleans 2.2 on netcore/linux).
Assuming interfaces
```
    public interface IGrainA: IGrainWithIntegerKey
    {
        Task<int> Get();
        Task<int> Start(int i);
    }

    public interface IGrainB : IGrainWithIntegerKey
    {
        Task<int> Init();
    }
```
implementation
```
    public class GrainA : Grain, IGrainA
    {
        private int _value = 0;

        public Task<int> Get() =>
            Task.FromResult(_value);

        public async Task<int> Start(int i)
        {
            _value = i;
            return await GrainFactory.GetGrain<IGrainB>(this.GetPrimaryKeyLong()).Init();
        }
    }

    public class GrainB : Grain, IGrainB
    {
        private int _value;

        public override async Task OnActivateAsync()
        {
            _value = await GrainFactory.GetGrain<IGrainA>(this.GetPrimaryKeyLong()).Get();
        }

        public Task<int> Init() =>
            Task.FromResult(_value);
    }
```
and the call `await cluster.GrainFactory.GetGrain<IGrainA>(1).Start(5)` results in deadlock that fails with timeout.

**Comment by justmara** [comment] 2019-01-24 14:21
Surely when I decorate the GrainA's Get method with `[AlwaysInterleave]` - it fixes problem. But it forces it to be always interleaved, not only within same call chain.

**Comment by ReubenBond** [comment] 2019-01-24 20:35
Which version of Orleans are you using? 
Can you confirm that you have call chain reentrancy enabled? It ought to be enabled by default.

```C#
hostBuilder.Configure<SchedulingOptions>(options =>
{
  options.AllowCallChainReentrancy = true;
});
```

**Comment by justmara** [comment] 2019-01-24 20:55
Getting this behavior with Orleans 2.2.3. Tried explicitly setting `AllowCallChainReentrancy` with no success.
Grain-to-grain calls are resolved fine. Timeouts occurs only when callback is made from `OnActivateAsync()`.

**Comment by sergeybykov** [comment] 2019-01-24 21:04
I wonder if that's indeed because you are making the call from inside `OnActivateAsync()`. At that time the grain isn't considered fully activated yet.

**Comment by sergeybykov** [comment] 2019-01-24 21:05
Can you submit a PR with a failing test?

**Comment by justmara** [comment] 2019-01-24 21:35
@sergeybykov I'll try to. But while I'm digging trough test projects, also found that #5145 were reverted without any notice in release notes. Only 2.2.0 notes that pr as being introduced in it.

**Comment by sergeybykov** [comment] 2019-01-24 21:41
I fixed released notes for 2.2.0. They were wrongly saying that #5145 was included, while is got reverted last minute due to performance impact. What obscured things further was the fact that #5254 got squashed during merge and lost fidelity of the individual commits.

**Comment by justmara** [comment] 2019-01-25 08:17
Cannot build/check tests because of some weird error in codegenerator
![orleans-build-fail](https://user-images.githubusercontent.com/4157587/51733538-a9f17b00-2092-11e9-965f-ef051dcab0f6.png)

**Comment by justmara** [comment] 2019-01-25 09:12
@sergeybykov I created pr with failed test as you've asked.

**Comment by sergeybykov** [comment] 2019-01-25 17:00
Thank you!

**Comment by jonas-johansson** [comment] 2019-02-05 17:25
Our team has observed the same behavior, and the new OnActivateAsync test by @justmara traps the issue. (Note, however, that the test sits inside a test fixture where AllowCallChainReentrancy = false. In any case, setting it to true doesn't change the behavior.

**Comment by sergeybykov** [comment] 2019-02-06 00:18
We discussed this. The consensus is that trying to enable reentrancy from within `OnActivateAsync()` is a bad idea. Until `OnActivateAsync()` successfully completes, the grain isn't fully activated and cannot be invoked. If we allowed reentrancy, that would mean that the grain would get invoked while it is still not activated. So we consider this behavior being by design.

**Comment by justmara** [comment] 2019-02-06 11:41
Ouch, seems legit. Since `OnActivateAsync` must succeed before any grain call - recursive call cannot be handled untill `OnActivateAsync` finishes. True.

**Comment by sergeybykov** [comment] 2019-02-06 17:52
@justmara Are you okay with closing this issue and #5334?

**Comment by justmara** [comment] 2019-02-07 13:12
@sergeybykov sure, ok. We'll rework our grains a bit to avoid any _heavy_ work on initialization phase since this can add such side-effects.

**Closed** 2019-02-07 17:09 UTC
