### ISSUE TITLE
Casting from non-generic to generic interface fails with an obscure error message

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1655] opened 2016-04-06 16:07 UTC
After reverting #1604 `Generic_CastToGenericInterfaceAfterActivation` and `Generic_CastToDifferentlyConcretizedGenericInterfaceBeforeActivation` are failing with an obscure message:

> "Cannot create an instance of UnitTests.GrainInterfaces.OrleansCodeGenSomeGenericGrainMethodInvoker`1[T] because Type.ContainsGenericParameters is true."

Instead, should succeed if the target grain class allows for such a cast or give an explicit error that the cast is illegal.

**Comment by jasonholloway** [comment] 2016-04-12 23:13
Seems that both kinds of ``genericArguments`` are needed - both those of the current interface, as provided before in #1604, and those of the initially "activating" type, which should stay constant across casts, and be provided for concrete activations.

As is, ``GrainReference.InvokeMethod_Impl`` is sending the ``genericArguments`` of the original activating type across to its respective MethodInvoker, which is therefore itself being activated with the wrong gen args - it requires those of the current interface.

I'll have another go at #1604. Both sets of gen args will have to be sent on every method invocation.

**Comment by sergeybykov** [comment] 2016-04-14 04:20
Looking closer at `Generic_CastToGenericInterfaceAfterActivation` and `Generic_CastToDifferentlyConcretizedGenericInterfaceBeforeActivation`, I think `NonGenericCastableGrain` today should be deemed illegal as it is a non-generic grain class that implements a generic grain interface. Until we add support for generic methods on non-generic grain classes and on grain classes with different type arguments (https://github.com/dotnet/orleans/issues/1352), this does not work in a general case, even though technically it compiles. We need to detect this at compile time and fail. At run time, we also need to detect such illegal cases, but it's not clear to me how and where we should report them.

**Comment by jasonholloway** [comment] 2016-04-14 08:48
I'd say at the first gathering of the ``GrainInterfaceMap``- ``GrainTypeManager`` should delegate to another method or object that does the actual gathering and matching of ``GrainClassData`` and ``GrainInterfaceData`` based on an enumeration of input types, and then the manager should enforce its constraints on receiving whatever's gathered.

**Comment by jasonholloway** [comment] 2016-04-14 08:50
By separating out the gathering from the managing, type-matching would also take a nice step towards being pluggable.

**Comment by jasonholloway** [comment] 2016-04-15 07:17
And it's more complicated than that, isn't it? There's the issue of runtime codegen doing its own internal type-gathering, before any involvement of ``GrainTypeManager``.

**Comment by shayhatsor** [comment] 2016-06-05 21:40
@sergeybykov isn't this a duplicate of #1656 ?

**Comment by sergeybykov** [comment] 2016-06-15 01:30
@shayhatsor I believe they are different issues.

**Comment by ReubenBond** [comment] 2023-12-11 02:04
Fixed since at least #8705

**Closed by ReubenBond** 2023-12-11 02:04 UTC
Labels: bug
