### ISSUE TITLE
Documentation for "running as stand alone silo" seems incomplete

### ISSUE THREAD

**Issue by S-Raghav** [dotnet/orleans#2785] opened 2017-02-27 12:41 UTC
I am new to Orleans and trying out the steps as given in the documentation. I ran into 3 errors in the process

1.  The OrleansConfiguration.xml file in the SiloHost project needed to be copied manually to the bin\Debug folders of the both the SiloHost(client) and grain collection projects. I didn't seem to find this note in the documentation

2. When I ran both the client and the grain collection I got the error 

~~~ERROR starting Orleans silo name=XXXXXXXX Exception=
Exc level 0: System.MissingMethodException: Method not found: 'Void Orleans.CodeGeneration.MethodInvokerAttribute..ctor(System.String, Int32, System.Type)'.
   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at Orleans.Runtime.TypeUtils.TypeHasAttribute(Type type, Type attribType)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Orleans.Runtime.TypeUtils.GetTypes(Predicate`1 whereFunc, Logger logger)
   at Orleans.Runtime.SiloAssemblyLoader.GetGrainMethodInvokerTypes(Boolean strict)
   at Orleans.Runtime.GrainTypeManager.InitializeInvokerMap(SiloAssemblyLoader loader, Boolean strict)
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
~~~

I noticed that the nuget packages for Orleans.CodeGenerator.Build in the GrainCollection and Orleans.CodeGenerator.Build and Orleans.Core in the grain interface needed to be updated

After updating I got compilation errors which went away after deleting the orleans.codegen.cs file in the grain interface file

3. Though I have specified the ProxyingGateway port as 30000, while running the client starts running at port 40000

I feel it would be helpful if these pitfalls could be captured in the documentation and their solutions specified. Thanks

**Comment by S-Raghav** [comment] 2017-03-03 05:15
Is this somehow related to #2617 ? If yes, maybe I could close this issue/add it as a comment there..

**Comment by sergeybykov** [comment] 2017-03-16 17:51
@S-Raghav Thanks for raising this issue. Yes, #2617 is the one to add more suggestions to.

**Comment by sergeybykov** [comment] 2017-04-04 18:03
Closing this one as a duplicate of #2617.

**Closed by sergeybykov** 2017-04-04 18:03 UTC
Labels: documentation
