### ISSUE TITLE
Exceptions serialization error 2.0 beta1

### ISSUE THREAD

**Issue by stephenlautier** [dotnet/orleans#3640] opened 2017-11-06 11:27 UTC
After the update to .NET Core 2 with Orleans, 2.0 beta-1, we are getting some issues with the exceptions, is there a way to mark them as serializable?

This is the error we are getting:

```cs
Orleans.Runtime.OrleansException: No copier found for the object of type System.ArgumentNullException. 
Perhaps you need to mark it [Serializable] or define a custom serializer for it?
```

For our own exceptions, we could modify the code to get them working, however for the ones we don't have control over I'm not sure what to do. Any suggestions?

**Comment by stephenlautier** [comment] 2017-11-07 13:56
I'm just going to leave a note in here, as this is somewhat related I believe (if you want I can open another issue). However for types that you don't have control over, e.g. `JObject`, is there a way to manually register them to be serializable? For errors such as above.

**Comment by stephenlautier** [comment] 2017-11-14 11:25
@ReubenBond @sergeybykov the exception issue seems to have been fixed, is there a time frame when it will be released? 
Since currently all our exceptions are throwing the serialization exception and we are losing the actual exceptions which is very hard

**Comment by SebastianStehle** [comment] 2017-11-15 23:52
Have the same problem with another error:

	Type 'System.NotSupportedException' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.
	 
	 at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
		at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
		at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
		at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
		at Orleans.Serialization.BinaryFormatterSerializer.Serialize(Object item, ISerializationContext context, Type expectedType)
		at Orleans.Serialization.SerializationManager.FallbackSerializer(Object raw, ISerializationContext context, Type t)
		at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, ISerializationContext context, Type expected)
		at Orleans.Serialization.SerializationManager.Serialize(Object raw, IBinaryTokenStreamWriter stream)
		at Orleans.Runtime.Message.Serialize(SerializationManager serializationManager, Int32& headerLengthOut, Int32& bodyLengthOut)
		at Orleans.Runtime.Messaging.Gateway.GatewaySender.Send(Message msg, Socket sock)

**Comment by ReubenBond** [comment] 2017-11-19 04:05
For the time being, try using the ILBasedSerializer as a workaround - I'm not sure if it will fix it, but it's worth a shot:
```C#
var clientConfig = new ClientConfiguration
{
    FallbackSerializationProvider = typeof(ILBasedSerializer).GetTypeInfo(),
   // other opts
};

var clusterConfig = new ClusterConfiguration
{
    Globals =
    {
        FallbackSerializationProvider = typeof(ILBasedSerializer).GetTypeInfo()
    }
};
```

**Comment by JasonBock** [comment] 2017-11-19 19:49
FYI this temp fix works for me. But is this something that **should** just work? Meaning, do I need to keep this code in place, or will a future 2.0 release address this?

**Comment by ReubenBond** [comment] 2017-11-19 22:29
@JasonBock investigating & potentially fixing this is my priority today. This has to work by default, so either we make the default `BinaryFormatter` serializer which is used for exceptions work or we change the default to `ILBasedSerializer`. Moving to the latter is probably best. It's also faster.

**Comment by ReubenBond** [comment] 2017-11-20 02:24
After investigation, I can confirm that we're running into [CoreFx issue #24424](https://github.com/dotnet/corefx/issues/24424). The [aforementioned fix](https://github.com/dotnet/orleans/issues/3640#issuecomment-345490447) is the recommended workaround. I'm working on a fix which does not involve changing the default FallbackSerializer.

**Comment by stephenlautier** [comment] 2017-11-21 20:59
@ReubenBond thanks for the workaround solution, its working good for the time being!

**Closed** 2017-11-28 07:00 UTC
