### ISSUE TITLE
2.0 rc1 using Microsoft.Orleans.OrleansSQLUtils persistent problem?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4105] opened 2018-03-01 11:06 UTC
Orleans how to deal with when there is no data in a single database, such as needing to add users? No user code state is empty.
![image](https://user-images.githubusercontent.com/28291464/36841521-7a39d6c2-1d83-11e8-9e69-7361cb599a01.png)

**Comment by quaider** [comment] 2018-03-02 10:13
come with the similar exception...
the database connect success, but `Orleans.Storage.AdoNetGrainStorage` throw errors.

**Comment by quaider** [comment] 2018-03-02 13:42
persist with sqlserver(installed System.Data.Client, and already execute the init sql）
```csharp
var builder = new SiloHostBuilder()
                .Configure(options => options.ClusterId = "helloworldcluster")
                .UseAdoNetClustering(options =>
                {
                    options.ConnectionString = connStr;
                    options.AdoInvariant = "System.Data.SqlClient";
                })
                .UseDevelopmentClustering(options => options.PrimarySiloEndpoint = new IPEndPoint(siloAddress, siloPort))
                .AddAdoNetGrainStorageAsDefault(options =>
                {
                    //options.InitStage = -1;
                    options.Invariant = "System.Data.SqlClient";
                    options.ConnectionString = connStr;
                })
                .ConfigureEndpoints(siloAddress, siloPort, gatewayPort)
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences())
                .ConfigureLogging(logging => logging.AddConsole());
```
fail: Orleans.Storage.AdoNetGrainStorage[200416]
      Error reading grain state: ServiceId=00000000-0000-0000-0000-000000000000 ProviderName=Default GrainType=Orleans.Runtime.Versions.VersionStoreGrain GrainId=0#helloworldcluster ETag= Exception=Object reference not set to an instance of an object..
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Storage.AdoNetGrainStorage.<ReadStateAsync>d__32.MoveNext()
fail: Orleans.Storage.AdoNetGrainStorage[102202]
      Error from storage provider AdoNetGrainStorage.Orleans.Runtime.Versions.VersionStoreGrain during ReadState for grain Type=Orleans.Runtime.Versions.VersionStoreGrain Pk=*grn/13BAB4D8/000000000000000000000000000000000600000013bab4d8+helloworldcluster-0xA22DA1FC Id=GrainReference:*grn/13BAB4D8/00000000+helloworldcluster Error=

      Exc level 0: System.NullReferenceException: Object reference not set to an instance of an object.
         at Orleans.Storage.AdoNetGrainStorage.<ReadStateAsync>d__32.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Orleans.Core.StateStorageBridge`1.<ReadStateAsync>d__11.MoveNext()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Storage.AdoNetGrainStorage.<ReadStateAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.StateStorageBridge`1.<ReadStateAsync>d__11.MoveNext()
fail: Orleans.Runtime.GrainLifecycle[100450]
      Lifecycle start canceled due to errors at stage 1000
Orleans.Runtime.OrleansException: Error from storage provider AdoNetGrainStorage.Orleans.Runtime.Versions.VersionStoreGrain during ReadState for grain Type=Orleans.Runtime.Versions.VersionStoreGrain Pk=*grn/13BAB4D8/000000000000000000000000000000000600000013bab4d8+helloworldcluster-0xA22DA1FC Id=GrainReference:*grn/13BAB4D8/00000000+helloworldcluster Error=

Exc level 0: System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by quaider** [comment] 2018-03-02 13:45
when set options.InitStage = -1; then the error disappear, but its data not stored in the OrleansMembershipTable

**Comment by AdamWyzgol** [comment] 2018-03-02 14:14
I also have this problem, changing to memory storage solve the problem, so this should be inside ado net implementation

**Comment by AdamWyzgol** [comment] 2018-03-02 14:30
I think it is duplicated #4099 adding `options.InitStage = ServiceLifecycleStage.RuntimeServices;` fix this issue

**Comment by sergeybykov** [comment] 2018-03-03 00:36
Closing this as a duplicate of #4099. Please reopen if the workaround of `options.InitStage = ServiceLifecycleStage.RuntimeService;` doesn't work for you.

**Closed by sergeybykov** 2018-03-03 00:36 UTC

**Comment by aqa510415008** [comment] 2018-03-03 15:07
@sergeybykov  AdoNetReminderTableOptions None InitStage this configuration

**Comment by aqa510415008** [comment] 2018-03-03 15:31
`var builder = new SiloHostBuilder()
                .UseDevelopmentClustering(options => options.PrimarySiloEndpoint = new IPEndPoint(siloAddress, siloPort))
                .UseAdoNetReminderService(opt =>
                {
                    opt.ConnectionString = "Database=orleans;Data Source=*.*.*.*;User Id=root;Password=root;pooling=false";
                    opt.Invariant = "MySql.Data.MySqlClient";
                })
                .AddSimpleMessageStreamProvider("SimpleMessageStream")
                .Configure(options => options.ClusterId = "helloworldcluster")
                .ConfigureEndpoints(siloAddress, siloPort, gatewayPort)
                .ConfigureSiloName(Silo.PrimarySiloName)
                .ConfigureServices(Startup.ConfigureServices)
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(UserService).Assembly).WithReferences())
                .ConfigureLogging(logging => logging.AddConsole());`
