### ISSUE TITLE
Code generation fails when there are multiple netcore SDKs on the machine

### ISSUE THREAD

**Issue by Avd6977** [dotnet/orleans#4970] opened 2018-09-12 12:26 UTC
Error	MSB3073	The command ""dotnet" \.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-beta1\build\..\tasks\netcoreapp2.0\Orleans.CodeGeneration.Build.dll" "@obj\Debug\netstandard2.0\codegen\Squidex.Infrastructure.orleans.g.args.txt"" exited with code 3.	Squidex.Infrastructure	\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-beta1\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets	82	

Removing previous SDKs fixes the issue.

**Comment by SebastianStehle** [comment] 2018-09-12 13:49
@Avd6977 Thank you, I already reported it there: https://github.com/dotnet/orleans/issues/4956

**Comment by sergeybykov** [comment] 2018-09-12 15:55
Closing as a duplicate of #4956. Thank you, @Avd6977!

**Closed by sergeybykov** 2018-09-12 15:55 UTC

**Comment by MatthewShelby** [comment] 2020-06-12 16:41
I solved this by repairing the SKD file from the windows Control Panel.
