### ISSUE TITLE
Type string "Orleans.Runtime.RequestInvocationHistory" cannot be resolved.

### ISSUE THREAD

**Issue by luohuazhiyu** [dotnet/orleans#4819] opened 2018-08-05 16:39 UTC
When I do the following setting, Client will throw an exception..
```
.Configure<SchedulingOptions>(c =>
{
    c.PerformDeadlockDetection = true;
})

at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 425
         at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadFullTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager, Type expected) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 464
         at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 374
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:line 1288
         at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Messaging\Message.cs:line 1325
         at Orleans.Serialization.SerializationManager.DeserializeMessageHeaders(IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:line 1563
         at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg) in D:\Git\orleans\src\Orleans.Core\Messaging\IncomingMessageBuffer.cs:line 175
         at Orleans.Messaging.GatewayClientReceiver.Run() in D:\Git\orleans\src\Orleans.Core\Messaging\GatewayClientReceiver.cs:line 43. Restarting gateway receiver for gwy.tcp://127.0.0.1:30000/0.
System.TypeAccessException: Named type "Orleans.Runtime.RequestInvocationHistory" is invalid: Type string "Orleans.Runtime.RequestInvocationHistory" cannot be resolved.
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 425
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadFullTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager, Type expected) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 464
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 374
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:line 1288
   at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Messaging\Message.cs:line 1325
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaders(IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:line 1563
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg) in D:\Git\orleans\src\Orleans.Core\Messaging\IncomingMessageBuffer.cs:line 175
   at Orleans.Messaging.GatewayClientReceiver.Run() in D:\Git\orleans\src\Orleans.Core\Messaging\GatewayClientReceiver.cs:line 43
fail: Messaging.GatewayClientReceiver/gwy.tcp://127.0.0.1:30000/0[100026]
      Asynch agent Messaging.GatewayClientReceiver/gwy.tcp://127.0.0.1:30000/0 encountered unexpected exception The Stage will be restarted.
System.TypeAccessException: Named type "Orleans.Runtime.RequestInvocationHistory" is invalid: Type string "Orleans.Runtime.RequestInvocationHistory" cannot be resolved.
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 425
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadFullTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager, Type expected) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 464
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader(IBinaryTokenStreamReader this, SerializationManager serializationManager) in D:\Git\orleans\src\Orleans.Core\Serialization\BinaryTokenStreamReader.cs:line 374
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:line 1288
   at Orleans.Runtime.Message.HeadersContainer.Deserializer(Type expected, IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Messaging\Message.cs:line 1325
   at Orleans.Serialization.SerializationManager.DeserializeMessageHeaders(IDeserializationContext context) in D:\Git\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:line 1563
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg) in D:\Git\orleans\src\Orleans.Core\Messaging\IncomingMessageBuffer.cs:line 175
   at Orleans.Messaging.GatewayClientReceiver.Run() in D:\Git\orleans\src\Orleans.Core\Messaging\GatewayClientReceiver.cs:line 43
   at Orleans.Threading.FiltersApplicant`1.Apply(T action) in D:\Git\orleans\src\Orleans.Core\Threading\ActionFilter.cs:line 86

**Comment by jason-bragg** [comment] 2018-08-07 22:03
Duplicate of - Enabling DeadlockDetection will cause an Exception #4517 and 
PerformDeadlockDetection not working in 2.0 #4706 

fixed in - Moved request invocation history to core. #4761

**Closed by jason-bragg** 2018-08-07 22:03 UTC
