### ISSUE TITLE
Management Grain took to long

### ISSUE THREAD

**Issue by mohamedhammad** [dotnet/orleans#4696] opened 2018-06-17 20:37 UTC
i had this warning on a silo that was running using sql server liveness,
WARNING	101215	Scheduler.WorkItemGroup	10.1.0.6:22222]	Task [Id=-1500906100, Status=RanToCompletion] in WorkGroup [Activation: S10.1.0.6:22222:265810487*grn/7483D9D2/00000000@b4f381b7 #GrainType=Orleans.Runtime.Management.ManagementGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:08.6929183 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/3, ManagedThreadId=10, Executing Task Id=-1500906100 Status=RanToCompletion for 00:00:08.6914987 on WorkItem=WorkItemGroup:Name=[Activation: S10.1.0.6:22222:265810487*grn/7483D9D2/00000000@b4f381b7 #GrainType=Orleans.Runtime.Management.ManagementGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:08.6914987. .>	

it is stating that the management grain took 8 seconds, i am using orleans 1.4.2
after that i got a callbackdata took 30 seconds error.
what would cause such behaviour ?

**Comment by veikkoeeva** [comment] 2018-06-18 16:36
Looks like a duplicate of https://github.com/dotnet/orleans/issues/4505.

**Comment by veikkoeeva** [comment] 2018-06-18 16:42
@mohamedhammad I might've been too quick in linking, do you use Orleans Dashboard?

ADO.NET shouldn't affect management grain otherwise than if it blocked calls.

**Comment by mohamedhammad** [comment] 2018-06-18 17:02
yes i use orleans dashboard

**Comment by ReubenBond** [comment] 2018-06-21 21:36
Hi @mohamedhammad, do you still experience this issue after removing the dashboard? The version of the dashboard which is compatible with 1.4.2 has blocking code which can cause issues

**Comment by mohamedhammad** [comment] 2018-06-22 12:41
yes still,but less frequent, now i am in the process of upgrading to 2.0. 3 dot net framework,because in another post i got information that there is some improvement, and even better a new scheduler that will be part of 2.1,so i am heading to the new 2.X.
thank you. will update here.

**Comment by sergeybykov** [comment] 2018-06-22 16:41
@mohamedhammad Do you mind if we close this one in favor of #4505 to consolidate?

**Comment by mohamedhammad** [comment] 2018-06-22 18:36
yes sir,we can,that would make it much easier to follow.thank you.

**Comment by sergeybykov** [comment] 2018-06-22 21:09
Thank you. Closing in favor of #4505.

**Closed by sergeybykov** 2018-06-22 21:09 UTC
