### ISSUE TITLE
 Unsupported type 'Orleans.Streams.PubSubGrainState' encountered.

### ISSUE THREAD

**Issue by ar3cka** [dotnet/orleans#3030] opened 2017-05-22 14:06 UTC
After orleans upgrade  from 1.3.1 to 1.4.1 we get the following error on silo start:

> 2017-05-22-13.35.13.812ZZ
ERROR starting Orleans silo name=Ucp.Sde.Cloud.WorkerRole_IN_1 Exception=
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   at Orleans.Runtime.Silo.DoStart()
   at Orleans.Runtime.Silo.Start()
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
Exc level 1: Orleans.Providers.ProviderInitializationException: Exception initializing provider Name=TrafficStatsticsBootstrapper Type=[TrafficStatsticsBootstrapper, KasperskyLab.Ucp.Sde.TrafficStatistic.TrafficStatsticsBootstrapper]
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.BootstrapProviderManager.PluginManager`1.<LoadAndInitPluginProviders>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.BootstrapProviderManager.<LoadAppBootstrapProviders>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
Exc level 2: Orleans.Runtime.OrleansException: Forwarding failed: tried to forward message Request S100.73.118.72:11111:233156068*grn/B23D7E1F/00000000@893f1db4->S100.73.118.72:11111:233156068*grn/716E8E94/477e64bb+AzureQueueProvider_VpnAccessEvents@3b49d1ab #32[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:GetAllSubscriptions() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now. System.AggregateException: Unable to convert from storage format GrainStateEntity.Data=System.Byte[] ---> System.Runtime.Serialization.SerializationException: Unsupported type 'Orleans.Streams.PubSubGrainState' encountered. Perhaps you need to mark it [Serializable] or define a custom serializer for it?
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[T](IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeFromByteArray[T](Byte[] data)
   at Orleans.Storage.AzureTableStorage.ConvertFromStorageFormat(DynamicTableEntity entity)
   --- End of inner exception stack trace ---
   at Orleans.Storage.AzureTableStorage.ConvertFromStorageFormat(DynamicTableEntity entity)
   at Orleans.Storage.AzureTableStorage.<ReadStateAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KasperskyLab.Ucp.Sde.Backend.Infrastructure.Orleans.Storage.CloudTableStorageProvider.<ReadStateAsync>d__11.MoveNext() in F:\vNext_KpcInfraSdePool\Agent10\_work\1\s\src\Ucp.Sde.Backend.Infrastructure\Orleans\Storage\CloudTableStorageProvider.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<SetupActivationState>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__59.MoveNext()
---> (Inner Exception #0) System.Runtime.Serialization.SerializationException: Unsupported type 'Orleans.Streams.PubSubGrainState' encountered. Perhaps you need to mark it [Serializable] or define a custom serializer for it?
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[T](IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeFromByteArray[T](Byte[] data)
   at Orleans.Storage.AzureTableStorage.ConvertFromStorageFormat(DynamicTableEntity entity)

**Comment by DixonDs** [comment] 2017-05-22 14:40
@ar3cka Do you use Azure Table storage provider for PubSub with binary format?

**Comment by ar3cka** [comment] 2017-05-22 15:53
@DixonDs Yes, we do. But we have written a wrapper storage provider (like was suggested in #1872) and use it for reading data with backward compatibility problems.

**Comment by sergeybykov** [comment] 2017-05-22 16:23
@ar3cka Do you have that storage provider added as "PubSubStore"?

**Comment by ar3cka** [comment] 2017-05-22 16:45
@sergeybykov Yes, we use it as "Default" and "PubSubStore" storage provider.

**Comment by jason-bragg** [comment] 2017-05-22 17:50
What stream provider are you using?  We may be able to reproduce this on our side once we know what stream provider you're using.

Since this is happening during deserialization, it seems most likely that something has changed between what was stored in pubsub in 1.3.1 and 1.4.1.  I assume the 1.4.1 version can read the state it writes?

From the code, it does not look like the pubsub state has changed between the versions, but something clearly has, so the question in my mind is "what's different?".
To help figure this out, I suggest:
1) Run the current 1.3.1 code in a clean environment, with the storage configured to store state in json format.
2) Run the new 1.4.1 version, also in a clean environment with the storage similarly configured.  
3) Compare pubsub json states between the two versions and look for data format differences that could account for the serialization errors.

Minor curiosity: Why move to 1.4.1 rather than 1.4.2?

**Comment by DixonDs** [comment] 2017-05-22 18:14
@jason-bragg 
>Minor curiosity: Why move to 1.4.1 rather than 1.4.2?

There is no 1.4.2 and 1.4.1 is the latest stable version.

**Comment by jason-bragg** [comment] 2017-05-22 18:22
@DixonDs 

>no 1.4.2

Oops.  We have a branch for 1.4.2, so I assumed we did a release, my mistake.  NM :)

**Comment by xiazen** [comment] 2017-05-22 19:40
It is strange that it throws exception when deserialize on PubSubGrainState class, Since the class structure itself doesn't change between 1.3.1 and 1.4.1, and its member class's serialized properties between two versions doesn't change either, except for GrainReference. But if the serialization problem lies on GrainReference, then you should be seeing more serialization exception regarding grains in general , rather than just PubSubGrainState class. 

I suspect it can be related to serialization itself. what serializer are you using when moving from 1.3 to 1.4.1? Are you using a different one?

**Comment by ar3cka** [comment] 2017-05-23 13:05
@jason-bragg @xiazen  We are using AzureQueueStreamProvider with the builtin binary serializer. I've checked migration on clean environment and found out, that issue happens only for binary serialization. There are no issues if we use json serialization.

**Comment by jason-bragg** [comment] 2017-05-23 20:25
@ReubenBond has reproduced the issue and has a preliminary fix, though he's still considering other solutions.
This will most likely necessitate a 1.4.2 release.
We've not yet identified a workaround you can apply in 1.4.1. :/

**Comment by sergeybykov** [comment] 2017-05-25 14:32
Should be fixed via #3035.

**Closed** 2017-05-25 15:23 UTC
