### ISSUE TITLE
ServiceId_SiloRestart test fails intermittently

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#4997] opened 2018-09-17 22:04 UTC
UnitTests.Streaming.StreamProvidersTests_ProviderConfigNotLoaded.ServiceId_SiloRestart fails intermittently

MESSAGE:
Orleans.Runtime.OrleansLifecycleCanceledException : Lifecycle start canceled due to errors at stage 19999\r\n---- System.TimeoutException : MembershipOracle activating failed due to timeout 00:05:00
+++++++++++++++++++
STACK TRACE:
at Orleans.LifecycleSubject.<OnStart>d__5.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 63 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Runtime\Scheduler\ClosureWorkItem.cs:line 63 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.Runtime.Silo.<StartAsync>d__65.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Runtime\Silo\Silo.cs:line 274 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.TestingHost.InProcessSiloHandle.Create(String siloName, IList`1 configurationSources) in D:\j\workspace\functional_pr---83d31c72\src\Orleans.TestingHost\InProcessSiloHandle.cs:line 36 at Orleans.TestingHost.TestCluster.StartOrleansSilo(Int32 instanceNumber, TestClusterOptions clusterOptions, IReadOnlyList`1 configurationOverrides, Boolean startSiloOnNewPort) in D:\j\workspace\functional_pr---83d31c72\src\Orleans.TestingHost\TestCluster.cs:line 521 at Orleans.TestingHost.TestCluster.RestartSilo(SiloHandle instance) in D:\j\workspace\functional_pr---83d31c72\src\Orleans.TestingHost\TestCluster.cs:line 419 at UnitTests.Streaming.StreamProvidersTests_ProviderConfigNotLoaded.<ServiceId_SiloRestart>d__9.MoveNext() in D:\j\workspace\functional_pr---83d31c72\test\TesterInternal\StreamProvidersTests.cs:line 92 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Core\Async\TaskExtensions.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.Runtime.Silo.<<OnBecomeActiveStart>g__BecomeActive|73_1>d.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Runtime\Silo\Silo.cs:line 527 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.Runtime.Silo.<StartAsyncTaskWithPerfAnalysis>d__70.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Runtime\Silo\Silo.cs:line 395 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.Runtime.Silo.<OnBecomeActiveStart>d__73.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Runtime\Silo\Silo.cs:line 529 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__9.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Runtime\Lifecycle\SiloLifecycleSubject.cs:line 82 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.LifecycleSubject.<WrapExecution>d__10.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 115 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Orleans.LifecycleSubject.<OnStart>d__5.MoveNext() in D:\j\workspace\functional_pr---83d31c72\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 55

**Comment by ReubenBond** [comment] 2018-12-03 22:01
Duplicate of https://github.com/dotnet/orleans/issues/4721

**Closed by ReubenBond** 2018-12-03 22:01 UTC
Labels: test-issue
