### ISSUE TITLE
From Codeplex: The code generation breaks on inner classes or on some F# effect

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#291] opened 2015-04-01 19:09 UTC
Orleans' codegenerator breaks in the following situation. Assume there's a DTO class defined in in a F# library like so

     namespace Project.Some
  
     [<AutoOpen>]
     module Temp =
       open System
       open System.Runtime.Serialization

    [<DataContract>]
    type Note() = 
        let mutable id: int = 0
                
        [<DataMember>]    
        member this.Id with get() = id and set(v) = id <- v

And then it being used in an interface definition like so

    public interface ISomeGrain: IGrain
    {
         Task Notify(Project.Some.Temp.Note note);
    }

And it results in orleans.codegen.cs to a following construct

    [Orleans.RegisterSerializerAttribute()]
    internal class Project_Some_Temp+NoteSerialization

The compiler rejects the + sign. If Note is lifted from the module straight under the namespace, the codegeneration functions as expected. I haven't investigated the root cause of this, but I believe modules in F# are compiled down to classes in IL, and judging from that this manifests in C# too with inner classes (I haven't tried, though). 

 As far as F#-C# interop in concerned, this is probably one of those nice to know little annoyances. So, not much of a concern as my feeling is that the best practice would be to put the type under namespace. Scott Wlaschin has a good write-up regarding this at his site F# for Fun and Profit on  [Organizing functions](http://fsharpforfunandprofit.com/posts/organizing-functions/) (from "Mixing types and functions in modules" onwards). More in [Organizing modules in a project](http://fsharpforfunandprofit.com/posts/recipe-part3/).

**Comment by alan-geller** [comment] 2015-04-02 21:52
The problem is that F# modules turn into .NET classes, so the Note class is an inner class whose Name property is Temp+Name. This could be fixed in the serializer generation code pretty easily, since the class name of the class that defines the serializer isn't semantically meaningful.

**Comment by alan-geller** [comment] 2015-04-02 21:54
Sorry, user error on my part (unintended close).

**Comment by sergeybykov** [comment] 2015-11-16 18:04
Is this still an issue with the new Roslyn-based codegen?

**Comment by ReubenBond** [comment] 2015-11-25 04:57
This is resolved by #528. We have tests which ensure that nested classes are serialized fine.
See: https://github.com/dotnet/orleans/blob/de2902b67501cb43a65387751072312f9f8cfde7/src/Tester/CodeGenTests/IRuntimeCodeGenGrain.cs

**Closed** 2015-11-25 07:30 UTC
Labels: bug
