### ISSUE TITLE
CreateOrleansTables sql script?

### ISSUE THREAD

**Issue by dazinator** [dotnet/orleans#3862] opened 2018-01-13 16:38 UTC
I am attempting to use sql server for storage.

The link to the sql script to create orleans tabes on this page 404's: http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Configuring-SQL-Tables 

Any ideas where I can find it?

**Comment by larsfjerm** [comment] 2018-01-14 20:38
Here is what you're looking for - run script to your DB:
https://pastebin.com/XK5v063w

**Comment by veikkoeeva** [comment] 2018-01-15 16:02
@dazinator 

1. It appears the link in the documentation has gone stale (should be fixed, naturally).
2. The scripts are co-located with the Nuget binaries, seeing you're in .NET Standard and if you run `nuget locals all -list`, I'd imagine it's something like `C:\Users\<username>\.nuget\packages\microsoft.orleans.*.adonet\2.0.0-beta3\lib\netstandard2.0`. There was recently a refactoring to split the script into multiple parts. You need to run separately the ones you need (e.g. in your case don't forget `C:\Users\Veikko\.nuget\packages\microsoft.orleans.clustering.adonet\2.0.0-beta3\lib\netstandard2.0\SQLServer`). The problem is further exarcarbarated in that the Nuget packages are places "far away from the project", i.e. in the Nuget cache. This should be remedied somehow, like bringing the scripts to project directory or something.
3. It should be explicitly mentioned in the documentation (and in the exception message) that one needs to reference also an appropriate ADO.NET library. The reason for this is that there are tens of providers for ADO.NET and currently at least there isn't a separate Nuget package that would add a helper function (e.g. `.ConfigureSqlServer`) which would then also bring in SQL Server packages.

A further note, if you plan to run database in production, do note you need to think a bit of adding a schema and appropriate filegroups. I.e. modify the script and queries a bit. I'm working [on a sample](https://github.com/veikkoeeva/orleans/tree/adonetstample/Samples/AdoNetSample/src/AdotNetSample.Database) which would use [Dacpac](https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/data-tier-applications).

Does this help you?

**Comment by dazinator** [comment] 2018-01-15 17:38
Thank you, I will take a look in the packages - i thought I had done that already - perhaps missed them.

I understand that there are many ado.net providers, but the dialect of sql used by a provider is usually specific for that provider. For example a postgress sql script is obviously different from an ms sql script. Due to that, I think I was expecting for the scripts to live with a concrete provider package. I was a bit off in my assumption :-)

Is DacPac the path you have in mind for releasing updates for the schema? If so may I suggest avoiding them and using a migrations based approach instead? To clarify what I mean by thay you could look at DbUp on github! Just my opinion having used both approaches I always find migration scripts much cleaner and easier to reliably rollout incremental changes :-)

**Comment by veikkoeeva** [comment] 2018-01-15 17:50
> I understand that there are many ado.net providers, but the dialect of sql used by a provider is usually specific for that provider. For example a postgress sql script is obviously different from an ms sql script. Due to that, I think I was expecting for the scripts to live with a concrete provider package. I was a bit off in my assumption :-)

As you see, I opened a ticket to improve the situation. The Nuget packages are split by functionality and each contain a directory for each of currently supported database flavor. This isn't a very good situation and maybe ought to be remedied before the the 2.0 version is released.

I've thought about using that in the sample, but that's mostly because it's somewhat readily available and I know a bit how to use it. Though maybe I should learn [DbUp](https://medium.com/@menezes.carlos/automated-database-deployments-with-dbup-5df3a247200). As you may know, Dacpac includes plenty of functionality other than schema tracking too. It's unfortunately limited to SQL Server. The real goal is to produce a more real-world sample project. I have already an API with Swagger and integration tests with backup-restore (takes less than a second whole a whole range of tests, so not a problem) to show this a bit more. It's also important to consider schemas and filegroups, for things like GDPR (and general security) and disaster recovery. :)

**Comment by sergeybykov** [comment] 2018-01-31 01:35
Links to the SQL scripts got fixed via #3898. Looks like we can close this one.

**Closed by sergeybykov** 2018-01-31 01:35 UTC
