### ISSUE TITLE
Orleans' Roslyn CodeGen Live Code Analyzer

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#868] opened 2015-10-03 21:03 UTC
Since we are really close to the end on finish #528, after talk with @sergeybykov we agreed that after the new Roslyn-based codegen will work in two modes:
1. Runtime mode
2. Compile time mode

In Compile time mode, it will looks pretty much the same as current codegen and every time you build the project the codegen will run and generate whatever is necessary. This mode can be used if you create a project from the Orleans project templates.

In other hand, Runtime mode will make the codegen emit the new types while Orleans Runtime is starting up and is the default mode if you are just adding Orleans references over a regular Class Library project whoever, it introduces one problem... 

While in compile mode you have a static code analysis working and presenting errors on VS error panel and this help the developer create code that will avoid several runtime errors. In other words, a "safier" code.

If you are using the Runtime Mode, which (IMHO) is the greatest feature on #528, we loose the static code analysis at all, since (ofc) the codegen will only generate code at runtime, so you will only see the problem when you are running the silo.

To handle the Runtime lack of "development time static code analysis", I suggested @sergeybykov  to use the newest Roslyn Analyzer assembly/project as you can see some samples here: https://msdn.microsoft.com/en-us/magazine/dn879356.aspx

It is just a class library/project/dll, that will be referenced on the required projects. We can add it as a new package (OrleansRuntime.Analyzer ?) and make it a dependency of the regular Orleans Nugets that uses codegen.

The only problem is that I'm not sure if this work with Visual Studios versions < 2015. Need check on that.

Anyone has a better idea? We need to keep the developers safe, and I think this is the way to go with Roslyn.

Thanks

**Comment by sergeybykov** [comment] 2018-10-09 17:07
Looks like #2841 is essentially a duplicate of this one. But it got more traction. Closing this one in favor of #2841.

**Closed by sergeybykov** 2018-10-09 17:07 UTC
Labels: P3
