### ISSUE TITLE
Using AzureTableStorage for grain state in 2.0.0-rc1 results in exception

### ISSUE THREAD

**Issue by lwansbrough** [dotnet/orleans#4099] opened 2018-02-28 23:03 UTC
I'm not sure if I've misconfigured the provider after upgrading or what, but I'm getting the following exception:

```
2018-02-28 13:47:42.0305|ERROR|Orleans.Storage.AzureTableGrainStorage|Error from storage provider AzureTableGrainStorage.Atlas.Grains.OracleGrain during ReadState for grain Type=Atlas.Grains.OracleGrain Pk=*grn/A7373A0B/0000000000000000000000000000000003ffffffa7373a0b-0xFD37BD8E Id=GrainReference:*grn/A7373A0B/00000000 Error=
 
Exc level 0: System.ArgumentException: GrainState-Table property not initialized
   at Orleans.Storage.AzureTableGrainStorage.<ReadStateAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.StateStorageBridge`1.<ReadStateAsync>d__11.MoveNext()
2018-02-28 13:47:42.0329|ERROR|Orleans.Runtime.GrainLifecycle|Lifecycle start canceled due to errors at stage 1000
2018-02-28 13:47:42.0329|ERROR|Orleans.Runtime.Catalog|Error calling grain's OnActivateAsync() method - Grain type = Atlas.Grains.OracleGrain Activation = [Activation: S127.0.0.1:11111:257550460*grn/A7373A0B/00000000@4bea0e8a #GrainType=Atlas.Grains.OracleGrain Placement=RandomPlacement State=Activating]
```

I'm using the following configuration:

```
services.AddAzureTableGrainStorage("AzureTableStore", options =>
{
    options.UseJson = true;
    options.ConnectionString = "my connection string here";
    options.TableName = "my table name, however i only added this in an attempt to fix the issue";
});
```

**Comment by lwansbrough** [comment] 2018-02-28 23:28
Seems to be resolved when I set `options.InitStage = ServiceLifecycleStage.RuntimeServices;` -- not sure if that's the correct setting though. It defaults to `ServiceLifecycleStage.ApplicationServices` which does seem like an odd choice for a storage service.

**Comment by benjaminpetit** [comment] 2018-02-28 23:58
I think the issue the silo is marked "Active" and open the gateway before everything is ready (like storage).

So the issue is not related to storage, it is must revealing that our startup/stop sequences are buggy :)

Ideally, silo should not be marked as "Active" in the membership table and accept client connection before everything is ready

**Comment by benjaminpetit** [comment] 2018-02-28 23:59
To confirm that, could you wait a bit before doing a call to this grain that is using table storage?

**Comment by sergeybykov** [comment] 2018-03-07 22:56
Should be resolved via #4135.

**Comment by sergeybykov** [comment] 2018-09-14 02:02
@mhertis Can you share more details?

**Comment by sergeybykov** [comment] 2019-03-04 20:13
Closing as this appears to be an external issue.

**Closed by sergeybykov** 2019-03-04 20:13 UTC
