### ISSUE TITLE
BondSerializer exception

### ISSUE THREAD

**Issue by lilinghui** [dotnet/orleans#1784] opened 2016-05-24 04:13 UTC
1.2.0 
when i get  OrleansBondUtils.dll from nuget , use bind  in BondSerializer.cs,
        public bool IsSupportedType(Type itemType)
        {
            if (ClonerInfoDictionary.ContainsKey(itemType.TypeHandle)) // this line throw null exception 
            {
                return true;
            }
...
 }
when i build OrleansBondUtils from source , then it worked fine.

**Comment by sergeybykov** [comment] 2016-05-24 17:16
`OrleansBondUtils.dll` is deployed and loaded into the silo process in both cases?

/cc @Carlm-MS

**Comment by Carlm-MS** [comment] 2016-05-24 18:10
The ClonerInfoDictionary should never be null so the only way a NullReferenceException can happen is if null was passed into the IsSupportedType method. It doesn't make sense that it works when built from source and not from the NuGet package.  I'll download the package and decompile and compare to the source.

from the source:
```csharp
        private static readonly ConcurrentDictionary<RuntimeTypeHandle, ClonerInfo> ClonerInfoDictionary = new ConcurrentDictionary<RuntimeTypeHandle, ClonerInfo>();
```

**Comment by Carlm-MS** [comment] 2016-05-24 18:43
I downloaded the package and wasn't able to see the problem. @lilinghui - can you provide a repro?

**Comment by lilinghui** [comment] 2016-05-25 03:00
i paste some stack info, i'm sorry , some chinese in it. maybe load Microsoft.VisualStudio.Debugger.Runtime.dll error.

[2016-05-25 02:54:15.511 GMT     1	VERBOSE-3 	100000	SerializationManager	]	Registered type Bond.Tag.bonded`1[T] as Bond.Tag.bonded`1'1	
[2016-05-25 02:54:15.511 GMT     1	VERBOSE-3 	100000	AssemblyProcessor	]	Processing type Bond.Tag.structT	
[2016-05-25 02:54:15.511 GMT     1	VERBOSE-2 	100000	SerializationManager	]	Scanning assembly C:\Item\hulk\GameSiloHost\GameSiloHost\bin\Debug\Bond.Attributes.dll for serialization info	
“GameSiloHost.exe”(CLR v4.0.30319: GameSiloHost.exe): 已加载“C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll”。模块已生成，不包含符号。
引发的异常:“System.NullReferenceException”(位于 OrleansBondUtils.dll 中)
“GameSiloHost.exe”(CLR v4.0.30319: OrleansHost): 已加载“C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll”。
[2016-05-25 02:54:59.925 GMT     1	VERBOSE-3 	100000	AssemblyProcessor	]	Processing assembly Microsoft.VisualStudio.Debugger.Runtime	
[2016-05-25 02:54:59.925 GMT     1	VERBOSE-3 	100000	AssemblyProcessor	]	Processing type Microsoft.VisualStudio.Debugger.Runtime.CrossThreadMessagingException	
[2016-05-25 02:54:59.925 GMT     1	VERBOSE-2 	100000	SerializationManager	]	Scanning assembly C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll for serialization info	
GameSiloHost.exe Error: 0 : [2016-05-25 02:55:00.011 GMT     1	ERROR  	102401	AssemblyProcessor	]	!!!!!!!!!! Failed to load type Microsoft.VisualStudio.Debugger.Runtime.CrossThreadMessagingException in assembly Microsoft.VisualStudio.Debugger.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	
Exc level 0: System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Orleans.Serialization.BondSerializer.IsSupportedType(Type itemType)
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 Orleans.Serialization.SerializationManager.TryLookupExternalSerializer(Type t, IExternalSerializer& serializer)
   在 Orleans.Serialization.SerializationManager.FindSerializationInfo(Type type)
   在 Orleans.Runtime.AssemblyProcessor.ProcessAssembly(Assembly assembly)
[2016-05-25 02:55:00.049 GMT     1	VERBOSE-3 	100000	AssemblyProcessor	]	Processing type Microsoft.VisualStudio.Debugger.Runtime.Main	
[2016-05-25 02:55:00.065 GMT     1	VERBOSE-2 	100000	SerializationManager	]	Scanning assembly C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll for serialization info	
[2016-05-25 02:55:00.065 GMT     1	VERBOSE-3 	100000	SerializationManager	]	Registered type Microsoft.VisualStudio.Debugger.Runtime.Main as Microsoft.VisualStudio.Debugger.Runtime.Main	
[2016-05-25 02:55:00.065 GMT     1	VERBOSE-3 	100000	AssemblyProcessor	]	Processing type Microsoft.VisualStudio.Debugger.Runtime.Tracing	
[2016-05-25 02:55:00.065 GMT     1	VERBOSE-2 	100000	SerializationManager	]	Scanning assembly C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll for serialization info	
GameSiloHost.exe Error: 0 : [2016-05-25 02:55:00.143 GMT     1	ERROR  	102401	AssemblyProcessor	]	!!!!!!!!!! Failed to load type Microsoft.VisualStudio.Debugger.Runtime.Tracing in assembly Microsoft.VisualStudio.Debugger.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	
Exc level 0: System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Orleans.Serialization.BondSerializer.IsSupportedType(Type itemType)
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 Orleans.Serialization.SerializationManager.TryLookupExternalSerializer(Type t, IExternalSerializer& serializer)
   在 Orleans.Serialization.SerializationManager.FindSerializationInfo(Type type)
   在 Orleans.Runtime.AssemblyProcessor.ProcessAssembly(Assembly assembly)
[2016-05-25 02:55:00.174 GMT     1	VERBOSE-3 	100000	AssemblyProcessor	]	Processing type Microsoft.VisualStudio.Debugger.Runtime.FunctionEvaluationController

**Comment by sergeybykov** [comment] 2016-05-25 17:09
So this is a debugger issue?

**Comment by Carlm-MS** [comment] 2016-05-25 18:52
We were able to repro this with our project a few weeks back and tweaked the serializer code to get around the problem by instantiating the static members in the Initialize() method. 

Since that's the case, I'll submit a PR with what we did to fix it.

**Comment by Carlm-MS** [comment] 2016-05-25 19:18
@sergeybykov Which compiler is used when the NuGet packages are generated/published?  It may be a bug in the compiler that is the root cause of the problem considering that the issue went away when @lilinghui generated the assembly from source.

**Comment by sergeybykov** [comment] 2016-05-25 20:08
It's VS 2015 compiler on our build servers.

**Comment by gabikliot** [comment] 2016-06-02 05:38
Fixed via #1790.

**Closed by gabikliot** 2016-06-02 05:38 UTC

**Comment by lilinghui** [comment] 2016-06-05 02:35
good job @gabikliot

**Comment by gabikliot** [comment] 2016-06-05 05:21
I didn't fix it. It was @carlm-ms.
