### ISSUE TITLE
CustomDictionary Serialization Bug - Orleans 7.1.2

### ISSUE THREAD

**Issue by cmeyertons** [dotnet/orleans#8551] opened 2023-07-19 16:35 UTC
Custom Dictionaries are not generating codecs appropriately as described as fixed in a couple of prior issues: https://github.com/dotnet/orleans/issues/5029, https://github.com/dotnet/orleans/issues/6158

Is there any guidance here on proper implementation?

Code:

```csharp
public interface IReadOnlyCustomDictionary : IReadOnlyCustomDictionary<object?>
{
    [ExcludeFromCodeCoverage]
    public static IReadOnlyCustomDictionary Empty { get; } = new CustomDictionary();
}

[GenerateSerializer]
public class CustomDictionary : CustomDictionary<object?>, IReadOnlyCustomDictionary
{
    // mirror the underlying dictionaries constructors, but enforce the default equality comparer to be used.
    public CustomDictionary() : base() { }

    public CustomDictionary(int capacity) : base(capacity) { }

    public CustomDictionary(IEnumerable<KeyValuePair<string, object?>> collection) : base(collection) { }

    public CustomDictionary(IDictionary<string, object?> dictionary) : base(dictionary) { }
}

public interface IReadOnlyCustomDictionary<TValue> : IReadOnlyDictionary<string, TValue>
{ }

[GenerateSerializer]
public class CustomDictionary<TValue> : Dictionary<string, TValue>, IReadOnlyCustomDictionary<TValue>
{
    // mirror the underlying dictionaries constructors, but enforce the default equality comparer to be used.
    public CustomDictionary() : base() { }

    public CustomDictionary(int capacity) : base(capacity) { }

    public CustomDictionary(IEnumerable<KeyValuePair<string, TValue>> collection) : base(collection) { }

    public CustomDictionary(IDictionary<string, TValue> dictionary) : base(dictionary) { }
}

public interface ICustomDictionarySerializationGrain : IGrainWithIntegerKey
{
    ValueTask<CustomDictionary<int>> GetIntDictionary();
    ValueTask<CustomDictionary> GetRawDictionary();
    ValueTask<IReadOnlyCustomDictionary> GetRawDictionaryReadonly();
}

public class CustomDictionarySerializationGrain : Grain, ICustomDictionarySerializationGrain
{
    public ValueTask<CustomDictionary> GetRawDictionary() => ValueTask.FromResult(new CustomDictionary() { { "key", "test" } });
    public async ValueTask<IReadOnlyCustomDictionary> GetRawDictionaryReadonly() => await GetRawDictionary();

    public ValueTask<CustomDictionary<int>> GetIntDictionary() => ValueTask.FromResult(new CustomDictionary<int>() { { "key", 1234 } });
}
```

Exception :
```

System.Collections.Generic.KeyNotFoundException
Could not find a base type serializer for type System.Collections.Generic.Dictionary`2[System.String,System.Int32].
   at Orleans.Serialization.Serializers.CodecProvider.ThrowBaseCodecNotFound(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 668
   at Orleans.Serialization.Serializers.CodecProvider.GetBaseCodec[TField]() in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 269
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
```

If I comment out the IntDictionary calls:

```
System.Collections.Generic.KeyNotFoundException
Could not find a base type serializer for type System.Collections.Generic.Dictionary`2[System.String,System.Object].
   at Orleans.Serialization.Serializers.CodecProvider.ThrowBaseCodecNotFound(Type fieldType) in /_/src/Orleans.Serialization/Serializers/CodecProvider.cs:line 668
```

**Comment by ReubenBond** [comment] 2023-07-19 16:41
This ought to be fixed in 7.2.x, but we need to add a regression test for it.
I am not sure why the previous support for this, as I mentioned implementing in the two linked issues, was un-done.

**Comment by ReubenBond** [comment] 2023-07-19 18:02
That will break if you change that (eg, once you migrate to 7.2), since there's no feasible way to make that backwards compatible without you implementing some manual conversion/serialization logic

**Comment by cmeyertons** [comment] 2023-07-19 18:15
No worries. We are in a pre-prod state so don’t need to worry about breaking change in live environment.

**Closed** 2023-07-24 16:08 UTC
