### ISSUE TITLE
Client unable to communicate with Silo

### ISSUE THREAD

**Issue by ponsakthi** [dotnet/orleans#3410] opened 2017-09-18 08:51 UTC
We have an infrastructure with 3 Clients(C1,C2,C3) and 10 Silos(S1,S2,S3......) hosted on Azure Cloud Service.
We faced the following issue in one our production environment and we need your help to zero-in on the root cause.
When the clients(WebRole) were coming up and when one of the client was trying to call  
`AzureClient.Initialize(clientConfigurationFile);`
it ended up with the following exception while trying to connect to one Silo(Say Silo3)
`Client.Initialize failed with exc --Response did not arrive on time in 00:00:30 for message: Request *cli/15df4d8e@777e8393->S10.91.24.88:30000:242460026TypeManagerId@S00000011 #2: global::Orleans.Runtime.IClusterTypeManager:GetClusterTypeCodeMap(). Target History is: <S10.91.24.88:30000:242460026:TypeManagerId:@S00000011>.Will try again`

Later as the message said , the client retried and `AzureClient.Initialize` method succeeded.

- However, from then on , neither of the 3 clients were able to make any calls to the problematic silo (Silo 3). All those calls ended up with Response time out exceptions.

- But Silos were able to communicate among themselves.(eg Silo 3 was able to make calls to Silo4 without any issues).

- Client.ConnectedGatewayCount was **10** as seen from ClientLogStatistics. Ideally it should have been **9** taking into account , the problematic silo

- From SiloLogStatistics, I could see **Gateway.Received.Current** settling down to a stand still number with Delta=0 for every 15 secs cycle.

We did not get any other useful logs on why this happened. Our log settings default to "Info" for LogPrefix="Application" in Silo configuration. What more do you think we should look at to get to the root cause of this connectivity problem?

More over, which logger (Runtime,Messaging,Scheduling) should we change to verbose to get more information of the ongoing problem in future?

**Comment by sergeybykov** [comment] 2017-09-18 15:30
What version of Orleans is this? Can you share the logs?

**Comment by ponsakthi** [comment] 2017-09-19 05:56
Orleans Version -> 1.4.1
@sergeybykov : I have sent logs to your mail.

**Comment by jdom** [comment] 2017-09-20 20:18
I have not looked at the logs, although this has the same symptoms as the issue when there is server clock skew. This was fixed in Orleans 1.4.2 (with PR https://github.com/dotnet/orleans/pull/2922).
If the servers are still running, can you verify the time is skewed between them?

**Comment by jdom** [comment] 2017-09-28 17:44
Was this the cause of the issue? If so, can we close this?

**Comment by aloysiustany** [comment] 2017-10-05 05:46
We are in process of upgrading to Orleans 1.4.2. Will keep posted here on the update after upgrade.

**Comment by aloysiustany** [comment] 2017-10-09 08:42
We upgraded to Orleans 1.4.2. But, we again faced the same issue couple of days after the upgrade.
Can you please have a look at the logs that @ponsakthi had sent to see if you could help us point to the cause of the issue.

**Comment by galvesribeiro** [comment] 2017-10-29 18:33
Heads up: 

![image](https://user-images.githubusercontent.com/4714040/32146998-ca53756e-bcc6-11e7-819f-af6e0d6e5059.png)

Same problem on 2.0 beta1. Not sure how clock is related in my case. I'm running both client and silo on the same process.

**Comment by galvesribeiro** [comment] 2017-10-29 19:14
After some changes on config around, not I have a different error:
![image](https://user-images.githubusercontent.com/4714040/32147325-a14e336a-bccc-11e7-985c-83d7989fe4a3.png)

**Comment by sergeybykov** [comment] 2017-11-30 21:31
I believe this has been resolved offline. Please confirm.

**Comment by ponsakthi** [comment] 2017-12-04 09:31
Yes @sergeybykov . The issue is resolved after changing Azure CloudService's service configuration to InternalEndpoint from InputEndPoint.

**Closed** 2017-12-04 16:29 UTC
