### ISSUE TITLE
The type or namespace name 'GenericMethodInvoker' does not exist in the namespace 'Orleans.CodeGeneration' 

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#4385] opened 2018-04-02 16:11 UTC
orleans2.0
ex:  `Task<TResult> Invoke<TResult>(object[] args);`
Error	CS0234	The type or namespace name 'GenericMethodInvoker' does not exist in the namespace 'Orleans.CodeGeneration' (are you missing an assembly reference?)

Do not support generics?

1.5.3 is ok

**Comment by sergeybykov** [comment] 2018-04-02 16:32
Can you provide the full definition of the method/interface you are using here?

**Comment by sundong1982** [comment] 2018-04-02 16:49
`    public interface IDemo: IGrainWithStringKey
    {
        Task<T> X<T>();
    }`

csproj file:
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="2.0.1" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Orleans.OrleansCodeGenerator.Build" Version="2.0.0" />
  </ItemGroup>

</Project>

**Comment by sundong1982** [comment] 2018-04-03 02:30
Your .net core2  sample (Hello word) also has this problem, When I add a generic method。
@sergeybykov @Triage @ReubenBond

**Comment by ReubenBond** [comment] 2018-04-03 03:04
@sundong1982 could you add a reference to `Microsoft.Orleans.Core`? That will fix your problem

**Comment by sundong1982** [comment] 2018-04-03 04:54
After adding a reference `Microsoft.Orleans.Core,` it's good。
hope you can repair it as soon as possible, and I'm developing a new project with it. :)

**Comment by jsteinich** [comment] 2018-04-03 13:15
Sounds like the same issue as https://github.com/dotnet/orleans/issues/4039

**Comment by sundong1982** [comment] 2018-04-04 01:08
add a reference `Microsoft.Orleans.Core` is ok

**Comment by ReubenBond** [comment] 2018-04-04 01:39
I'll close this as a duplicate of #4039

**Closed by ReubenBond** 2018-04-04 01:39 UTC
