### ISSUE TITLE
Improving startup time for dev/test?

### ISSUE THREAD

**Issue by TrexinanF14** [dotnet/orleans#2098] opened 2016-08-26 15:17 UTC
Currently when I'm running orleans with the client/silo in the same process, orleans takes ~15 seconds to complete SiloHost.InitializeOrleansSilo(...) and another ~30 seconds to complete GrainClient.Initialize(...). Are there conditions or configuration settings that would slow down the init process? For instance, I have about 130 dlls (thanks aspnet core) in the project folder that orleans scans on startup, but I don't know how serious of an impact that would be. I'm not hitting any non-local resources and I don't have many non-default configuration settings (trace settings and setting up the storage provider mainly).

**Comment by sergeybykov** [comment] 2016-08-29 16:25
This is way too long of a startup time IMO to be usable. Did you measure where the time is spent? I suspect you are right that the 130 assemblies are likely the cause.

We are looking at adding explicit scanning of only given assemblies instead of every binary we can find. #2025 is an attempt in that direction. And it's one of the workitems for .NET Core compatibility.

**Comment by TrexinanF14** [comment] 2016-08-29 18:34
I've been following that issue, once it gets merged in I'll give it a shot with my project and see if it brings down the startup time. In the interim I was thinking about

**Comment by TrexinanF14** [comment] 2016-08-29 18:43
I've been planning on temporarily stripping out most of the assemblies to see if the startup time drops, but I haven't had the chance yet. If that proves to be the problem then I'll wait until #2025 gets merged in and give it a whirl.

**Comment by talarari** [comment] 2017-12-12 17:55
@sergeybykov is there any way workaround to tell Orleans to only look at specific assemblies in 1.5.3? 
That  would really help until 2.0 is ready (and until we are ready to migrate).

**Comment by sergeybykov** [comment] 2017-12-12 18:05
@talarari Unfortunately, no.

**Comment by sergeybykov** [comment] 2018-01-06 01:11
Closing this, as we don't scan all assemblies by default in 2.0.0.

**Closed by sergeybykov** 2018-01-06 01:11 UTC
