### ISSUE TITLE
Errors When deploying to Azure App Services

### ISSUE THREAD

**Issue by sudsy** [dotnet/orleans#2152] opened 2016-09-14 04:40 UTC
I am deploying my Orleans App for the first time and encountering errors when deploying to an Azure App Service (Web App).

The trace of my error is at http://pastebin.ca/3715471

Some further information
- The application runs in release build on my local IIS development server
- The application runs under the local Azure Storage Emulator if I configure it as a Web Role
- I have tried to ensure that my dependencies are at the level required by Orleans 
- I have ensured that tracing is turned off on my web application 
- I have ensured that there is no tracing configuration in the Web.Config file
- I have added a reference to Orleans.AzureUtils because it seems to be needed, but I am unsure if this is correct for a Web app
- I have tried prerelease v 1.3 orleans
- Tried setting TraceFileName = null and TraceToConsole false in orleans config

**Comment by sergeybykov** [comment] 2016-09-14 14:59
I suspect it throw at https://github.com/dotnet/orleans/blob/master/src/Orleans/Logging/LogManager.cs#L168 when the code tries to write an error to the `DefaultTraceListener`. What's not clear to me is why `AzureDriveTraceListener` is throwing the "disposed object" exception. I don't know why `AzureDriveTraceListener` is there to begin with.

Maybe try to empty `Trace.Listeners` before initializing Orleans.

**Comment by sudsy** [comment] 2016-09-15 07:30
Clearing Trace.Listeners did the trick. Thanks! I have yet to see if there are side effects to this. Once I get a little time back I will try to stand up a plain vanilla Web App and see if it has the same problem.

I have moved on somewhat, now getting the following error, which seems to be some sort of networking issue. I will work on it again tomorrow to see if I can resolve it, but if you have any tips in the meantime they would be appreciated.

```
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>
Response did not arrive on time in 00:00:30 for message: Request *cli/ac5c6195@c9a0f6ab->S10.0.0.5:40000:211618952TypeManagerId@S00000011 #6: global::Orleans.Runtime.ITypeManager:GetTypeCodeMap(). Target History is: <S10.0.0.5:40000:211618952:TypeManagerId:@S00000011>.
</ExceptionMessage>
<ExceptionType>System.TimeoutException</ExceptionType>
<StackTrace>
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Orleans.GrainClient.InternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient) at Orleans.GrainClient.Initialize(ClientConfiguration config) at PVL.WebService.OrleansHelper.initialiseOrleans() at PVL.WebService.CSharp.Controllers.TestController.Get() at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClassc.<GetExecutor>b__6(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
</StackTrace>
</Error>
```

**Comment by sergeybykov** [comment] 2016-09-15 14:16
Client is trying to failing to retrieve a type code map from a silo via `ITypeManager:GetTypeCodeMap()`.

Do you have TCP ports open on the silo for silo-to-silo and client-to-gateway connectivity?

**Comment by sudsy** [comment] 2016-10-20 06:28
Just Checked this on a brand new web service in Azure with a Brand new Web App in Visual Studio and I get the same error 
```
Cannot access a disposed object.
 Object name: 'Microsoft.WindowsAzure.WebSites.Diagnostics.AzureDriveTraceListener'.
```
This Error Occurs when I call ```Trace.TraceInformation("foo");```

I am currently working on suitable workaround to allow me to receive Trace Information in my Application Insights stream while disabling the drivetracelistener.

**Comment by sergeybykov** [comment] 2016-10-20 23:22
You mentioned before that
>Clearing Trace.Listeners did the trick.

Is it different now?

**Comment by sudsy** [comment] 2016-10-21 00:17
Clearing trace listeners did get rid of the error but it also disabled tracing.
So, the built in features of being able to turn tracing on and off in the azure console has no effect as far as I can tell.
I needed an alternative way to get my trace information which ended up being Application Insights.
Once I had set up Application Insights on the project it was actually easier than I thought to get my trace output into it.

After my call to `Trace.Listeners.Clear();`, I just added `Trace.Listeners.Add(new ApplicationInsightsTraceListener());`

**Comment by attilah** [comment] 2016-10-27 20:38
I've checked the stacktrace and since I see a call to Orleans.Runtime.TraceLogger.Initialize I suspect that you were running 1.2.x version of Orleans and Logging was totally revamped by @jason-bragg in 1.3.0.

Probably the error can still produce itself, since the initialize method did not change for the logger, but it did change for Orleans Client initialization.

@sudsy Could you please test it with 1.3.0? or share a minimal repro project with us?

**Comment by sudsy** [comment] 2016-11-03 23:53
I have put together the most basic repo:

https://github.com/sudsy/orleansTracingSample

It uses version 1.3 of Orleans. with the minimum amount of changes from the default template I could manage.

It was published to azure directly from git using the azure web app continuous deployment option.

It is hosted at: [](http://orleanstracingsample.azurewebsites.net/)

**Comment by attilah** [comment] 2016-11-04 21:42
@sudsy I was able to reproduce and get to the roots of the bug.

The problem is that during client uninitialization, which is done if an error happens when constructing the client instance we're closing - beside other things - the LogManager. It involves closing of all TelemetryConsumers.

This closing includes the TraceTelemetryConsumer which affects you.

When we're done with the uninitialization, your catch is getting executed AND a Trace statement getting executed which ends in the ObjectDisposedException, since all the trace listeners are closed previously.

Beside it IS a bug, I think that client initialization is a really early phase/edge case, so you can easily workaround it if you put the Tracing call into a try/catch block.

**Comment by sudsy** [comment] 2016-11-04 22:23
Thanks,

That makes sense. 

I already have a workaround that is working pretty well for now. 

If I stick the Trace in a try catch block I will never see an entry in my trace log showing the failure.

**Comment by attilah** [comment] 2016-11-08 00:35
Fixed by merging: https://github.com/dotnet/orleans/pull/2396

**Closed by attilah** 2016-11-08 00:35 UTC
Labels: bug
