### ISSUE TITLE
Are Reminder Names unique per grain?

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#1373] opened 2016-02-04 18:45 UTC
Breaking my head here...

Have 2 grain types: Sites and Nodes.

Both implement reminders.
This is how I register the reminder:
`await RegisterOrUpdateReminder(REMINDER_NAME, TimeSpan.FromMinutes(TMO), TimeSpan.FromMinutes(PERIOD));`

REMINDER_NAME, TMO and PERIOD are private constants per class, obviously different for Site than for Node.

In TableStorage I see a Reminder row per site as expected
But I only see one reminder for all the nodes, like if it is reused.

Question: Do I need to append the unique identity to the ReminderName?

Thx!

**Comment by sergeybykov** [comment] 2016-02-04 18:48
Each grain has its own set (sort of a namespace) of reminders. Reminder names can be safely reused across grains and grain types. I suspect the issue is probably somewhere else. Are you sure `RegisterOrUpdateReminder` is successfully called from more than one grain?

**Comment by gabikliot** [comment] 2016-02-09 04:12
@ukluk , were you able to make more progress on that?
Can that issue be closed?

**Comment by sergeybykov** [comment] 2016-02-11 00:59
I'll close it. @ukluk please reopen if something isn't working as expected.

**Closed by sergeybykov** 2016-02-11 00:59 UTC
Labels: question
