### ISSUE TITLE
AzureSilo.Start() + WindowsAzure.Storage 8.0.0 raises Failed to create OrleansSiloInstanceManager

### ISSUE THREAD

**Issue by mauriciomagni** [dotnet/orleans#2543] opened 2016-12-23 08:39 UTC
When calling AzureSilo.Start() and WindowsAzure.Storage 8.0.0 is installed and Orleans.Runtime.OrleansException is raised (Orleans version: 1.3.1)
**Note: The very same code works properly with WindowsAzure.Storage 7.2.1**

The code:
`            string storageConnectionString = RoleEnvironment.GetConfigurationSettingValue("DataConnectionString");

            var config = AzureSilo.DefaultConfiguration();
            config.AddAzureTableStorageProvider("AzureStore", storageConnectionString, "VisibleShippingGrainState");

            silo = new AzureSilo();
            bool ok = silo.Start(config);`

The connectionString is "UseDevelopmentStorage=true"

The error message:
`An unhandled exception of type 'Orleans.Runtime.OrleansException' occurred in OrleansAzureUtils.dll

Additional information: Failed to create OrleansSiloInstanceManager. This means CreateTableIfNotExist for silo instance table has failed with 

Exc level 0: System.AggregateException: One or more errors occurred.

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at Orleans.Runtime.Host.AzureSilo.Start(ClusterConfiguration config, String deploymentId, String connectionString)

Exc level 1: Orleans.Runtime.OrleansException: Exception trying to create or connect to the Azure table: The remote server returned an error: (400) Bad Request.

   at Orleans.AzureUtils.OrleansSiloInstanceManager.<GetManager>d__14.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Orleans.OrleansTaskExtentions.<WithTimeout>d__8`1.MoveNext()

Exc level 2: Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request.

   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 50

   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndCreateIfNotExists(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 1286

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Orleans.AzureUtils.AzureTableDataManager`1.<InitTableAsync>d__15.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Orleans.OrleansTaskExtentions.<WithTimeout>d__7.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Orleans.AzureUtils.OrleansSiloInstanceManager.<GetManager>d__14.MoveNext()

Exc level 3: System.Net.WebException: The remote server returned an error: (400) Bad Request.

   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPreProcess(TableResult result, TableOperation operation, HttpWebResponse resp, Exception ex) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpResponseParsers.cs:line 61

   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 299`

**Comment by attilah** [comment] 2016-12-23 09:33
@mauriciomagni please try the same code against real azure storage and not the emulator.

My suspicion from the error is that you need to install newer azure storage emulator, which supports azure storage 8.0.

Could you please double check it?

**Comment by attilah** [comment] 2016-12-23 09:38
You can find the link to the 4.6 version of Storage Emulator on this page: https://azure.microsoft.com/en-us/downloads/ which was recently released.

**Comment by kogir** [comment] 2016-12-23 17:11
I also experienced this problem, and can confirm that Storage Emulator 4.6 fixes it. Sadly it's currently incompatible with the Azure tooling in Visual Studio 2017 RC. Can't win them all, I guess.

In any case, the issue is in Azure/azure-storage-net. The [release notes](https://github.com/Azure/azure-storage-net/releases/tag/v8.0.0) state:
```
All: Support for 2016-05-31 REST version. Please see our REST API documentation and blogs for information about the related added features. If you are using the Storage Emulator, please update to Emulator version 4.6.
```

Rolling back to 7.2.1 works fine for now.

**Comment by attilah** [comment] 2016-12-23 18:11
@kogir thanks for confirming, that's what I found out also, so closing this as a non Orleans issue.

**Closed by attilah** 2016-12-23 18:11 UTC
