### ISSUE TITLE
Orleans extreme slow when debuging

### ISSUE THREAD

**Issue by montella1507** [dotnet/orleans#8427] opened 2023-05-09 17:03 UTC
Hi, 

anyone experiencing issues with debugging on MacOS M2 / Rider?

Orleans is like 500x times slower when debugger is attached. 

Orleans 7.0, .NET Core 7.0

**Comment by montella1507** [comment] 2023-05-09 18:01
When i Detach debugger it runs normally afterward...

**Comment by ReubenBond** [comment] 2023-05-09 18:09
Is that 500x number measured or an estimate? Are you attaching a debugger to a Debug build of your application, or a Release build? I would expect it to be about 10x slower, but it depends on what you're doing. I'm also not familiar with the debugger on macOS. Maybe it's much slower.

**Comment by montella1507** [comment] 2023-05-16 07:05
Seems so! Thank you!

**Comment by montella1507** [comment] 2023-05-16 07:07
Seems so! Thank you 

Unfortunately i can confirm this:

> 
> This is extremely frustrating, and makes debugging barely functional.
> It's quicker to debug using log statements.

So i hope it will get fixed soon

**Comment by slonopotamus** [comment] 2023-05-16 16:05
We're also seeing this with .NET 6.0 + Orleans 3.6.2 and believe that https://github.com/dotnet/runtime/issues/38736 is the root cause. And no, 500x is not an exaggeration.

**Comment by ReubenBond** [comment] 2023-05-16 17:38
It sounds like this is a Mac-specific issue. Please👍 that issue and/or respond to it to try to get it resolved.

**Comment by montella1507** [comment] 2023-05-17 20:14
I Will try the performance on Windows then.

**Comment by montella1507** [comment] 2023-05-25 12:51
@ReubenBond 

Windows - JetBrains Rider- 10700k, 64GB RAM,  200 grains:
- no debug 280 - 330ms 
- debug 1300 ms


macOS - JetBrains Rider- M2 Air , 24GB unified,  200 grains:
- no debug - 300-370ms
- debug - 22 000 ms 

 So it may be mac-specific issue

**Comment by mkuennek** [comment] 2023-12-20 13:41
We also encountered this issue while evaluating Orleans, but for both Windows and MacOS. Really rough to use Orleans like this.

**Comment by ReubenBond** [comment] 2023-12-20 14:39
@mkuennek is performance under the debugger equally bad on Win & Mac? When you run under the debugger, are you also changing any other settings, such as log levels? Please add feedback (thumbs up, comment with info) to the original .NET runtime issue: https://github.com/dotnet/runtime/issues/38736

**Comment by mkuennek** [comment] 2023-12-20 18:55
@ReubenBond Without having any hard number I would say both Mac and Windows experience the same performance degradation. Both platforms start showing same types of warnings and errors(slow storage access, failing to activate grains). We do not change any other settings. Both runs were in Debug configuration with same log levels, etc.

Thank you for the feedback. Already voted in the mentioned runtime issue.

Both platform tests were done using the current version of Rider but we also had another developer using Windows with VS report this problem.

**Comment by ReubenBond** [comment] 2023-12-20 19:09
Thanks for the info, @mkuennek. Hopefully we can get this fixed in the .NET Runtime and/or debuggers. I'm not sure why this is more of an issue on mac than Windows. My inkling was that the issue was related to the way that Rider's debugger handles the notification, but if behavior is the same on Windows under VS (which I have not yet experienced), then perhaps that is not the case. I've asked for more information on the dotnet/runtime thread.

**Comment by mkuennek** [comment] 2023-12-20 19:56
I just installed VS to check it myself. The behavior is the same as with Rider.

If you think a small project for reproducing this issue could help, I can try providing one.

**Comment by ReubenBond** [comment] 2023-12-20 19:57
Thanks. The dotnet/runtime thread has a minimal repro already. The problem seems to be well understood by the runtime engineers and we're just waiting for a fix now.

**Comment by bc3** [comment] 2024-01-10 07:06
hello, not on the orleans project, but i have a sort a like issue, I reported this today to Jetbrains: https://youtrack.jetbrains.com/issue/RIDER-104266/Blazor-server-app-performs-very-slow-when-run-from-debugger-on-Mac-M2 , add upvotes or something :D

**Comment by yoDon** [comment] 2024-02-01 01:57
Adding my vote to the "please address this incredibly important issue" counter.

I just lost several days to this issue, trying to understand why my code was suddenly unusably slow.

I'm running Rider IDE on a Mac M3 Pro.

**Comment by gaoyang** [comment] 2024-02-01 06:08
The same thing that keeps me from working. 

https://youtrack.jetbrains.com/issue/RIDER-105306/Execution-is-too-slow-when-debugging-code

**Comment by bc3** [comment] 2024-02-22 07:09
@gaoyang , @yoDon : i've downloaded EAP JetBrains Rider 2024.1 EAP 5 => see my info in the thread on the jetbrains forum https://youtrack.jetbrains.com/issue/RIDER-104266/Blazor-server-app-performs-very-slow-when-run-from-debugger-on-Mac-M2#focus=Comments-27-9227967.0-0

**Comment by ReubenBond** [comment] 2024-05-07 03:37
A fix has just been merged into [dotnet/runtime](https://github.com/dotnet/runtime/pull/101864)!

**Comment by yoDon** [comment] 2024-05-07 11:33
For those watching or encountering this, note that the merged fix is for .NET 9 not .NET 8

**Comment by ReubenBond** [comment] 2024-05-15 18:42
> For those watching or encountering this, note that the merged fix is for .NET 9 not .NET 8

Correct. Noah made a comment about it here: https://github.com/dotnet/runtime/pull/101864#issuecomment-2097518279

If you'd like to try this out, you can install a .NET 9.0 nightly build from here: https://github.com/dotnet/installer?tab=readme-ov-file#table

I will close this now, since the runtime issue is fixed. Please feel free to open a new issue referencing this if you hit similar symptoms.

**Closed by ReubenBond** 2024-05-15 18:42 UTC
Labels: Needs: triage :mag:
