### ISSUE TITLE
SiloStatusChangeNotification being hit multiple times

### ISSUE THREAD

**Issue by claycass17** [dotnet/orleans#6089] opened 2019-11-04 16:11 UTC
**Environment:**

- 4 Windows Servers (1 silo on each server)
- Consul Clustering
- Ado Reminders (MariaDB)

Current working orleans version 2.3.4 (no issues)
Issues reported once updated to orleans 2.4.3

**Reported Issue:**

MariaDb database being hit by large amounts of select reminders query. (643,945 selects in 40min starting with an empty reminders table, then eventually creating about 60 reminders)

`SELECT 		GrainId, 		ReminderName, 		StartTime, 		Period, 		Version 	FROM OrleansRemindersTable 	WHERE 		ServiceId = 'xxx' AND 'xxx' IS NOT NULL 		AND ((GrainHash > 2107253094 AND 2107253094 IS NOT NULL) 		OR (GrainHash <= -2052557686 AND -2052557686 IS NOT NULL))`

After tuning on Information logs we've seen 'Added Server..' log more than 13,000 times in 40min

`Added Server Sxx.xx.xxx.24:20001:310558213/xA2F1633E. Current view: [Sxx.xx.xxx.21:20001:310557917 -> <MultiRange: Size=x2FE94EF8, %Ring=18.715%>, Sxx.xx.xxx.22:20001:310557967 -> <MultiRange: Size=x3C9921CC, %Ring=23.671%>, Sxx.xx.xxx.24:20001:310558213 -> <MultiRange: Size=x422D3E8A, %Ring=25.850%>, Sxx.xx.xxx.23:20001:310558077 -> <MultiRange: Size=x515050B2, %Ring=31.763%>]`

This log is being called via this call stack: 

SiloStatusListenerManager.Participate.ProcessMembershipUpdates.NotifyObservers ->
VirtualBucketsRingProvider.SiloStatusChangeNotification.**AddServer**.NotifyLocalRangeSubscribers - > RangeChangeNotification.OnRangeChange.ReadAndUpdateReminders.ReadTableAndStartTimers

The log 'Starting VirtualBucketsRingProvider on silo' is only hit 4 times within the 40min session.

What is triggering Silo Status Change Notification?

**Comment by ReubenBond** [comment] 2019-11-04 16:16
@claycass17 are you able to provide more redcacted logs as well as a dump of the membership table?

**Comment by claycass17** [comment] 2019-11-05 09:37
Consul membership table keys:

**orleans/ProjectName.2.0.0.121.Testing/xx.xx.xxx.21:20001@310640119**
{"Hostname":"myHostName-B01","ProxyPort":30001,"StartTime":"2019-11-05T08:55:20.8704056Z","Status":3,"SiloName":"Silo_d15d7","SuspectingSilos":[]}

**orleans/ProjectName.2.0.0.121.Testing/xx.xx.xxx.21:20001@310640119/iamalive**
"2019-11-05T09:30:24.0667746Z"

**orleans/ProjectName.2.0.0.121.Testing/xx.xx.xxx.22:20001@310640120**
{"Hostname":"myHostName-B02","ProxyPort":30001,"StartTime":"2019-11-05T08:55:21.8319148Z","Status":3,"SiloName":"Silo_f1c02","SuspectingSilos":[]}

**orleans/ProjectName.2.0.0.121.Testing/xx.xx.xxx.22:20001@310640120/iamalive**
"2019-11-05T09:30:34.705656Z"

**orleans/ProjectName.2.0.0.121.Testing/xx.xx.xxx.23:20001@310640711**
{"Hostname":"myHostName-B03","ProxyPort":30001,"StartTime":"2019-11-05T09:05:12.8324481Z","Status":3,"SiloName":"Silo_fde4c","SuspectingSilos":[]}

**orleans/ProjectName.2.0.0.121.Testing/xx.xx.xxx.23:20001@310640711/iamalive**
"2019-11-05T09:30:24.6599031Z"

**orleans/ProjectName.2.0.0.121.Testing/xx.xx.xxx.24:20001@310640715**
{"Hostname":"myHostName-B04","ProxyPort":30001,"StartTime":"2019-11-05T09:05:16.9799814Z","Status":3,"SiloName":"Silo_99f5f","SuspectingSilos":[]}

**orleans/SportsbookEngine.OddsProcessing.2.0.0.121.Testing/xx.xx.xxx.24:20001@310640715/iamalive**
"2019-11-05T09:30:22.5943315Z"

**Comment by claycass17** [comment] 2019-11-06 12:25
I've added some logs in Orleans.Runtime.dll 2.4.3 in SiloStatusListenerManager.ProcessMembershipUpdatesAsync to capture whats inside _snapshot_ on line 86 
`var snapshot = enumerator.Current.CreateClusterMembershipSnapshot();
log.LogInformation($"Enumerating MembershipTableSnapshot Version:{snapshot.Version} Members count:{snapshot.Members.Count}");`

And logged before calling `this.NotifyObservers(update);`

`log.LogInformation($"About to call NotifyObservers; hasChanges: {update.HasChanges} Snapshot: {update.Snapshot} Changes: {changes}");
this.NotifyObservers(update);

`
The first log loggs:

> Enumerating MembershipTableSnapshot Version:-9223372036854775808 Members count:199

The second logs:

> About to call NotifyObservers; hasChanges: True Snapshot: Version: -9223372036854775808. 199 members: Sxx.xx.xxx.24:20001:310730805/Dead, Sxx.xx.xxx.24:20001:310730762/Dead, Sxx.xx.xxx.24:20001:310730780/Dead, Sxx.xx.xxx.24:20001:310730860/Dead, Sxx.xx.xxx.24:20001:310730824/Dead, Sxx.xx.xxx.24:20001:310731933/Dead, Sxx.xx.xxx.24:20001:310732164/Dead, Sxx.xx.xxx.24:20001:310732537/Dead, Sxx.xx.xxx.24:20001:310732504/Dead, Sxx.xx.xxx.24:20001:310732690/Dead, Sxx.xx.xxx.24:20001:310733255/Dead, Sxx.xx.xxx.24:20001:310733619/Active, Sxx.xx.xxx.24:20001:310728158/Dead, Sxx.xx.xxx.24:20001:310730606/Dead, Sxx.xx.xxx.24:20001:310730669/Dead, Sxx.xx.xxx.24:20001:310730631/Dead, Sxx.xx.xxx.24:20001:310730648/Dead, Sxx.xx.xxx.24:20001:310730728/Dead, Sxx.xx.xxx.24:20001:310730740/Dead, Sxx.xx.xxx.24:20001:310730689/Dead, Sxx.xx.xxx.24:20001:310730713/Dead, Sxx.xx.xxx.22:20001:310728156/Dead, Sxx.xx.xxx.22:20001:310730535/Dead, Sxx.xx.xxx.22:20001:310730618/Dead, Sxx.xx.xxx.22:20001:310730589/Dead, Sxx.xx.xxx.22:20001:310730563/Dead, Sxx.xx.xxx.22:20001:310730669/Dead, Sxx.xx.xxx.22:20001:310730646/Dead, Sxx.xx.xxx.22:20001:310730739/Dead, Sxx.xx.xxx.22:20001:310730713/Dead, Sxx.xx.xxx.22:20001:310730690/Dead, Sxx.xx.xxx.22:20001:310730492/Dead, Sxx.xx.xxx.22:20001:310731025/Dead, Sxx.xx.xxx.22:20001:310730806/Dead, Sxx.xx.xxx.22:20001:310730786/Dead, Sxx.xx.xxx.22:20001:310730765/Dead, Sxx.xx.xxx.22:20001:310730872/Dead, Sxx.xx.xxx.22:20001:310730851/Dead, Sxx.xx.xxx.22:20001:310730827/Dead, Sxx.xx.xxx.22:20001:310730921/Dead, Sxx.xx.xxx.22:20001:310730892/Dead, Sxx.xx.xxx.22:20001:310730981/Dead, Sxx.xx.xxx.22:20001:310730959/Dead, Sxx.xx.xxx.22:20001:310732588/Dead, Sxx.xx.xxx.22:20001:310732568/Dead, Sxx.xx.xxx.22:20001:310732548/Dead, Sxx.xx.xxx.22:20001:310732665/Dead, Sxx.xx.xxx.22:20001:310732640/Dead, Sxx.xx.xxx.22:20001:310732608/Dead, Sxx.xx.xxx.22:20001:310732730/Dead, Sxx.xx.xxx.22:20001:310732709/Dead, Sxx.xx.xxx.22:20001:310732691/Dead, Sxx.xx.xxx.22:20001:310732792/Dead, Sxx.xx.xxx.22:20001:310732757/Dead, Sxx.xx.xxx.22:20001:310732340/Dead, Sxx.xx.xxx.22:20001:310732320/Dead, Sxx.xx.xxx.22:20001:310732296/Dead, Sxx.xx.xxx.22:20001:310732394/Dead, Sxx.xx.xxx.22:20001:310732373/Dead, Sxx.xx.xxx.22:20001:310732353/Dead, Sxx.xx.xxx.22:20001:310732456/Dead, Sxx.xx.xxx.22:20001:310732436/Dead, Sxx.xx.xxx.22:20001:310732527/Dead, Sxx.xx.xxx.22:20001:310732505/Dead, Sxx.xx.xxx.22:20001:310732485/Dead, Sxx.xx.xxx.22:20001:310732083/Dead, Sxx.xx.xxx.22:20001:310732269/Dead, Sxx.xx.xxx.22:20001:310733611/Active, Sxx.xx.xxx.22:20001:310733108/Dead, Sxx.xx.xxx.22:20001:310733079/Dead, Sxx.xx.xxx.22:20001:310733172/Dead, Sxx.xx.xxx.22:20001:310733157/Dead, Sxx.xx.xxx.22:20001:310733135/Dead, Sxx.xx.xxx.22:20001:310733229/Dead, Sxx.xx.xxx.22:20001:310732854/Dead, Sxx.xx.xxx.22:20001:310732825/Dead, Sxx.xx.xxx.22:20001:310732907/Dead, Sxx.xx.xxx.22:20001:310732879/Dead, Sxx.xx.xxx.22:20001:310732985/Dead, Sxx.xx.xxx.22:20001:310732957/Dead, Sxx.xx.xxx.22:20001:310732936/Dead, Sxx.xx.xxx.22:20001:310733053/Dead, Sxx.xx.xxx.22:20001:310733031/Dead, Sxx.xx.xxx.22:20001:310733014/Dead, Sxx.xx.xxx.23:20001:310733607/Active, Sxx.xx.xxx.23:20001:310733172/Dead, Sxx.xx.xxx.23:20001:310733140/Dead, Sxx.xx.xxx.23:20001:310733114/Dead, Sxx.xx.xxx.23:20001:310733091/Dead, Sxx.xx.xxx.23:20001:310733064/Dead, Sxx.xx.xxx.23:20001:310733243/Dead, Sxx.xx.xxx.23:20001:310732923/Dead, Sxx.xx.xxx.23:20001:310732897/Dead, Sxx.xx.xxx.23:20001:310732872/Dead, Sxx.xx.xxx.23:20001:310732843/Dead, Sxx.xx.xxx.23:20001:310732823/Dead, Sxx.xx.xxx.23:20001:310732803/Dead, Sxx.xx.xxx.23:20001:310733045/Dead, Sxx.xx.xxx.23:20001:310733025/Dead, Sxx.xx.xxx.23:20001:310733001/Dead, Sxx.xx.xxx.23:20001:310732973/Dead, Sxx.xx.xxx.23:20001:310732940/Dead, Sxx.xx.xxx.23:20001:310730866/Dead, Sxx.xx.xxx.23:20001:310730844/Dead, Sxx.xx.xxx.23:20001:310730825/Dead, Sxx.xx.xxx.23:20001:310730802/Dead, Sxx.xx.xxx.23:20001:310730781/Dead, Sxx.xx.xxx.23:20001:310730756/Dead, Sxx.xx.xxx.23:20001:310730971/Dead, Sxx.xx.xxx.23:20001:310730924/Dead, Sxx.xx.xxx.23:20001:310730906/Dead, Sxx.xx.xxx.23:20001:310730889/Dead, Sxx.xx.xxx.23:20001:310732669/Dead, Sxx.xx.xxx.23:20001:310732646/Dead, Sxx.xx.xxx.23:20001:310732620/Dead, Sxx.xx.xxx.23:20001:310732586/Dead, Sxx.xx.xxx.23:20001:310732553/Dead, Sxx.xx.xxx.23:20001:310732775/Dead, Sxx.xx.xxx.23:20001:310732748/Dead, Sxx.xx.xxx.23:20001:310732729/Dead, Sxx.xx.xxx.23:20001:310732709/Dead, Sxx.xx.xxx.23:20001:310732691/Dead, Sxx.xx.xxx.23:20001:310732525/Dead, Sxx.xx.xxx.23:20001:310732501/Dead, Sxx.xx.xxx.23:20001:310732476/Dead, Sxx.xx.xxx.23:20001:310732439/Dead, Sxx.xx.xxx.23:20001:310732161/Dead, Sxx.xx.xxx.23:20001:310730610/Dead, Sxx.xx.xxx.23:20001:310730580/Dead, Sxx.xx.xxx.23:20001:310730558/Dead, Sxx.xx.xxx.23:20001:310730525/Dead, Sxx.xx.xxx.23:20001:310730732/Dead, Sxx.xx.xxx.23:20001:310730709/Dead, Sxx.xx.xxx.23:20001:310730686/Dead, Sxx.xx.xxx.23:20001:310730665/Dead, Sxx.xx.xxx.23:20001:310730644/Dead, Sxx.xx.xxx.23:20001:310727543/Dead, Sxx.xx.xxx.21:20001:310729727/Dead, Sxx.xx.xxx.21:20001:310730485/Dead, Sxx.xx.xxx.21:20001:310730624/Dead, Sxx.xx.xxx.21:20001:310730648/Dead, Sxx.xx.xxx.21:20001:310730666/Dead, Sxx.xx.xxx.21:20001:310730689/Dead, Sxx.xx.xxx.21:20001:310730708/Dead, Sxx.xx.xxx.21:20001:310730729/Dead, Sxx.xx.xxx.21:20001:310730521/Dead, Sxx.xx.xxx.21:20001:310730555/Dead, Sxx.xx.xxx.21:20001:310730577/Dead, Sxx.xx.xxx.21:20001:310730599/Dead, Sxx.xx.xxx.21:20001:310727545/Dead, Sxx.xx.xxx.21:20001:310733574/Active, Sxx.xx.xxx.21:20001:310732955/Dead, Sxx.xx.xxx.21:20001:310732975/Dead, Sxx.xx.xxx.21:20001:310732993/Dead, Sxx.xx.xxx.21:20001:310733011/Dead, Sxx.xx.xxx.21:20001:310733042/Dead, Sxx.xx.xxx.21:20001:310732810/Dead, Sxx.xx.xxx.21:20001:310732840/Dead, Sxx.xx.xxx.21:20001:310732860/Dead, Sxx.xx.xxx.21:20001:310732894/Dead, Sxx.xx.xxx.21:20001:310732924/Dead, Sxx.xx.xxx.21:20001:310733185/Dead, Sxx.xx.xxx.21:20001:310733217/Dead, Sxx.xx.xxx.21:20001:310733073/Dead, Sxx.xx.xxx.21:20001:310733099/Dead, Sxx.xx.xxx.21:20001:310733123/Dead, Sxx.xx.xxx.21:20001:310733156/Dead, Sxx.xx.xxx.21:20001:310730907/Dead, Sxx.xx.xxx.21:20001:310730941/Dead, Sxx.xx.xxx.21:20001:310730981/Dead, Sxx.xx.xxx.21:20001:310731007/Dead, Sxx.xx.xxx.21:20001:310730756/Dead, Sxx.xx.xxx.21:20001:310730782/Dead, Sxx.xx.xxx.21:20001:310730804/Dead, Sxx.xx.xxx.21:20001:310730827/Dead, Sxx.xx.xxx.21:20001:310730850/Dead, Sxx.xx.xxx.21:20001:310730874/Dead, Sxx.xx.xxx.21:20001:310731077/Dead, Sxx.xx.xxx.21:20001:310732453/Dead, Sxx.xx.xxx.21:20001:310732476/Dead, Sxx.xx.xxx.21:20001:310732501/Dead, Sxx.xx.xxx.21:20001:310732523/Dead, Sxx.xx.xxx.21:20001:310732309/Dead, Sxx.xx.xxx.21:20001:310732336/Dead, Sxx.xx.xxx.21:20001:310732357/Dead, Sxx.xx.xxx.21:20001:310732389/Dead, Sxx.xx.xxx.21:20001:310732415/Dead, Sxx.xx.xxx.21:20001:310732691/Dead, Sxx.xx.xxx.21:20001:310732713/Dead, Sxx.xx.xxx.21:20001:310732744/Dead, Sxx.xx.xxx.21:20001:310732760/Dead, Sxx.xx.xxx.21:20001:310732782/Dead, Sxx.xx.xxx.21:20001:310732553/Dead, Sxx.xx.xxx.21:20001:310732574/Dead, Sxx.xx.xxx.21:20001:310732604/Dead, Sxx.xx.xxx.21:20001:310732626/Dead, Sxx.xx.xxx.21:20001:310732661/Dead, Sxx.xx.xxx.21:20001:310732020/Dead, Sxx.xx.xxx.21:20001:310732277/Dead 

Changes: Sxx.xx.xxx.24:20001:310730805/Dead
Sxx.xx.xxx.24:20001:310730762/Dead
Sxx.xx.xxx.24:20001:310730780/Dead
Sxx.xx.xxx.24:20001:310730860/Dead
Sxx.xx.xxx.24:20001:310730824/Dead
Sxx.xx.xxx.24:20001:310731933/Dead
Sxx.xx.xxx.24:20001:310732164/Dead
Sxx.xx.xxx.24:20001:310732537/Dead
Sxx.xx.xxx.24:20001:310732504/Dead
Sxx.xx.xxx.24:20001:310732690/Dead
Sxx.xx.xxx.24:20001:310733255/Dead
Sxx.xx.xxx.24:20001:310733619/Active
Sxx.xx.xxx.24:20001:310728158/Dead
Sxx.xx.xxx.24:20001:310730606/Dead
Sxx.xx.xxx.24:20001:310730669/Dead
Sxx.xx.xxx.24:20001:310730631/Dead
Sxx.xx.xxx.24:20001:310730648/Dead
Sxx.xx.xxx.24:20001:310730728/Dead
Sxx.xx.xxx.24:20001:310730740/Dead
Sxx.xx.xxx.24:20001:310730689/Dead
Sxx.xx.xxx.24:20001:310730713/Dead
Sxx.xx.xxx.22:20001:310728156/Dead
Sxx.xx.xxx.22:20001:310730535/Dead
Sxx.xx.xxx.22:20001:310730618/Dead
Sxx.xx.xxx.22:20001:310730589/Dead
Sxx.xx.xxx.22:20001:310730563/Dead
Sxx.xx.xxx.22:20001:310730669/Dead
Sxx.xx.xxx.22:20001:310730646/Dead
Sxx.xx.xxx.22:20001:310730739/Dead
Sxx.xx.xxx.22:20001:310730713/Dead
Sxx.xx.xxx.22:20001:310730690/Dead
Sxx.xx.xxx.22:20001:310730492/Dead
Sxx.xx.xxx.22:20001:310731025/Dead
Sxx.xx.xxx.22:20001:310730806/Dead
Sxx.xx.xxx.22:20001:310730786/Dead
Sxx.xx.xxx.22:20001:310730765/Dead
Sxx.xx.xxx.22:20001:310730872/Dead
Sxx.xx.xxx.22:20001:310730851/Dead
Sxx.xx.xxx.22:20001:310730827/Dead
Sxx.xx.xxx.22:20001:310730921/Dead
Sxx.xx.xxx.22:20001:310730892/Dead
Sxx.xx.xxx.22:20001:310730981/Dead
Sxx.xx.xxx.22:20001:310730959/Dead
Sxx.xx.xxx.22:20001:310732588/Dead
Sxx.xx.xxx.22:20001:310732568/Dead
Sxx.xx.xxx.22:20001:310732548/Dead
Sxx.xx.xxx.22:20001:310732665/Dead
Sxx.xx.xxx.22:20001:310732640/Dead
Sxx.xx.xxx.22:20001:310732608/Dead
Sxx.xx.xxx.22:20001:310732730/Dead
Sxx.xx.xxx.22:20001:310732709/Dead
Sxx.xx.xxx.22:20001:310732691/Dead
Sxx.xx.xxx.22:20001:310732792/Dead
Sxx.xx.xxx.22:20001:310732757/Dead
Sxx.xx.xxx.22:20001:310732340/Dead
Sxx.xx.xxx.22:20001:310732320/Dead
Sxx.xx.xxx.22:20001:310732296/Dead
Sxx.xx.xxx.22:20001:310732394/Dead
Sxx.xx.xxx.22:20001:310732373/Dead
Sxx.xx.xxx.22:20001:310732353/Dead
Sxx.xx.xxx.22:20001:310732456/Dead
Sxx.xx.xxx.22:20001:310732436/Dead
Sxx.xx.xxx.22:20001:310732527/Dead
Sxx.xx.xxx.22:20001:310732505/Dead
Sxx.xx.xxx.22:20001:310732485/Dead
Sxx.xx.xxx.22:20001:310732083/Dead
Sxx.xx.xxx.22:20001:310732269/Dead
Sxx.xx.xxx.22:20001:310733611/Active
Sxx.xx.xxx.22:20001:310733108/Dead
Sxx.xx.xxx.22:20001:310733079/Dead
Sxx.xx.xxx.22:20001:310733172/Dead
Sxx.xx.xxx.22:20001:310733157/Dead
Sxx.xx.xxx.22:20001:310733135/Dead
Sxx.xx.xxx.22:20001:310733229/Dead
Sxx.xx.xxx.22:20001:310732854/Dead
Sxx.xx.xxx.22:20001:310732825/Dead
Sxx.xx.xxx.22:20001:310732907/Dead
Sxx.xx.xxx.22:20001:310732879/Dead
Sxx.xx.xxx.22:20001:310732985/Dead
Sxx.xx.xxx.22:20001:310732957/Dead
Sxx.xx.xxx.22:20001:310732936/Dead
Sxx.xx.xxx.22:20001:310733053/Dead
Sxx.xx.xxx.22:20001:310733031/Dead
Sxx.xx.xxx.22:20001:310733014/Dead
Sxx.xx.xxx.23:20001:310733607/Active
Sxx.xx.xxx.23:20001:310733172/Dead
Sxx.xx.xxx.23:20001:310733140/Dead
Sxx.xx.xxx.23:20001:310733114/Dead
Sxx.xx.xxx.23:20001:310733091/Dead
Sxx.xx.xxx.23:20001:310733064/Dead
Sxx.xx.xxx.23:20001:310733243/Dead
Sxx.xx.xxx.23:20001:310732923/Dead
Sxx.xx.xxx.23:20001:310732897/Dead
Sxx.xx.xxx.23:20001:310732872/Dead
Sxx.xx.xxx.23:20001:310732843/Dead
Sxx.xx.xxx.23:20001:310732823/Dead
Sxx.xx.xxx.23:20001:310732803/Dead
Sxx.xx.xxx.23:20001:310733045/Dead
Sxx.xx.xxx.23:20001:310733025/Dead
Sxx.xx.xxx.23:20001:310733001/Dead
Sxx.xx.xxx.23:20001:310732973/Dead
Sxx.xx.xxx.23:20001:310732940/Dead
Sxx.xx.xxx.23:20001:310730866/Dead
Sxx.xx.xxx.23:20001:310730844/Dead
Sxx.xx.xxx.23:20001:310730825/Dead
Sxx.xx.xxx.23:20001:310730802/Dead
Sxx.xx.xxx.23:20001:310730781/Dead
Sxx.xx.xxx.23:20001:310730756/Dead
Sxx.xx.xxx.23:20001:310730971/Dead
Sxx.xx.xxx.23:20001:310730924/Dead
Sxx.xx.xxx.23:20001:310730906/Dead
Sxx.xx.xxx.23:20001:310730889/Dead
Sxx.xx.xxx.23:20001:310732669/Dead
Sxx.xx.xxx.23:20001:310732646/Dead
Sxx.xx.xxx.23:20001:310732620/Dead
Sxx.xx.xxx.23:20001:310732586/Dead
Sxx.xx.xxx.23:20001:310732553/Dead
Sxx.xx.xxx.23:20001:310732775/Dead
Sxx.xx.xxx.23:20001:310732748/Dead
Sxx.xx.xxx.23:20001:310732729/Dead
Sxx.xx.xxx.23:20001:310732709/Dead
Sxx.xx.xxx.23:20001:310732691/Dead
Sxx.xx.xxx.23:20001:310732525/Dead
Sxx.xx.xxx.23:20001:310732501/Dead
Sxx.xx.xxx.23:20001:310732476/Dead
Sxx.xx.xxx.23:20001:310732439/Dead
Sxx.xx.xxx.23:20001:310732161/Dead
Sxx.xx.xxx.23:20001:310730610/Dead
Sxx.xx.xxx.23:20001:310730580/Dead
Sxx.xx.xxx.23:20001:310730558/Dead
Sxx.xx.xxx.23:20001:310730525/Dead
Sxx.xx.xxx.23:20001:310730732/Dead
Sxx.xx.xxx.23:20001:310730709/Dead
Sxx.xx.xxx.23:20001:310730686/Dead
Sxx.xx.xxx.23:20001:310730665/Dead
Sxx.xx.xxx.23:20001:310730644/Dead
Sxx.xx.xxx.23:20001:310727543/Dead
Sxx.xx.xxx.21:20001:310729727/Dead
Sxx.xx.xxx.21:20001:310730485/Dead
Sxx.xx.xxx.21:20001:310730624/Dead
Sxx.xx.xxx.21:20001:310730648/Dead
Sxx.xx.xxx.21:20001:310730666/Dead
Sxx.xx.xxx.21:20001:310730689/Dead
Sxx.xx.xxx.21:20001:310730708/Dead
Sxx.xx.xxx.21:20001:310730729/Dead
Sxx.xx.xxx.21:20001:310730521/Dead
Sxx.xx.xxx.21:20001:310730555/Dead
Sxx.xx.xxx.21:20001:310730577/Dead
Sxx.xx.xxx.21:20001:310730599/Dead
Sxx.xx.xxx.21:20001:310727545/Dead
Sxx.xx.xxx.21:20001:310733574/Active
Sxx.xx.xxx.21:20001:310732955/Dead
Sxx.xx.xxx.21:20001:310732975/Dead
Sxx.xx.xxx.21:20001:310732993/Dead
Sxx.xx.xxx.21:20001:310733011/Dead
Sxx.xx.xxx.21:20001:310733042/Dead
Sxx.xx.xxx.21:20001:310732810/Dead
Sxx.xx.xxx.21:20001:310732840/Dead
Sxx.xx.xxx.21:20001:310732860/Dead
Sxx.xx.xxx.21:20001:310732894/Dead
Sxx.xx.xxx.21:20001:310732924/Dead
Sxx.xx.xxx.21:20001:310733185/Dead
Sxx.xx.xxx.21:20001:310733217/Dead
Sxx.xx.xxx.21:20001:310733073/Dead
Sxx.xx.xxx.21:20001:310733099/Dead
Sxx.xx.xxx.21:20001:310733123/Dead
Sxx.xx.xxx.21:20001:310733156/Dead
Sxx.xx.xxx.21:20001:310730907/Dead
Sxx.xx.xxx.21:20001:310730941/Dead
Sxx.xx.xxx.21:20001:310730981/Dead
Sxx.xx.xxx.21:20001:310731007/Dead
Sxx.xx.xxx.21:20001:310730756/Dead
Sxx.xx.xxx.21:20001:310730782/Dead
Sxx.xx.xxx.21:20001:310730804/Dead
Sxx.xx.xxx.21:20001:310730827/Dead
Sxx.xx.xxx.21:20001:310730850/Dead
Sxx.xx.xxx.21:20001:310730874/Dead
Sxx.xx.xxx.21:20001:310731077/Dead
Sxx.xx.xxx.21:20001:310732453/Dead
Sxx.xx.xxx.21:20001:310732476/Dead
Sxx.xx.xxx.21:20001:310732501/Dead
Sxx.xx.xxx.21:20001:310732523/Dead
Sxx.xx.xxx.21:20001:310732309/Dead
Sxx.xx.xxx.21:20001:310732336/Dead
Sxx.xx.xxx.21:20001:310732357/Dead
Sxx.xx.xxx.21:20001:310732389/Dead
Sxx.xx.xxx.21:20001:310732415/Dead
Sxx.xx.xxx.21:20001:310732691/Dead
Sxx.xx.xxx.21:20001:310732713/Dead
Sxx.xx.xxx.21:20001:310732744/Dead
Sxx.xx.xxx.21:20001:310732760/Dead
Sxx.xx.xxx.21:20001:310732782/Dead
Sxx.xx.xxx.21:20001:310732553/Dead
Sxx.xx.xxx.21:20001:310732574/Dead
Sxx.xx.xxx.21:20001:310732604/Dead
Sxx.xx.xxx.21:20001:310732626/Dead
Sxx.xx.xxx.21:20001:310732661/Dead
Sxx.xx.xxx.21:20001:310732020/Dead
Sxx.xx.xxx.21:20001:310732277/Dead

**Comment by ReubenBond** [comment] 2019-11-06 19:39
Thanks for the detail, @claycass17 
Looking at the Consul membership table code, it looks like the issue is there: the Consul implementation doesn't support versioning, but membership relies on monotonic versioning to function correctly.

This needs to be fixed before it will be usable.

I believe the correct fix for this is to change the provider to use transactions instead of simple CAS operations. Inside the transaction, perform two CAS: one on a "Version" KV pair and one on the entry KV  pair. This is what the Azure Table Storage provider does.

I have opened #6095 to fix this. Could you please verify that this resolves your problem via a nightly build (once that PR is merged), @claycass17?

**Comment by claycass17** [comment] 2019-11-07 09:58
Thank you for following up with this issue and your quick response. Is there a plan to release this update in .Net Core 2.2 following version of orleans 2.4.3 as master is .Net Core 3 so we can't really test it.

**Comment by SebastianStehle** [comment] 2019-11-07 13:04
What is the current status of membership? Is the monotonic versioning required now? There are other providers who do not support it yet.

**Comment by sergeybykov** [comment] 2019-11-07 17:51
>What is the current status of membership? Is the monotonic versioning required now? There are other providers who do not support it yet.

[It was required for a long time](http://dotnet.github.io/orleans/Documentation/implementation/cluster_management.html#extension-to-totally-order-membership-views). However, violations of this requirements previously didn't lead to any observable issues. Now they do. We need to update all providers to implement this.

**Closed** 2019-11-07 17:52 UTC

**Comment by ReubenBond** [comment] 2019-11-07 18:00
I opened issues to track the remaining providers:

* MongoDB: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/issues/71
* DynamoDB: #6099

**Comment by SebastianStehle** [comment] 2019-11-07 20:37
It would be great if you could make your tests public, so that there is an easy way to write automated integration tests for them.

**Comment by claycass17** [comment] 2019-11-08 08:44
@ReubenBond is there a possibility this update is done on top of version 2.4.3?

**Comment by sergeybykov** [comment] 2019-11-08 16:42
>is there a possibility this update is done on top of version 2.4.3?

Yes, we definitely need to release 2.4.4 with these fixes.
