### ISSUE TITLE
[4.0] Code Generator sometimes hangs and does not work with Benchmark.NET

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#7592] opened 2022-02-20 10:21 UTC
I have the impression that sometimes the code generator just hangs. I have made this experience in the following branch: https://github.com/OrleansContrib/OrleansDashboard/pull/351

The build just stops and takes forever (or until I stop it). I do not have this issue with other (much larger) projects. Only in the Dashboard project.

Furthermore I cannot get Benchmark.NET to run, it also fails to build.

**Comment by ReubenBond** [comment] 2022-02-20 16:05
How are you building and running this? For what it's worth, I've never seen the code generator hang

**Comment by SebastianStehle** [comment] 2022-02-20 16:09
Just CTRL+F5 (Benchmark.NET) or F5 for the normal dashboard. I use Visual Studio 2022 and it hangs forever. I have forgotten to turn it off and it was still running after I cam back from lunch an hour later.

**Comment by ReubenBond** [comment] 2022-02-20 16:12
I'm building the ring-buffers branch, which fails for other reasons (package downgrade to 3.4.0, unknown `IISi` type, etc). Should I be building the 4.0 branch instead? I can also push some fixes to your branch.

**Comment by ReubenBond** [comment] 2022-05-20 18:00
I wonder if this is somehow related to https://github.com/dotnet/orleans/issues/7751

**Comment by asos-stefanzilik** [comment] 2023-02-28 17:42
I'm also getting error when running Benchmark.Net with Microsoft.Orleans.Server 7.1.0

Standard error:
 MSBuild version 17.4.0+18d5aef85 for .NET
C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\85cad078-2b6b-43f5-86ca-0859a3d311df.orleans.g.cs(9,93): error CS0118: 'OrleansCodeGen' is a namespace but is used like a type [C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\BenchmarkDotNet.Autogenerated.csproj]
C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\85cad078-2b6b-43f5-86ca-0859a3d311df.orleans.g.cs(9,110): error CS0103: The name 'cad0782b6b43f586ca0859a3d311df' does not exist in the current context [C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\BenchmarkDotNet.Autogenerated.csproj]
C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\85cad078-2b6b-43f5-86ca-0859a3d311df.orleans.g.cs(9,12): error CS1729: 'TypeManifestProviderAttribute' does not contain a constructor that takes 3 arguments [C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\BenchmarkDotNet.Autogenerated.csproj]
Build FAILED.
C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\85cad078-2b6b-43f5-86ca-0859a3d311df.orleans.g.cs(9,93): error CS0118: 'OrleansCodeGen' is a namespace but is used like a type [C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\BenchmarkDotNet.Autogenerated.csproj]
C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\85cad078-2b6b-43f5-86ca-0859a3d311df.orleans.g.cs(9,110): error CS0103: The name 'cad0782b6b43f586ca0859a3d311df' does not exist in the current context [C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\BenchmarkDotNet.Autogenerated.csproj]
C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\85cad078-2b6b-43f5-86ca-0859a3d311df.orleans.g.cs(9,12): error CS1729: 'TypeManifestProviderAttribute' does not contain a constructor that takes 3 arguments [C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df\BenchmarkDotNet.Autogenerated.csproj]
    0 Warning(s)
    3 Error(s)
Time Elapsed 00:00:01.93

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in C:\code\Asos.Sf.SampleApp\Asos.Sf.SampleApp.Benchmarks\bin\Release\net7.0\85cad078-2b6b-43f5-86ca-0859a3d311df
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html

**Comment by ReubenBond** [comment] 2023-02-28 18:02
This looks like a version mismatch, @asos-stefanzilik. Are you able to provide more information? This seems to be the same error that @YAJeff ran into in #8311

**Comment by YAJeff** [comment] 2023-02-28 18:19
Yep. Same one. Working on isolating within a repo.

**Comment by asos-stefanzilik** [comment] 2023-03-06 17:07
Hi @ReubenBond min code https://github.com/asos-stefanzilik/BenchmarkOrleansCodeGenIssueRepro, let me know if you can repro

**Comment by asos-stefanzilik** [comment] 2023-03-07 17:40
Thank you @ReubenBond , I've tested your fix and the error is gone, although now I'm getting a different error (using your PR branch) - that it can't find Grain interface implementation. No idea if it's related to your changes, or other changes in the repo.

Assuming your fix works and gets approved, would this be released with .Net 8, or could it be incorporated earlier as a minor patch?

**Comment by ReubenBond** [comment] 2023-03-07 17:46
Ah, right, I forgot to tell you: you forgot the host.Start() call.
We'll release the fix earlier (soon).

**Comment by asos-stefanzilik** [comment] 2023-03-07 19:05
@ReubenBond yes that's true, I also forgot to inherit the BenchmarkGrain (from) : Grain class, however I've fixed all these (before asking, checked in the repro repo) and still get the issue. It seems like the issue is not related to invoking Orleans in context of BenchmarkNet, even direct invocation reports the the same problem (could be just some other changes in Orleans in progress)

Soon sounds great

**Closed** 2023-03-07 23:28 UTC
Labels: Needs: triage :mag:
