### ISSUE TITLE
intermittent failures of Rem_Azure_GT_1F1J_MultiGrain

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#4319] opened 2018-03-27 20:32 UTC
https://orleans.visualstudio.com/Orleans/_TestManagement/Runs?_a=resultSummary&runId=4144&resultId=101129
>Error message
Orleans.Runtime.OrleansMessageRejectionException : Forwarding failed: tried to forward message Request S127.0.0.1:27480:259533019*cli/c5a628a4@ac0793a9->S127.0.0.1:27480:259533019*grn/60DF7002/9f44629c@07e6ffa6 #7449[ForwardCount=2]: for 2 times after Non-existent activation to invalid activation. Rejecting now. 
Stack trace
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d`1.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.Core\Async\TaskExtensions.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at UnitTests.TimerTests.ReminderTests_Base.<PerCopyGrainFailureTest>d__25.MoveNext() in D:\build\agent\_work\18\s\test\TesterInternal\TimerTests\ReminderTests_Base.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.OrleansTaskExtentions.<WithTimeout>d__16.MoveNext() in D:\build\agent\_work\18\s\src\Orleans.Core\Async\TaskExtensions.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Tester.AzureUtils.TimerTests.ReminderTests_AzureTable.<Rem_Azure_GT_1F1J_MultiGrain>d__16.MoveNext() in D:\build\agent\_work\18\s\test\TesterAzureUtils\Reminder\ReminderTests_AzureTable.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by benjaminpetit** [comment] 2018-03-27 23:19
I think the issue is that a silo is in its shutdown sequence, and the test is trying to access to a grain that lives on it. We know that we have some issue during this process, I am pretty sure they are related

**Comment by ReubenBond** [comment] 2021-09-03 19:43
Closing all test reliability issues. Test reliability has improved substantially. We can re-open for any test reliability issues which we still see.

**Closed by ReubenBond** 2021-09-03 19:43 UTC
Labels: test-issue
