### ISSUE TITLE
Publishers grains not unregistered from streams on grain deactivation

### ISSUE THREAD

**Issue by clovos** [dotnet/orleans#6404] opened 2020-03-17 10:12 UTC
Hey! During some loadtest with our Orleans setup I've noticed issues with our Streams. I've noticed that we get dead stream entries in our database with 1 producer registered even though the producer grain have gone to sleep. This would also explain why we have a lot of dead streams in our live environment database(+100 000)
Is this a known issue or are we configuring our producers incorrect somehow?

Our Setup:
Orleans 3.0.2
We're using SimpleStreamProvider
Our stream database is DynamoDB.
Steam database option DeleteStateOnClear is set to true.
We don't use grain-to-grain streams only grain-to-client which means we can potentially kill the stream database between server restarts since we do register/unregister during the player sessions on the client and on the silos we fetch streams on grain activation.

This is how I've understand the producer workflow:

-On grain activation you should user GetStream from the provider which would register the grain as a producer to the stream. We then cache it in memory for when we want to publish.

-When you want to publish you call OnNextAsync on the cached stream.

-When a grain goes to sleep it should unregister the producer automatically on all the streams that contains the grain as a producer.

-When Silo shutdowns gracefully it will unregister all grains from the streams that is loaded into memory.

Is there something we're doing wrong or something that we've missed in this workflow?

**Comment by sergeybykov** [comment] 2020-03-24 02:50
>-When a grain goes to sleep it should unregister the producer automatically on all the streams that contains the grain as a producer.

I think this is the wrong expectation. When a grain gets deactivated, nothing about it gets unregistered, by design. When a new consumer subscribes to a stream that that grain was a producer for, it will get reactivated to register (under the covers) the new consumer.

**Comment by clovos** [comment] 2020-03-24 09:50
Thank you for the answer @sergeybykov !
If this is the case then is it by design that entries will stored forever in the database if the stream only have a producer registered? 
In our case if a player don't log in again then the stream will never be used and therefore be stuck forever in the database.
When exactly is producers removed from the stream persistent data? There is no manual way to unregister a producer currently.

**Comment by jason-bragg** [comment] 2020-03-24 21:27
I think Sergey was thinking of the consumer side rather than the producer side.  Consumer subscriptions exist until the consumer unsubscribes, even over multiple activation.  Producers remain only as long as the producer grain is active.  Should a producer fail to unregister as a producer of the stream, it will be reactivated on any subscription change on that stream, and that behavior may be used to help detect and clean up dead producers, but such was not the intention.

Your understanding is mostly accurate.  Outside of ungraceful shutdown or errors, under your configuration dead producers shouldn't remain in storage.  Some minor corrections and details below:

> On grain activation you should user GetStream from the provider which would register the grain as a producer to the stream. We then cache it in memory for when we want to publish.

GetStream  just gets the stream, it doesn't register it for production or consumption, until those activities occur.  It registers as a producer on the first OnNextAsync call, and registers as a consumer during the SubscribeAsync call.

> When a grain goes to sleep it should unregister the producer automatically on all the streams that contains the grain as a producer.

When a grain is deactivated, it unregisters itself as a producer of any stream it has produced on.  This operation is best effort and will not generate application errors, retry or stop deactivation if it fails.  It will, however, generate a warning in the logs "Ignoring unhandled exception during PubSub.UnregisterProducer".

- Are you seeing unregister producer warnings?

**Comment by clovos** [comment] 2020-03-25 10:15
Thanks for the clarifications @jason-bragg, this is very helpful indeed!
I do see these warning from time to time in our live environment and in the loadtest session but the amount of logs did not match the amount of dead streams in the database in the loadtest. But this is a lead for sure. 
So when is the different scenarios that the best effort deactivation fails?

**Comment by jason-bragg** [comment] 2020-03-25 18:53
> So when is the different scenarios that the best effort deactivation fails?

All grain deactivation is best effort, and may not even occur in the case of non-graceful shutdown.

As for why the producer unregister fails, I suggest checking the exception reported in the warning.  From my experience, this is most often caused by grain timeout (PubSubRendezvousGrain) during upgrades, or storage errors.

I've seen these occur most often during silo shutdown, because we've no ordering of grain deactivation, so if the PubSubRendezvousGrain is shutdown before the unregister is made, it would need be reactivated on another silo for the unregister to call to work.  If this is the last silo in the cluster during a shutdown, then there is no way to reactive it and the operation will fail.  Further if there are a great many of these, it can overload storage from the burst of storage calls during shutdown.

In any case, I'd look at the exceptions logged in the warning, as they're the best info I'm aware of to root cause this.

**Comment by sergeybykov** [comment] 2020-03-31 02:30
@clovos Sorry about the confusion! Can we close this now?

**Comment by clovos** [comment] 2020-03-31 07:33
Thanks again for the answers. I've been out sick for a few days. I do like thinking that our ungraceful shutdowns is the reason to why it happens but these dead stream entries I got in the loadtest did not involve any silo restarts and still had streams in the database with a single producer registered in the stream even tho all the player grains who was the producer had gone to sleep. In our live environment what you're saying is for sure a problem. We don't have graceful shutdowns currently since we've not manage to set it up in our AWS instance auto scaling groups. I will look into setting up graceful silo shutdown. Any ideas of how to do this on a linux instance machine without a Ctrl-C key solution that the documentation suggested?

**Comment by jason-bragg** [comment] 2020-03-31 18:05
> Any ideas of how to do this on a linux instance machine without a Ctrl-C key solution that the documentation suggested?

@ReubenBond, @benjaminpetit, you all have any experience with this?

**Comment by ReubenBond** [comment] 2020-03-31 18:52
If you use the generic host (Microsoft.Extensions.Hosting) then you can get the console lifetime. It's there by default if you create your host using Host.CreateDefaultBuilder().

Whatever solution you use, there has to be some signal from the infrastructure (typically, SIGINT, which is what Ctrl+c sends) that tells your service to please shut down.

With the hosting package, you can implement your own lifetimes which are more infrastructure-aware and know when to initiate a shutdown

**Comment by clovos** [comment] 2020-04-01 15:28
Alright I will look into trying to send a SIGINT command with AWS documents, thanks!

**Closed** 2020-09-26 23:44 UTC
