### ISSUE TITLE
Custom dependency injection IServiceProvider broken in v1.4.1 (was working in v1.3.1)

### ISSUE THREAD

**Issue by Quicksilvr-** [dotnet/orleans#3072] opened 2017-05-31 20:22 UTC
Hi there.

I've found a bug in **v1.4.1** whereby custom **IServiceProvider** implementations have been broken. It appears as if the custom service provider, returned from the **ConfigureServices()** method in the app startup class, is simply being ignored, as the type of the service provider available later in the application is the default service provider type.

Please see the attached .zip containing two versions of the same console app, one using Orleans v.1.3.1 (which works fine) and the other using v1.4.1 (broken).

Thanks for a great project.
Q

PS. I haven't tested with any later/dev version, only these two versions.

[CustomServiceProviderBug.zip](https://github.com/dotnet/orleans/files/1042773/CustomServiceProviderBug.zip)

**Comment by attilah** [comment] 2017-05-31 23:09
Hello @Quicksilvr- !

Thanks for providing the repro and the issue. We were aware of a similar issue.

The root cause of this change, which seems to be a breaking change is that in 1.3.1 we did not utilized the DI container as much as we do in 1.4.1 it was a multi step change for us.

It is not that we're serving a different ```IServiceProvider``` instance. When you're doing ```services.BuildServiceProvider();``` the default container is being built up, which cannot supply your own ```IServiceProvider``` instance, since there is no connection and that does not exist.

On the other hand when I fixed your repro to make it work in a suggested way we found out that 2 of our ctors can cause conflicts with other DI implementation, because of how ctors are picked. These fixes are in https://github.com/dotnet/orleans/pull/3075 and will be part of the 1.4.2 release, which is coming quite soon.

I've attached a fixed 1.4.1 repro, which will work with 1.4.2 after release or you can build it for yourself based on that PR above.

Beware that if you receive a MethodNotFoundException for the ```With'`` method in the startup class, that is a missing binding redirect between the ```DryIoc.Microsoft.DependencyInjection``` and the ```DryIoc.dll``` package.

[CustomServiceProviderBug1.4.1.zip](https://github.com/dotnet/orleans/files/1043151/CustomServiceProviderBug1.4.1.zip)


- Attila

**Closed by attilah** 2017-05-31 23:09 UTC

**Comment by Quicksilvr-** [comment] 2017-06-01 05:44
Thanks for the quick turnaround and the updated example. I'll grab 1.4.2 as soon as it is released, so I can get rid of my hacky workaround code.

It's useful to be able to inject data access services during initialisation of custom storage providers, which is why I need a container that does not follow the build->readonly pattern. And of course it's a bonus that DryIoc is one of the [fastest, fully featured containers out there](http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison).

Hope you have a great day.
