### ISSUE TITLE
Reminder dueTime limitation has to be longer than 50 days

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1298] opened 2016-01-19 04:02 UTC
Currently reminder can't be later than 49 (max TimeSpan is `49 days 17:02:47.2940000`) days from a creation time. There is a hard-coded limit in ReminderRegistry.cs

```
 internal class ReminderRegistry : IReminderRegistry
    {
        private const UInt32 MAX_SUPPORTED_TIMEOUT = (uint)0xfffffffe;

        public Task<IGrainReminder> RegisterOrUpdateReminder(string reminderName, TimeSpan dueTime, TimeSpan period)
        {
            // Perform input volatility checks that are consistent with System.Threading.Timer
            // http://referencesource.microsoft.com/#mscorlib/system/threading/timer.cs,c454f2afe745d4d3,references
            var dueTm = (long)dueTime.TotalMilliseconds;
            if (dueTm < -1)
                throw new ArgumentOutOfRangeException("dueTime", "Cannot use negative dueTime to create a reminder");
            if (dueTm > MAX_SUPPORTED_TIMEOUT)
                throw new ArgumentOutOfRangeException("dueTime", String.Format("Cannot use value larger than {0} for dueTime when creating a reminder", MAX_SUPPORTED_TIMEOUT));
...

```

which references back to .NET [Timer implementation limitations here](http://referencesource.microsoft.com/#mscorlib/system/threading/timer.cs,c454f2afe745d4d3,references)

But this doesn't make sense to use limitations of a timer which is CPU\Host bound for reminders.

Implementation should allow longer TimeSpans so this functionality can be used for scheduling.

Also there is a limitation for a negative TimeSpan - it'd be nice that if timespan is negative - reminder reminds immediately, instead of throwing errors - this will make RegisterOrUpdateReminder more consistent - user's code doesn't need to check reminders spans, just schedule it as is and accept Runtime's default behaviour

**Comment by gabikliot** [comment] 2016-01-19 05:39
The upper limit comes from the way we currently implement it. We currently create a Timer per reminder. Originally we were not checking upon creation in this place, and it would throw later on, deep in the reminder service, which was harder to debug.
So if one would to change this limit, he will need to adjust the implementation. Same goes with negative.
So yes, I am in favor of removing the upper limitation, but need to implement them all the way down, including test that show it works.

As for negative, I am not sure I agree. Reminders are trying to mimic .NET Timers, which have this limitation: zero is immediate, negative is not allowed. I think its better to be consistent.

**Comment by centur** [comment] 2016-01-19 05:57
Not insisting on negative value handling, this just means that this duty is being moved to user code and everywhere it needs to check that set of parameters is satisfying current "Reminder constrains" and it exposes concrete implementation details, which is umm.. usually not a good thing to have.

From a least surprise perspective - I'd expect that Orleans Timer mimics .NET Timer behaviour, but not a Reminder, which suppose to be very long running and expected to behave differently (otherwise - what's the responsibility of reminder if we have Timers which are umm - exactly like .NET Timers).

**Comment by gabikliot** [comment] 2016-01-20 05:07
Ye... I am less opinionated about the negative value. It can work both ways. 
Supporting larger than MAX value is a non trivial modification in the service implementation I think. But you can give it a try.

**Comment by jkonecki** [comment] 2018-05-06 21:14
This is a real PITA ;-)
Any chances of bumping the priority?

**Comment by Shrn-Prmshr** [comment] 2018-10-02 08:46
Honestly, I can not understand the reason back of this limitation. But I will be so happy if someone can explain it in more details. Maybe it is a wrong thinking to have more than 50 days for reminder and this is exactly what I need to know more about.

**Comment by jkonecki** [comment] 2018-10-02 10:47
I believe the limitation is a purely technical one - if I remember correctly there is a maximum timespan a windows Timer can be set to and Reminders follow the same.
The workaround is to set the reminder to 49 days and when triggered revalidate if they are triggering on the desired time. If not, reset them for the remaining period or 49 days.

**Comment by sergeybykov** [comment] 2018-10-02 15:46
The code points to the reason in .NET's timer.cs - http://referencesource.microsoft.com/#mscorlib/system/threading/timer.cs,c454f2afe745d4d3,references. We could do better than that, of course. Just haven't implemented it yet.

**Comment by sergeybykov** [comment] 2018-10-02 20:31
>@sergeybykov do you have any plan for this update?

No concrete plans yet. We consider this a low priority issue, as it is easy (and I think better) to schedule a reminder to fire more frequently, e.g. daily or weekly, and check if the needed time period has passed. 

Otherwise, if you set a reminder for, say, 6 months, and on that minute when it was scheduled to fire the cluster was down, that reminder will not fire for another 6 months, which is probably not what you want. I think it's better to have it fire weekly/daily and check if 6 months have passed.

**Comment by Shrn-Prmshr** [comment] 2018-10-02 21:01
Actually users are responsible for setting up this reminder timespan and this means they don't know about existence of Orleans and I am trying to not write any kind of Orleans related logic in our logic.
Exactly I did the similar approach. I check and if it is more than 50 days I set reminder time to 49 days instead and continue to finish the requested period.

**Comment by jkonecki** [comment] 2018-10-03 07:15
> Otherwise, if you set a reminder for, say, 6 months, and on that minute
when it was scheduled to fire the cluster was down, that reminder will not
fire for another 6 months, which is probably not what you want. I think
it's better to have it fire weekly/daily and check if 6 months have passed.

Oh, this is quite an unexpected behaviour. Is this documented?
I would hazard saying that most would expect the reminder to fire as soon
as cluster is up...

**Comment by jkonecki** [comment] 2018-10-03 17:05
Wouldn't a FiredTimestamp column be enough?
I don't have a full understanding of how reminders are implemented so
please forgive a naive solution.

**Comment by sergeybykov** [comment] 2018-10-08 17:58
>Wouldn't a FiredTimestamp column be enough?

That's what I meant by "it would require recording in storage every delivered reminder" - we'd have to update that timestamp upon every reminder tick.

**Comment by IhnatKlimchuk** [comment] 2019-06-21 19:48
Is there any updates or plans regarding this?

**Comment by sergeybykov** [comment] 2019-07-15 19:50
>Is there any updates or plans regarding this?

None at the moment.

**Comment by jkonecki** [comment] 2019-07-15 21:08
Sergey, if the fix is straightforward than, given some guidance, I could
work on this one. I feel the pain in my current project and would love to
get it fixed.

Jakub

**Comment by sergeybykov** [comment] 2019-07-15 21:58
@jkonecki That would be much appreciated! My recollection is that it is constrained by the `MaxValue` of `Timer`. Shouldn't too hard to account for that I hope.

**Comment by jkonecki** [comment] 2019-07-16 11:28
I'm still on 1.5 branch. Can I make the changes there and than port them to
2.x? Or should I work on 2.x directly?

**Comment by sergeybykov** [comment] 2019-07-16 15:44
All new development is done in `master' (2.x) and only select changes get backported to 1.5 patches. So it is better to make the change in `master`.

**Comment by ReubenBond** [comment] 2023-12-10 05:40
Fixed by https://github.com/dotnet/orleans/pull/6342

**Closed by ReubenBond** 2023-12-10 05:40 UTC
Labels: enhancement, Needs: documentation 📄, help wanted, hacktoberfest
