### ISSUE TITLE
[2.0]Fatal problem，Urgently ask the author for help

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4526] opened 2018-04-28 13:50 UTC
A serious problem occurred today, the client could not connect to Host.
System：windows server 2012
Cluster： stand-alone
Client connection error：

The first problem：
`System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/e3c929ba@fc95d3ad->S127.0.0.1:30000:0*grn/388429D6/00000000 #6: . Target History is: <S127.0.0.1:30000:0:*grn/388429D6/00000000:>.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`

The second problem：
`Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message NewPlacement Request S127.0.0.1:11111:262617005*cli/bdae729e@1c7fab88->S127.0.0.1:11111:262617005*grn/388429D6/00000000@757c0c9a #112[ForwardCount=2]:  for 2 times after Duplicate activation to invalid activation. Rejecting now. 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task   at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d_1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Zop.PaymentGateway.Application.TradePreCreateService.<PreCreate>d__3.MoveNext()`

**Comment by aqa510415008** [comment] 2018-04-28 13:53
Found a problem, I have been reporting errors while using OrleansDashboard.
![bxetiz rc0e etbnk hoi6n](https://user-images.githubusercontent.com/28291464/39397244-9f3a6486-4b2e-11e8-9d2d-f1da18eb31e0.png)

**Comment by ReubenBond** [comment] 2018-04-29 01:24
@aqa510415008 could you please provide us with more information, such as which clustering plugin you are using as well as logs. How many silos do you have? Are the clients on the same network as the silos?

**Comment by claylaut** [comment] 2018-04-30 11:00
@ReubenBond There is already an issue opened for this, with more details:
https://github.com/dotnet/orleans/issues/4505

This seems duplicate.

**Comment by ReubenBond** [comment] 2018-04-30 22:57
Lets close this as a duplicate of #4505 then - until we know otherwise. I've assigned myself to #4505

**Closed by ReubenBond** 2018-04-30 22:57 UTC
