### ISSUE TITLE
FactoryAttribute is internal

### ISSUE THREAD

**Issue by andre-realroi** [dotnet/orleans#711] opened 2015-08-18 16:54 UTC
Based on the documentation kindly provided by @gabikliot (http://dotnet.github.io/orleans/Advanced-Concepts/Two-Way-Client-Observers), one is instructed to use `[Factory(FactoryAttribute.FactoryTypes.ClientObject)]`, however that is not possible as it's `internal`.

Shouldn't the class `FactoryAttribute` be made `public`?

**Comment by gabikliot** [comment] 2015-08-18 17:52
I looked at that. The issue is actually more subtle than just making `FactoryAttribute` public. Just making `FactoryAttribute` public will not suffice to enable two way client objects. We will also need to add another method to `IGrainFactory` or change the way observers work.
Stepping back, this is not just making one attribute public, it is about providing **a new abstraction** - a new public concept of "two way client addressable object". It might be a new type of interface that extends `IGrain` or maybe something else.
We had something internal that we used for that purpose, but as long as it was not part of the public abstraction, we did not need to worry how it looks or how it aligns with all the other abstractions. We will need to deeply revisit this now.

Also, the description I put [here](http://dotnet.github.io/orleans/Advanced-Concepts/Two-Way-Client-Observers) about tow way client object is obviously wrong: it won't work without changing the `IGrainFactory`.

Therefore, for now, I will remove the description.
I think we can close this issue and instead  open a new feature request about "allowing two way RPC from grains to clients".

**Closed** 2015-08-18 17:56 UTC
Labels: enhancement
