### ISSUE TITLE
Unexpected token '100' introducing type specifier

### ISSUE THREAD

**Issue by justmara** [dotnet/orleans#4593] opened 2018-05-15 06:57 UTC
We're getting strange error from our web app that uses Orleans.Client. The strange thing is that app works, it calls Orleans cluster and gets response, but spikes to ~50% cpu every 5 minutes and writes this error to log every second or so.
```
Unable to connect to silo "System.Runtime.Serialization.SerializationException: Unexpected token '100' introducing type specifier
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.DeserializeBody(SerializationManager serializationManager, List`1 bytes)
   at Orleans.Runtime.Message.GetDeserializedBody(SerializationManager serializationManager)
   at Orleans.Runtime.GrainReference.ResponseCallback(Message message, TaskCompletionSource`1 context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<StartInternal>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<Start>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.ClusterClient.<Connect>d__24.MoveNext()
```

**Comment by sergeybykov** [comment] 2018-05-15 17:39
Which version of Orleans is this? Any chance of a version mix somewhere?

**Comment by ReubenBond** [comment] 2018-05-15 21:36
Linking #3883 in case they are the same issue

**Comment by sujesharukil** [comment] 2018-05-30 04:19
Something to add... it definitely seems like something to do with large data being passed. Just encountered it but with a different token ```Unexpected token '58' introducing type specifier```. The interesting thing is, this happens for us when we do a Task.WhenAll on multiple task and a collective size of the data being passed is very large. Separating the calls with individual awaits, seems to not cause this issue.

**Comment by ReubenBond** [comment] 2018-08-14 03:48
Closing as a duplicate of #3883, let's use that to track.

**Closed** 2018-08-14 05:01 UTC
Labels: P2, bug
