### ISSUE TITLE
Client Observer Reference doesn't work on second silo

### ISSUE THREAD

**Issue by brianqcgames** [dotnet/orleans#2519] opened 2016-12-14 23:11 UTC
This is behavior I am seeing in 1.3.1

Setup:
I am running 2 silos using zookeeper for membership
I am running 1 client using zookeeper for gateway discovery
I see in the logs that both silos record the open socket from the client
A grain (TestGrain) is created that holds an observer reference to an object in the client. The grain is usually created in silo 1 because of timing.
The grain is persisting the reference to redis for temporary storage.
I kill silo 1 (or whatever silo is holding the TestGrain object).
If the client re-activates TestGrain the state appears to be properly re-created from redis including the observer reference.
If TestGrain then tries to send a notification to the client using the observer reference it will sometimes fail with the error: 
Discarding OneWay rejection for message OneWay S127.0.0.1:11112:219365805*grn/E5E4FD49/00000000@4a6885bf->*cli/d85ac3a0f126053a-7b70-462e-8ac5-a2d8ffd9a2e5 #178: global::QCServicesGrainInterfaceLibrary.ITestGrainObserver:OnSimpleNotification(). Exc = No activation for client *cli/d85ac3a0

What is strange is it doesn't always fail and I can't find a consistent way to make it fail. My hypothesis is that it fails when the silo that was the "first" silo a client connects to is the one that was shut down but I can't reliably produce that scenario or tell it is actually happening because I am not sure how the client gateway connections work.

**Comment by brianqcgames** [comment] 2016-12-14 23:12
Tagging @benjaminpetit  as Sergey mentioned he was looking at client-gateway communication recently.

**Comment by benjaminpetit** [comment] 2016-12-16 00:17
Do you shutdown `Silo 1` properly, or do you kill it?

I think it will happen if `Silo 1` was the owner of the `GrainDirectoryPartition`: when this silo is killed, this partition is lost. I am not sure that a client-gateway communication could help here.

Could you provide a unit test for this? If not I will try to add one.

**Comment by brianqcgames** [comment] 2016-12-16 19:53
It was a kill. I was trying to simulate silo failure.

So the GrainDirectoryPartition only lives on a single silo? 

I guess the larger question is how resilient should we expect Orleans to be in the event of catastrophic silo failure. Are there other cases where data living on a single silo can can cause failures throughout the cluster?

I will see about getting a unit test built after the holidays.

Thanks

**Comment by benjaminpetit** [comment] 2016-12-16 22:41
The `GrainDirectoryPartition` is distributed across all silos in the cluster.

In a 2-silo cluster, if one is killed you lose (assuming both silos are under the same load):
- ~50% of the `GrainDirectoryPartition`
- ~50% of the grain activations

Since this two sets don’t' contain the same ids (ex: activation `A` lives on `Silo 1`, but its entry in the `GrainDirectoryPartition` is on `Silo 2`), if one silo is killed you will likely "loose' more than 50% of the activations (in this example in to 75%: all activations that lived on silo that was killed, and all activations that were on the `GrainDirectoryPartition`).

In reality, it is a bit more complex than that: `Silo 1` has a local cache of `GrainDirectoryPartition` entries that were previously queried (to avoid always make remote call to `GrainDirectoryPartition`). To continue with our example, if the entry for activation `A` was in the cache in `Silo 1`, then there is still hope for it :)

But what about grain client id? Since its activation doesn’t live on a silo, maybe we could replicate these entries on all silos to be more robust? I am not sure if it is worth it: normally your client will be connected to more than 1 silo in the cluster, so there is a chance that all silos that are connected will have this entry in their partition cache.

I hope that my explanations were clear?

**Comment by brianqcgames** [comment] 2017-01-02 20:21
Yes... that helps greatly. Thanks!

**Comment by sergeybykov** [comment] 2017-01-03 05:46
@brianqcgames Is there anything left to do here?

**Comment by brianqcgames** [comment] 2017-01-03 14:51
> normally your client will be connected to more than 1 silo in the cluster, so there is a chance that all silos that are connected will have this entry in their partition cache.

This line implies that a client "should" have an entry in each silo that is has connected to. In my case I am pretty sure my client was connecting to both silos so when one when down I would still expect to be able to resolve that client reference. I am not 100% sure about what I am observing so I want to create a simple test case outside of our service.

At a higher level I am still concerned about the notion that a client reference can become un-resolvable if a silo goes down. I am less concerned about grains because if we are doing things correctly and properly persisting state then the grains should be re-activated elsewhere in the cluster. In the case of clients, a client becoming unreachable is a big problem and in our case it is an even bigger problem since our orleans client is an http server that acts as a proxy for N actual clients. We need to be able to heal the service in this situation. If the entries were replicated to all silos then that would certainly work. Or, if the client could detect that this happened it could automatically reconnect? Another option could be to treat the client references more like membership entries and make them accessible via a more redundant and persistent layer (like redis or zookeeper). Unless, I am still misunderstanding the problem.

**Comment by benjaminpetit** [comment] 2017-01-05 16:56
I managed to reproduce the issue in a unit test. We don't hit the issue every time, I am investigating it

**Comment by benjaminpetit** [comment] 2017-01-05 23:03
Ok so the issue occurs if the client Id was registered in the partition of the killed/stopped silo. I am not sure on how the cache system works so let's ignore that for the moment.

We could say that if the client Id is not found in the partition and the local silo's gateway is connected to that client, we could use this silo's gateway. But it will not works if the client is not connected to this silo (client connect to a maximum of x gateways).

A possible fix could be that if the client Id is not found in the partition, ask all silos if they are connected to this client and add a new entry in the partition (basically "reconstruct" this entry). But there will be race conditions here, so it is not trivial. And if we have a lot of *orphan* subscriptions (clients that subscribed and disconnected without unsubscribing) it can become very chatty and impact performance.

But there is still hope :) Every `GlobalConfiguration.ClientRegistrationRefresh` (by default 5 minutes), a gateway iterates on all connected client and update the partition. That means that if your client is still connected to some gateways in the cluster, after less than `GlobalConfiguration.ClientRegistrationRefresh` it will be able to receive notifications.

**Comment by gabikliot** [comment] 2017-01-06 06:44
@benjaminpetit , your explanations are all correct, but I think the answer is basically much simpler:
our recommendation for using regular Observers has always been, and I think still is, is to periodically resubscribe. The reason is that observes simply do not provide reliable durable subscription model (they do not have durable pub sub). Indeed, sometimes you may be temped to apply reasoning like @benjaminpetit  did that is some cases even without durable pub sub it should work. Maybe. I prefer to be minimal and clear and stand 100% behind what we guarantee: for observers we do NOT guarantee durable subscription, these are best effort subscriptions and can get lost in all kind of different cases (by design, it is a feature, not a bug). So just periodically resubscribe if you need reliable observers.

The solution (should be) much better with client steams. Those do use durable pub sub and there it should be enough to subscribe once and it should always work, regardless of the failures.  The minor unfortunate circumstance is that we now have a corner case bug when in some situations this may also be violated (if client temporarily disconnected from ALL silos) but I consider that **a bug** and @jason-bragg is well aware of it, and I hope its high on his TODO list to fix it.

**Comment by benjaminpetit** [comment] 2017-01-11 02:00
But the issue here is not really with Observers: it is that when a silo is dead, we lost the mapping `clientId -> gateways` that silos was responsible for.

When the catalog detects that a silo is dead, it will deactivate all grain activations that were on the dead silo's directory. In the `ClientObserverRegistrar` we could also listen to membership change, and force a refresh of the clientId entries that are connected to the gateway, without waiting for the timer to fire.

I made a small prototype here: https://github.com/dotnet/orleans/compare/master...benjaminpetit:clientid-rebuild?expand=1 The fix seems quite simple and will add reliability without too much added complexity IMO.

**Comment by gabikliot** [comment] 2017-01-11 06:16
@benjaminpetit , yes, this is a good and worthy improvement. 

In your code, instead of restarting the timer, you can queue another local refresh callback:
`scheduler.QueueTask(() => OnClientRefreshTimer);`
just no need mess up with the timer. This is system target, so code will be single threaded anyway.

**Comment by brianqcgames** [comment] 2017-01-11 15:32
Thanks for digging into this!

@gabikliot We have always been a bit uncomfortable with some of our uses of observers to provide push communication to clients (or other grains) and have sometime arbitrarily picked a side of the communication to be the observer to avoid reentrant issues with grains. We are going to look at streams to see if they make more sense in some of our use cases.

@benjaminpetit I still believe that client references should be more reliable and appreciate you taking a look and providing a possible fix.

**Comment by sergeybykov** [comment] 2017-01-12 16:42
Resolved via #2587.

**Closed by sergeybykov** 2017-01-12 16:42 UTC
