### ISSUE TITLE
NullReferenceException in GatewayConnection.Stop

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#1034] opened 2015-11-17 20:23 UTC
Running some tests, I received this error: 
![image](https://cloud.githubusercontent.com/assets/203839/11223612/f587d2ee-8dc4-11e5-8d8c-33d8d1cc0c84.png)

This seems to be a regression introduced in #1017, but I haven't confirmed.
We should check for null there.

**Comment by gabikliot** [comment] 2015-11-17 21:05
I prefer to understand the root cause (and potentially fix it), before adding a null ref guard.
The goal of this feature was to provide a somewhat stronger guarantee (maybe not 100%, but as close to that as possible) on requests being broken early. So not breaking them in some cases will make that guarantee weaker.
Can you grab the client log (at Info level) when this happens and share it?

**Comment by ReubenBond** [comment] 2015-11-17 21:11
Here are the logs: https://gist.github.com/ReubenBond/1a81ab3351225b6c2c18

**Comment by gabikliot** [comment] 2015-11-17 21:16
Thanks. I will take a look.

**Comment by ReubenBond** [comment] 2015-11-17 22:09
It's being thrown on a new test, introduced in #1028, but I believe it
would be thrown on most tests. I was running in debug mode. It's possibly
non-deterministic, so your mileage may vary.

**Comment by gabikliot** [comment] 2015-11-17 22:30
I think I know what it is: it's a race in test mostly, between the `GrainClient.Uninitialize` and unloading of the app domain. We don't join all the client threads when we do `GrainClient.Uninitialize`, so when later on app domain unloads, it stops all the yet-running threads, and thus we get a duplicate call to `Stop` on this thread.  Will look deeper later.

**Comment by gabikliot** [comment] 2015-11-18 06:06
That was a good one!
Found a potential source for thread handlers leakage.
Fixed in #1036.

@ReubenBond, please verify that #1036 indeed solved the problem you saw. I was able to repro it locally and it did solve it for me.

**Comment by jdom** [comment] 2015-11-19 00:39
@gabikliot I think #1036 change is great and should be merged, although it doesn't really explain the NullReferenceException entirely, does it? Probably either Lockable or Cts fields were null at the time the domain was unloaded. 
Could it be that the domain was unloaded before it finished running the AsynchAgent constructor?
Another option is that AsynchAgent.Dispose was called, so it disposes and nulls the Cts field (this could have unwanted side effects if someone is still using the cancellation token, but since I'm not familiar with how AsynchAgent is being used, albeit risky I assume callers only call Dispose after the token is no longer needed nor there is still in-flight work being done). Maybe the Stop method needs protection against the Cts being nulled out?

**Comment by gabikliot** [comment] 2015-11-19 05:33
@jdom , it does explain it.

As @dVakulen wrote above: 
In this test we call `GrainClient.Uninitialize`  which sets the `RuntimeClient.Current` to null. `GrainClient.Uninitialize` also cleanly shuts all threads down, collects everything. After `GrainClient.Uninitialize` is done we should be fully uninitialized and nothing leaking.
Except for the bug in #1036, which caused the thread to still be rooted (preventing anything that was referenced from it to be GCed), and when the domain unload event was delivered, it called the `Stop` function on this thread and inside the `Stop` we got NullRefExc, since the `RuntimeClient.Current` is already null.
Makes sense?

**Comment by gabikliot** [comment] 2015-11-19 17:23
Fixed via #1036.

**Closed by gabikliot** 2015-11-19 17:23 UTC
Labels: bug

**Comment by jdom** [comment] 2015-11-19 17:56
I see, I guess I was looking only at the AsynchAgent.Stop implementation, which doesn't use RuntimeClient.Current, but I see now there are several other concrete implementations that override this method, and some of them do use RuntimeClient (especially GatewayConnection, which I now see it's the actual type shown in the stacktrace).
Thanks for the explanation
