### ISSUE TITLE
RegexImplicitStreamSubscription not working

### ISSUE THREAD

**Issue by cjenp** [dotnet/orleans#5247] opened 2018-12-12 12:41 UTC
Implicit stream subscription with RegexImplicitStreamSubscription attribute is not working:

> System.Runtime.Serialization.SerializationException: 'Type 'System.Text.RegularExpressions.RegexReplacement' in Assembly 'System.Text.RegularExpressions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.'

**Comment by xiazen** [comment] 2018-12-14 19:32
which version of orleans is this?

**Comment by xiazen** [comment] 2018-12-14 19:41
can you provide more information on this exception? such as its stack trace?

**Comment by cjenp** [comment] 2018-12-17 07:14
The exception occurs when the client try to connect to the cluster.

System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Type 'System.Text.RegularExpressions.RegexReplacement' in Assembly 'System.Text.RegularExpressions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync|4_0>d`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<StreamingInitialize>d__54.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.OutsideRuntimeClient.<<StartInternal>g__ExecuteWithRetries|56_3>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.OutsideRuntimeClient.<<StartInternal>g__ExecuteWithRetries|56_3>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<StartInternal>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.OutsideRuntimeClient.<Start>d__55.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.ClusterClient.<Connect>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebApiO.Startup.<StartClientWithRetries>d__8.MoveNext() in C:\GitRoot\SmartCacheOrleankka\SmartCacheOrleans\WebApiO\Startup.cs:line 89
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebApiO.Startup.ConfigureServices(IServiceCollection services) in C:\GitRoot\SmartCacheOrleankka\SmartCacheOrleans\WebApiO\Startup.cs:line 35

**Comment by ReubenBond** [comment] 2018-12-19 16:01
At first look, it seems the issue here is in serialization of `ImplicitStreamSubscriberTable.predicates`, which is a list containing `IStreamNamespacePredicate`.

So currently the client needs to be able to deserialize all `IStreamNamespacePredicate` implementations in the system. This includes `RegexStreamNamespacePredicate` and @alexeyzimarev's custom predicate.

For the RegEx predicate, we can serialize the Regex pattern as a string using custom serialization methods.

For the remainder (including @alexeyzimarev's issue #5274), we will have to make sure that all clients have access to all predicate types for now.

In the long run, we could consider alternative solutions, such as shifting the responsibility for predicate matching, etc, to the gateway/silo (eg, the simplest solution would be to have a grain perform the matching task and pass the results to the client).

**Comment by alexeyzimarev** [comment] 2018-12-19 19:19
@ReubenBond I have tried adding the predicate type to the client project and also added the assembly as an application part to the client initialisation code, but it didn't help.

**Comment by ReubenBond** [comment] 2018-12-19 19:35
@alexeyzimarev could you upload the `orleans.g.cs` file? Does the client have the code generation package installed?

**Comment by alexeyzimarev** [comment] 2018-12-19 19:37
@ReubenBond I confirm that it started to work when I placed the custom attribute to the grains interface project, which has the MSBuild code generation package referenced.

**Comment by ReubenBond** [comment] 2018-12-19 19:38
Ok great, thank you.

**Comment by xiazen** [comment] 2019-02-27 22:52
close this since it looks to me the problem is solved. feel free to reopen.

**Closed by xiazen** 2019-02-27 22:52 UTC
