### ISSUE TITLE
Switch to System.Text.Json APIs

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/orleans#6070] opened 2019-10-27 08:45 UTC
The new [System.Text.Json](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) API's provide a slight performance boost over Newtonsoft.Json and I believe the gap will get wider with further releases. This boost is even more prevalant if you serialize directly to and from UTF-8 bytes.

Are there any plans to migrate to this as the new default and possible enable the ability to switch between the two formats like in ASP.NET Core?

**Comment by JanEggers** [comment] 2019-10-27 13:15
I like the idea of improving json performance but I think https://github.com/neuecc/Utf8Json would be better aka faster

**Comment by SebastianStehle** [comment] 2019-10-27 14:18
Do you have benchmarks for System.Text.Json vs Utf8Json? They follow the same principle.

I think the biggest value of Newtonsoft.Json are the number of serializers. And if you look to the benchmarks in the blog then the performance benefit of System.Text.Json is not that big in real world scenarios.

**Comment by RehanSaeed** [comment] 2019-10-27 15:27
I think the performance benefit will be greater in time. This API is going to get a lot of eyes on it now. It's also part of dotnet. Ideally the JSON serialiser should be switchable like Asp.net.

**Comment by SebastianStehle** [comment] 2019-10-27 15:40
I do not expect big jumps in performance any more. It is more likely that it will be a little bit slower when more feature are added over time.

When you talk about serializers there  are hundreds of places. Each storage provider has its own dependencies and some scenarios like in MongoDB are also not possible with System.Text.Json https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/master/Orleans.Providers.MongoDB/StorageProviders/JsonBsonConverter.cs

**Comment by RehanSaeed** [comment] 2019-10-27 18:32
A common interface that could be used in all these places would allow you to switch out different serializers easily. ASP.NET Core has done something similar.

**Comment by justmara** [comment] 2019-10-28 10:38
System.Text.Json is still not finished and cannot be used ([for example](https://github.com/dotnet/corefx/issues/40120)) as a drop-in replacement for Newtonsoft. So one need to be a really careful when trying to switch to it. We've tried - and switched back to Newtonsoft on our project because of too much customizations already done that are not supported by this new api.

**Comment by sergeybykov** [comment] 2019-11-11 01:51
Sounds like the consensus is that a switch like this would be at least premature. Should we close this until something changes materially?

**Comment by RehanSaeed** [comment] 2019-11-11 09:28
Is it possible to make the default serializer switchable in readyness for System.Text.Json (There are a bunch of fixes and improvements coming in .NET Core 3.1)? Is that possible or does Orleans use too many of Newtonsoft.Json low level features?

**Comment by SebastianStehle** [comment] 2019-11-11 10:44
This would be a breaking change. I am very sure that most storage providers would have a problem. There will probably a lot of changes around serialization, e.g. System.Text.Json does not even provide a converter for TimeSpan and inheritance will be a problem as well. 

But a good start would be to check the converters: https://github.com/dotnet/orleans/blob/5b1d9cdf41f00cecd0f914667f1ca1a809c50e30/src/Orleans.Core/Serialization/OrleansJsonSerializer.cs

**Comment by sergeybykov** [comment] 2019-11-13 22:08
It seems to me that a general change is a non-starter. However, individual providers could take a dependency on `System.Text.Json` if it makes sense.

Since JSON is not used for messaging, the performance improvements I think are unlikely to become noticeable in the big scheme of things if they only contribute to persitence.

**Comment by jan-johansson-mr** [comment] 2019-11-30 14:16
Mmmm... but `System.Text.Json` is nice :-)

I've just kicked the tires of version 3.0.1, and man! This is really good stuff! I enjoy it so much, and make exhaustive use of the DI with State. Really good stuff! Everything also ties very nicely into generic host, so BIG Kudos to everyone that contributed to Orleans!

Thanks people!

**Comment by justmara** [comment] 2020-01-02 10:39
> Mmmm... but `System.Text.Json` is nice :-)

no, it is [not](https://github.com/dotnet/corefx/issues/38650) :)

**Comment by jan-johansson-mr** [comment] 2020-01-02 14:30
Hmm... that is solved by a nice plugin (by design they left out stuff that
newtonsoft has out of the box), as a coincidence I happen to have written
such a nice polymorphic serializer plugin to system.text.json :-) :-)

Den tors 2 jan. 2020 11:39justmara <notifications@github.com> skrev:

**Comment by ahsonkhan** [comment] 2020-01-07 02:08
> as a coincidence I happen to have written
such a nice polymorphic serializer plugin to system.text.json :-) :-)

Would you be willing to share that? I would be interested in seeing how it was done :)

**Comment by justmara** [comment] 2020-01-07 09:16
@ahsonkhan I think he means [this one](https://github.com/dahomey-technologies/Dahomey.Json), but its... kinda disputable

**Comment by jan-johansson-mr** [comment] 2020-01-07 11:42
Nope, as I wrote, I did the plugin myself...

Den tis 7 jan. 2020 10:16justmara <notifications@github.com> skrev:

**Comment by jan-johansson-mr** [comment] 2020-01-07 11:49
I checked it out, and the solution pointed to is kind of involved, a lot of
moving parts. The solution I made is much less involved, but covers all my
needs. In short, I push as much as I can to the system.text.json
serializer, but do some basic (small) housekeeping that's needed. No need
to write a handler for each basic runtime type.

Den tis 7 jan. 2020 12:42Jan Johansson <jan.johansson.mr@gmail.com> skrev:

**Comment by electricessence** [comment] 2020-01-17 22:16
https://michaelscodingspot.com/the-battle-of-c-to-json-serializers-in-net-core-3/
Utf8Json appears to be WAY faster.

**Comment by electricessence** [comment] 2020-01-17 22:16
True parity is a problem: https://github.com/dotnet/corefx/issues/38650

**Comment by electricessence** [comment] 2020-01-17 22:17
https://github.com/electricessence/Open.Serialization
I've done my best to match parity across the different libs, but the above issue really killed that dream.

**Closed** 2020-03-24 03:19 UTC
