### ISSUE TITLE
High cpu load on linux with net core 2.0

### ISSUE THREAD

**Issue by sergeibulavintsev** [dotnet/orleans#3724] opened 2017-11-29 08:07 UTC
Good day,
We tried to run orleans 2.0 under debian using net core 2.0 and we discovered strange behavior: silo application consumes 100% from one core without any client connected to it (tested on quad core processor). Even trying to run hello world example for net core showed similar behavior. Using perf tool showed that 80% of 'overhead' was in libcoreclr.so Running application using orleans 1.5 with mono exposed totally different behavior and it was consuming just 2% from one core. 
Also tried to call strace to see which operation consumes so much cpu time and observed that threads always were calling futex() call:
[pid  4969] futex(0x2625f44, FUTEX_WAIT_PRIVATE, 21917, NULL <unfinished ...>
[pid  4974] futex(0x262b3c8, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid  4958] <... futex resumed> )       = 1
[pid  4955] futex(0x23e4de4, FUTEX_WAIT_BITSET_PRIVATE, 34959, {tv_sec=714131, tv_nsec=391327737}, 0xffffffff <unfinished ...>
[pid  4958] futex(0x262b3c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  4974] <... futex resumed> )       = 0
[pid  4958] <... futex resumed> )       = 1
[pid  4974] futex(0x262b3c8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  4958] futex(0x262e6c4, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x262e6c0, FUTEX_OP_SET<<28|0<<12|FUTEX_OP_CMP_GT<<24|0x1 <unfinished ...>
[pid  4974] <... futex resumed> )       = 0
[pid  4977] <... futex resumed> )       = 0
[pid  4958] <... futex resumed> )       = 1
[pid  4977] futex(0x262e698, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid  4958] futex(0x262e698, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  4977] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  4958] <... futex resumed> )       = 0
[pid  4977] futex(0x262e698, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  4958] futex(0x262a304, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x262a300, FUTEX_OP_SET<<28|0<<12|FUTEX_OP_CMP_GT<<24|0x1 <unfinished ...>

I will appreciate any advice in solving this issue.

**Comment by sergeybykov** [comment] 2017-11-30 19:21
Is there a way to get call stacks?

**Comment by sergeibulavintsev** [comment] 2017-12-01 10:27
I built debug version of libcoreclr.so and could get call stacks for it. Some undefined symbols I think come from orleans dlls which are built in release, but hope it can help anyway.
[orleans_call_stack.txt](https://github.com/dotnet/orleans/files/1521216/orleans_call_stack.txt)
[htop_output.txt](https://github.com/dotnet/orleans/files/1521217/htop_output.txt)

**Comment by benjaminpetit** [comment] 2017-12-01 21:16
Hi @sergeibulavintsev,

Did you manage to reproduce this issue on Windows, using the "full" dotnet or core? Are clients able to connect to this silo and send requests?

I didn't noticed any issue on Linux, I am using official dotnet docker images (Debian 9.2).

**Comment by sergeibulavintsev** [comment] 2017-12-02 06:23
Hi,
On Windows I couldn't reproduce this issue, using net core on Windows works es expected. Clients are able to connect to Silo and when we give some load to it, "top" util shows 400% cpu usage on Debian, 100% when it waits for clients.

**Comment by sergeibulavintsev** [comment] 2017-12-04 10:40
Hi,
I installed debian 9.2 on virtual machine with host OS as Windows and ran orleans with net core there and cpu load was fine, just 5-6%, then I installed Ubuntu LTS 17.10 on physical machine and tested it there, cpu load again was 100%

**Comment by tinpl** [comment] 2017-12-04 11:21
Hi, can confirm we had this issue also on ubuntu 16.04 LTS using beta-1, the silo had 100% cpu load on startup, so we temporarily switched our staging back to windows until it's probably resolved. 
Tried to run it on macos sierra, same thing (not 100%, but quite high on silo regardless does it has connected client or not). 
Attaching sampling of the process, maybe it will help somehow..
[orleans.sampling-macos.txt](https://github.com/dotnet/orleans/files/1526797/orleans.sampling-macos.txt)

[orleans.top.txt](https://github.com/dotnet/orleans/files/1526798/orleans.top.txt)

**Comment by ik80** [comment] 2017-12-04 11:53
To me this smells like someone is repeatedly calling ThreadNativeWait with a really small timeout in an effort to reduce latency. Ugh!

**Comment by benjaminpetit** [comment] 2017-12-04 17:57
I just tried on an up-to-date Ubuntu 16.04.3, with dotnet-sdk-2.0.3 installed and I do not reproduce this issue on a physical machine.

The machine is using a Xeon E3-1220v1, 24gb ram, kernel 4.4

Could you post your hardware spec/software versions?

**Comment by sergeibulavintsev** [comment] 2017-12-05 07:27
I tested on Ubuntu 17.10 kernel version 4.13, dotnet-sdk-2.0.3
CPU is core i7-7700K, 16 Gb ram

**Comment by sergeibulavintsev** [comment] 2017-12-05 09:24
may be it can be as clue: I prepared virtual machine from same Ubuntu iso image and windows as host system and discovered that orleans consumes just 4-5% in idle state, so difference with my previous case that ubuntu was installed directly on physical machine.

**Comment by benjaminpetit** [comment] 2017-12-05 16:55
My test was also on bare metal, and I didn't noticed that. Are you using one of the sample?

**Comment by sergeibulavintsev** [comment] 2017-12-06 08:03
I have found root of problem, I disabled Hyper-Threading and on both physical machines with different Linux OS (Debian and Ubuntu) orleans started to consume in idle mode around 10% from one real core (before it was 150% from hyper-threading cpu). Have you encountered such situation ever or may be you have any explanations for that behavior? I will appreciate any answer, I'm really curious why disabling hyper threading can change behavior of netcore for linux.

**Comment by sergeibulavintsev** [comment] 2017-12-07 13:29
Anyway even when Hyper Threading is disabled Silo application consumes 10-15%, it is much slower than running under Windows with same net core version. On windows same silo application in idle consumes just 0.1-0.5% of CPU time and difference in performance is too obvious, however it is not 150% but still is not acceptable. What about your silo application under linux? How much does it consume?

**Comment by benjaminpetit** [comment] 2018-01-11 00:05
Following this after the holidays...

It seems that there was some issues with Kaby Lake HT, is your bios and CPU microcode up-to-date?

**Comment by ik80** [comment] 2018-01-11 07:42
Hi!

Thanks for following up on this, since its not exactly an orleans issue!

Indeed we tested this on Kaby Lake CPU with out of date microcode. Today we updated microcode and turned HT on again, and the issue persists. We DID NOT update BIOS however, since it is not trivial on this vendor box.

For now we decided not to use the orleans tech., so there wont be any more input from us, however turning off HT is a viable option for anyone who runs into this same problem.

**Comment by raghur** [comment] 2018-07-11 09:54
Can this be reopened? It's not entirely clear why this was closed.

I'm facing the same issue with a toy project running on k8s cluster - .net core 2 and orleans 2.0.3. THere are no requests and yet the silo consumes 1+ cores all the time.

![image](https://user-images.githubusercontent.com/516267/42564405-4a596636-851e-11e8-828f-ea29bc79e7a1.png)

**Comment by jason-bragg** [comment] 2018-07-11 16:42
@raghur what OS and version?

**Comment by raghur** [comment] 2018-07-12 04:06
@jason-bragg  - Ubuntu 16.04.2 image on an AKS cluster 

BTW, I think I found what's happening. I had a liveness & readiness probe that launched the same executable with a different argument that makes a call through a grain client and returns the version string. Turning off the probes seem to have brought down CPU to expected levels.

OTOH, I'm a little surprised that launching a process that prints a version string and exits is causing this much load - but that's nothing to do with orleans. 

![image](https://user-images.githubusercontent.com/516267/42612087-e61aae98-85b6-11e8-8c1d-34599e2d92c9.png)

**Comment by benjaminpetit** [comment] 2018-07-26 21:14
@raghur can you check if 2.0.4 solves your issue?

**Comment by benjaminpetit** [comment] 2018-08-02 22:49
If should have been fixed with 2.0.4. Don't hesitate to reopen it if needed.

**Closed by benjaminpetit** 2018-08-02 22:49 UTC
