### ISSUE TITLE
SQL CreateOrleansTable files

### ISSUE THREAD

**Issue by kmyrtue** [dotnet/orleans#3890] opened 2018-01-22 14:23 UTC
To populate the SystemStorage when using a SQL database the createOrleansTables is needed.

The location given in the documentation for these files are Binaries/OrleansServer I spent a lot of time looking on the internet since I could not find them in the surgested package. Instead they are in the packages/OrleansSQLUtils/lib/net.

This issue is only a surgested update for the documentation in the following file "http://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Configuration-Guide/Configuring-SQL-Tables.html"

the paragraph:
Where the DataConnectionString is set to any valid SQL Server connection string. In order to use SQL Server as the store for system data, there’s now a script file CreateOrleansTables_*(where asterisk denotes database vendor) in the Binaries\OrleansServer folder which establishes the necessary database objects. Make sure that all servers that will be hosting Orleans silos can reach the database and has access rights to it! We’ve tripped up a few times on this seemingly trivial concern during our testing.

to:

Where the DataConnectionString is set to any valid SQL Server connection string. In order to use SQL Server as the store for system data, there’s now a script file CreateOrleansTables_*(where asterisk denotes database vendor) in the **Binaries\OrleansSQLUtils\lib\net** folder which establishes the necessary database objects. Make sure that all servers that will be hosting Orleans silos can reach the database and has access rights to it! We’ve tripped up a few times on this seemingly trivial concern during our testing.

**Comment by veikkoeeva** [comment] 2018-01-23 18:38
Indeed, in addition to the ones linked by @Xanatus, the relevant ones are https://github.com/dotnet/orleans/issues/3865 and https://github.com/dotnet/orleans/issues/3864.

**Comment by sergeybykov** [comment] 2018-01-24 00:37
Closing this as a duplicate of #3862.

**Closed by sergeybykov** 2018-01-24 00:37 UTC
