### ISSUE TITLE
 Timer should have fired at "xxxxxxxxxxx", which is "xxxxxxxxxxx" ago

### ISSUE THREAD

**Issue by Itoktsnhc** [dotnet/orleans#6218] opened 2020-01-08 02:45 UTC
After running for a while (about a week), the following log appears

>2020-01-03 17:47:30.964 +08:00 [ERR] **DeleteDeadMembershipTableEntries operation is not supported by the current implementation of IMembershipTable. Disabling the timer now.**
2020-01-03 17:48:04.533 +08:00 [WRN] Timer should have fired at "2020-01-03T09:47:29.1370809Z", which is "00:00:35.3965504" ago
2020-01-03 17:48:04.534 +08:00 [WRN] Watchdog had 1 Health Check Failure(s) out of 5 Health Check Participants.
2020-01-03 17:53:05.355 +08:00 [WRN] Timer should have fired at "2020-01-03T09:47:29.1370809Z", which is "00:05:36.2182977" ago

And
> 2020-01-08 10:32:01.608 +08:00 [WRN] Timer should have fired at "2020-01-03T09:47:29.1370809Z", which is "4.16:44:32.4709898" ago
2020-01-08 10:32:01.608 +08:00 [WRN] Watchdog had 1 Health Check Failure(s) out of 5 Health Check Participants.
2020-01-08 10:37:02.030 +08:00 [WRN] Timer should have fired at "2020-01-03T09:47:29.1370809Z", which is "4.16:49:32.8934554" ago
2020-01-08 10:37:02.030 +08:00 [WRN] Watchdog had 1 Health Check Failure(s) out of 5 Health Check Participants.
2020-01-08 10:42:02.455 +08:00 [WRN] Timer should have fired at "2020-01-03T09:47:29.1370809Z", which is "4.16:54:33.3186580" ago
2020-01-08 10:42:02.455 +08:00 [WRN] Watchdog had 1 Health Check Failure(s) out of 5 Health Check Participants.

Using direct client connect to single silo use localhost clustering as background service in asp.net core 3.0.
Orleans Dashboard : 3.0.8
Microsoft.Orleans.XXX : 3.0.2

**Comment by sergeybykov** [comment] 2020-01-08 17:17
What clustering provider are you using? This is by design because that clustering provider doesn't implement the cleanup functionality, which is optional.

**Comment by Itoktsnhc** [comment] 2020-01-09 03:32
@sergeybykov  
I am using 'UseLocalhostClustering'.  
Now I see it is development-only clustering. 
![image](https://user-images.githubusercontent.com/11204672/72035599-4ed08c80-32d3-11ea-9506-e0f9ade4d667.png)
So do I need to use other Clustering Providers in the case of a single silo node?

**Comment by sergeybykov** [comment] 2020-01-09 16:49
Is this meant for production? The table cleanup functionality was added to prevent the cluster membership table to grow too big in case of large clusters or high churn rate of silo. For a small setup like yours, you can simply ignore this warning.

**Comment by Itoktsnhc** [comment] 2020-01-10 05:30
Ok I get it, thanks for the explanation. 😁

**Comment by veikkoeeva** [comment] 2020-01-10 09:16
Should the warning message be improved with this explanation? :)

**Comment by sergeybykov** [comment] 2020-01-10 16:11
We might want to special-case the local clustering provider, and not fire this warning for it. It makes sense for all real, storage-based, providers I think.

**Comment by sergeybykov** [comment] 2020-03-24 03:23
Should be resolved via #6415.

**Closed by sergeybykov** 2020-03-24 03:23 UTC
Labels: question
