### ISSUE TITLE
StartupTypeName config location

### ISSUE THREAD

**Issue by jasonholloway** [dotnet/orleans#1765] opened 2016-05-16 10:16 UTC
Just ran into a problem in trying to set up `TestCluster` with a designated startup class for DI: the `StartupTypeName` value appears in the per-node configuration object, and is as such automatically overridden by `TestCluster`, which uses specially-generated config overrides for each silo node it creates, thereby ignoring the settable defaults.

This can be hacked through for now by enumerating through each override node that `TestCluster` creates (or at least I think it can - additional silos can only be created after deployment, can't they...)

But - it occurs to me that the Startup class shouldn't be a per-node value in the first place. Having different DI containers per silo surely poses an ever so slight risk to the location transparency of grains - some seriously sharky waters here.

Could it be moved to `ClusterConfiguration.Globals`?

**Comment by jdom** [comment] 2016-05-16 22:40
If you set this setting in `ClusterConfiguration.Defaults`, then it should be automatically propagated to all the individual node configurations. Also, there's the `ApplyToAllNodes` extension method to avoid the manual enumeration.

Having said all that (at least as a temporary workaround), I agree with you that it doesn't make much sense to have this as a `NodeConfiguration' setting, and I would agree it might fit `GlobalConfiguration` better.
Pinging @attilah, since he initially put it there, to see if this was by design or he would agree with a move too.

**Comment by jasonholloway** [comment] 2016-06-11 18:25
Hi @jdom, sorry for taking ages to respond. I've looked into it a bit more, and I think the first issue above (ie the difficulty in setting per-node config values) was/is to do with `TestCluster` over-eagerly setting up an override for its primary node in its most obvious constructors via `TestClusterOptions` - before the user has had any chance to mess about with the defaults, the 'default' defaults have already been used to configure the first node.

Obviously the already-created primary override can be tweaked in situ, but it wasn't the most obvious thing. Perhaps though it makes sense in other ways to create the primary override up front.

The solution, probably, is documentation :)

**Comment by jdom** [comment] 2016-11-07 20:49
I think after a lot of back and forth, we cannot 100% decide whether this should be a global configuration, or a node configuration, as you might actually want to configure the silos differently (although in theory the Startup class itself could do the branching). 
Since there's no 100% right choice (at least for now, until we revamp configuration, which hopefully should come soon) we are closing this issue. This approach does not constraint the configuration, where as the other approach (having it in Globals) might, and people might be relying on it.
The supplied extension method `UseStartupType` should make matters easier for the case that you want all of the silos to align.

Feel free to comment if you believe this should be reopened. Thanks

**Closed by jdom** 2016-11-07 20:49 UTC
