### ISSUE TITLE
Azure queue tests failing

### ISSUE THREAD

**Issue by dVakulen** [dotnet/orleans#1037] opened 2015-11-18 19:01 UTC
Azure queue streaming tests sometimes fails with QueueNotFound exception on latest build (09a4f40).

Logs: https://gist.github.com/dVakulen/a3f21fd3f72bc58e95dd.

**Comment by dVakulen** [comment] 2015-11-18 22:29
Some observation that may be helpful - with binary formatter as fallback serializer this tests fails ~ 1 out of 7 times but with Json.Net they fail on every run.

**Comment by sergeybykov** [comment] 2015-11-18 22:55
Interesting. Although makes not sense to me.

**Comment by gabikliot** [comment] 2015-11-19 05:39
Is it possible that the tests are now running with the newer Azure Storage SDK version (after we merged https://github.com/dotnet/orleans/pull/1024) and the new SDK changed some behavior of the Azure Queue?

**Comment by dVakulen** [comment] 2015-11-19 06:13
I saw this tests failing before the merge of the #1024.

**Comment by gabikliot** [comment] 2015-11-19 06:28
Is it one particular test? Which one is it?

**Comment by sergeybykov** [comment] 2015-11-19 06:35
We saw https://github.com/dotnet/orleans/blob/master/src/Tester/StreamingTests/AQSubscriptionMultiplicityTests.cs#L125 failing with this error. @jason-bragg was investigating.

**Comment by gabikliot** [comment] 2015-11-19 07:37
Ohh, that is a new test he just added 2 days ago: https://github.com/dotnet/orleans/pull/1023.
Maybe it never worked.
I do remember that we had a client side (both consumer and producer) tests, both for SMS and AQ, working correctly in VSO. There was even a test when both consumer and producer are on the client. Do they still work correctly now?

**Comment by gabikliot** [comment] 2015-12-01 04:26
Looks like that can be closed now. The test was fixed via #1070  and the real fix for the issue is described in #1069.

**Closed by gabikliot** 2015-12-01 04:26 UTC
Labels: bug
