### ISSUE TITLE
Unable to schedule reminders with a dueTime > 4294967294ms 

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#7571] opened 2022-02-17 03:29 UTC
See: https://github.com/dotnet/orleans/blob/a30f0ab6a3c4c46e01d4e09d8960fe95cf9387d4/src/Orleans.Runtime/ReminderService/ReminderRegistry.cs#L36-L53

Why is this limitation imposed?

**Comment by ElanHasson** [comment] 2022-02-17 03:30
Dupe of https://github.com/dotnet/orleans/issues/1298#issue-127361552

**Comment by ElanHasson** [comment] 2022-02-17 03:30
What would it take to change this?

**Comment by rafikiassumani-msft** [comment] 2022-02-17 19:16
Closing as dupe of #1298

**Closed by rafikiassumani-msft** 2022-02-17 19:16 UTC
Labels: area-reminders/timer

**Comment by ElanHasson** [comment] 2022-02-17 20:15
@rafikiassumani-msft  I'm talking with @ReubenBond  about how to do this. I have a working prototype.

Details to follow.
