### ISSUE TITLE
Problem with PubSubStateGrain JSON serialization 

### ISSUE THREAD

**Issue by yoniabrahamy** [dotnet/orleans#1041] opened 2015-11-19 09:09 UTC
Hello everyone,
We are using a custom storage provider which uses JSON.NET serialization, and when trying to use it as the PubSubStore (which saves the `PubSubGrainState`) for persistent streams, it fails to deserialize the `PubSubGrainState` correctly.

I have seen an issue that was opened before ([here](https://github.com/dotnet/orleans/issues/328)) and in the following pull request ([here](https://github.com/dotnet/orleans/pull/331/)) it seems that it has been resolved. However, going over the merge request and the current code I can see that many changes have been made. 

I believe that the breaking changes occurred in `PubSubPublisherState` and `PubSubSubscriptionState` (These classes are a part of `PubSubGrainState`). 
Currently, these are the classes properties:

* In PubSubPublisherState:
```
    public StreamId Stream;
    public GrainReference producerReference; // the field needs to be of a public type, otherwise we will not generate an Orleans serializer for that class.
    public IStreamProducerExtension Producer { get { return producerReference as IStreamProducerExtension; } }
```
* In PubSubSubscriptionState:
```
        public GuidId SubscriptionId;
        public StreamId Stream;
        public GrainReference consumerReference; // the field needs to be of a public type, otherwise we will not generate an Orleans serializer for that class.
        public object filterWrapper; // Serialized func info
        public SubscriptionStates state;
```

In my opinion the problem lies in the properties `GrainReference producerReference` and `GrainReference consumerReference`. Since they represent a reference to a grain, I don't think that serializing them "as is" and then deseriailzing them later will get the wanted result. Also, I have noticed that these properties joined the classes after the aforementioned pull request.

So my question basically is: How should I JSON serialize the PubSubGrainState? and more specifically, how should I JSON serialize `GrainReference`?

**Comment by gabikliot** [comment] 2015-11-19 17:50
After issue #328 there was another issue #752 that I fixed in #754.
The  `GrainReference producerReference` and `GrainReference consumerReference` should work, I explicitly changed the code this way so it will work.
Perhaps something else was changed lately and broke it.
Perhaps the problem is with the filter - https://github.com/dotnet/orleans/issues/836. The filter was added as mandatory in https://github.com/dotnet/orleans/pull/967.

The Json serializer is **extremely fragile**.
I promised to wrote a test here https://github.com/dotnet/orleans/pull/754#issuecomment-137151625 but it turned out to be harder that I thought. I could not write a standalone unit test for `PubSubGrainState` outside the silo, since I could not mock/fake `GrainReference`. So the fallback for test now is an end to end streaming test with Json pub sub, which I think we do not have.

**I think we should absolutely create a standalone test for that**, but I don't know how at this point.
Perhaps @jason-bragg  will know. If not standalone, at least to change some of the AQ tests to use Json pub sub. That should be easy to do.
Maybe also alternatively change the `PubSubGrainState` to do explicit ISerializable interface for Json, like done now in `GrainReference` https://github.com/dotnet/orleans/blob/master/src/Orleans/Runtime/GrainReference.cs#L690). Hopefully it will be less fragile.

**Comment by randa1** [comment] 2015-11-21 08:43
@gabikliot, I have a question regarding the last paragraph about `GrainReference` serialization. If I serialize `GrainReference` To Json then deserialize it on later time, will the reference still be usable even after Grain relocation, silo shutdowns, etc? Doesn't `GrainReference` hold some data that is specific to the current activation state of the target Grain?

I apologize beforehand if this is a trivial question :)

**Comment by gabikliot** [comment] 2015-11-21 15:06
Ran, no problem. Yes, the grain references will be useable. It stores no physical data, only the grain primary key and typo info. This is part of the virtual actor abstraction.

**Comment by yoniabrahamy** [comment] 2015-11-21 18:01
That's interesting. The problem that i experienced was that after the deserialization the property `public IStreamProducerExtension Producer', which returns the `producerReference` (which is a `GrainReference`) as an `IStreamProducerExtension`, started to return null for me. That is why I figured that there is something wrong with the deserialization process.

**Comment by gabikliot** [comment] 2015-11-21 19:17
Right. This is most probably due to something changed/ broken in integration with json, so grain reference cannot deserialize. Or while serialization we somehow don't capture it. It is not due to anything dynamic changing in the cluster, like grain activation moved.

**Comment by dVakulen** [comment] 2015-11-21 21:13
There's possibility that this was fixed in #1047, e.g. [GrainId converter](https://github.com/dotnet/orleans/pull/1047/files#diff-cda7828deb9a413344be865303b65661R129) but seems like internal converters must be exposed to users in order to be used by their serialization code.

**Comment by randa1** [comment] 2015-11-22 17:48
This was actually an issue on our end. I think we can close it @yoniabrahamy.

**Comment by gabikliot** [comment] 2015-11-26 06:28
Closing, as indicated by @randa1. Please re-open is the issue persists.

**Closed by gabikliot** 2015-11-26 06:28 UTC
Labels: bug
