### ISSUE TITLE
Can't send message to stream after a long time 

### ISSUE THREAD

**Issue by shersh** [dotnet/orleans#7191] opened 2021-08-10 09:09 UTC
After cluster running a some time (20+ hours) messages can't be sent to stream.

This happend after we added RedisStorage as PubSubStore with this options:

```
{
     options.ConnectionString = redisDbConfig.ConnectionUri;
     options.DeleteOnClear = true;
}
```

Log:

> {"@t":"2021-08-10T08:49:58.3008163Z","@m":"Failed to deliver message to consumer on \"62a24131-b3b1-44b3-a43e-284731ff3a53\" for stream \"CLIENT_STREAM-a9a4ff8c-8570-4e1b-9e02-79b53a348641-ORLEANS_STORAGE_PROVIDER\", may retry.","@i":"c9f2c62e","@l":"Warning","@x":"Orleans.Runtime.GrainReferenceNotBoundException: Attempted to use a GrainReference which has not been bound to the runtime: ObserverId:*cli/4414f54b1e853f524a6c203dd6d185980400000000000000-0x252760F5/37470e00-89be-4093-8594-a0cc8dd46cd1. Use the IGrainFactory.BindGrainReference method to bind this reference to the runtime.\n   at Orleans.Runtime.GrainReference.get_Runtime()\n   at Orleans.Runtime.GrainReference.InvokeMethodAsync[T](Int32 methodId, Object[] arguments, InvokeMethodOptions options, SiloAddress silo)\n   at Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference.global::Orleans.Streams.IStreamConsumerExtension.DeliverBatch(GuidId subscriptionId0, StreamId streamId1, Immutable`1 item2, StreamHandshakeToken handshakeToken3)\n   at Orleans.Streams.PersistentStreamPullingAgent.ContextualizedDeliverBatchToConsumer(StreamConsumerData consumerData, IBatchContainer batch)\n   at Orleans.Streams.PersistentStreamPullingAgent.DeliverBatchToConsumer(StreamConsumerData consumerData, IBatchContainer batch)","SubscriptionId":"62a24131-b3b1-44b3-a43e-284731ff3a53","StreamId":"CLIENT_STREAM-a9a4ff8c-8570-4e1b-9e02-79b53a348641-ORLEANS_STORAGE_PROVIDER","SourceContext":"Orleans.Streams.ORLEANS_STORAGE_PROVIDER","ExceptionDetail":{"HResult":-2146233088,"Message":"Attempted to use a GrainReference which has not been bound to the runtime: ObserverId:*cli/4414f54b1e853f524a6c203dd6d185980400000000000000-0x252760F5/37470e00-89be-4093-8594-a0cc8dd46cd1. Use the IGrainFactory.BindGrainReference method to bind this reference to the runtime.","Source":"Orleans.Core.Abstractions","Type":"Orleans.Runtime.GrainReferenceNotBoundException"},"machine_name":"c7d36400351b","environment":"Production"}

@ReubenBond  Could you suggest any solutions and is this bug of core Orleans or Redis persistance package?

**Comment by ReubenBond** [comment] 2021-09-02 19:04
Based on the error message, this is the same issue as #7188. I'll close this in favor of that. The issue is fixed in the Orleans.Redis repository, but is pending a release.

**Closed by ReubenBond** 2021-09-02 19:04 UTC
