### ISSUE TITLE
MissingMethodException in Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by Hariongit** [dotnet/orleans#6144] opened 2019-11-27 16:18 UTC
Hi,
I am having the below exception.

System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IHttpClientBuilder Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.String, System.Action`1<System.Net.Http.HttpClient>)'.

It doesn't happen in developer machine but on windows-7 computer that i want to run the  application i have seen above issue.
I tried switches .net core versions from 3.0.1 to 2.1.0 with clean builds each time but none of them worked.
Any thoughts on how to resolve this issue ?

**Comment by ReubenBond** [comment] 2019-11-27 17:18
Hi @Hariongit, I believe this error is caused by incompatible packages being loaded.

Orleans never calls `AddHttpClient`, so it must be something else, but I am happy to help you find it. 

It is likely that some package needs to be updated because of a breaking change in another package

Could you provide the full stack trace so we can locate the source of the error?

**Comment by Hariongit** [comment] 2019-11-27 17:27
Hi, 
I think it is related to .net core so i posted it there https://github.com/dotnet/core/issues/3922
I tried keeping all the packages update to the specific versions using Nuget but it didn't worked out.
Regarding stack trace : other than the above trace attached i don't have any additional info from.

Thank you for looking into this.

**Comment by ReubenBond** [comment] 2019-11-27 17:29
@Hariongit what you posted above isn't a stack trace, it's just the exception message. The stack trace allows us to see which method is trying to call the missing method, and therefore helps us to locate the out-of-date assembly.

**Comment by Hariongit** [comment] 2019-11-27 19:35
@ReubenBond, Stack trace doesn't have any additional info other than costume code call stack, Any ideas on what else i can look into ? 

please find the attached package config info if that helps.
<packages>
  <package id="log4net" version="2.0.8" targetFramework="net471" />
  <package id="Microsoft.Extensions.Configuration" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.DependencyInjection" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.Http" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.Logging" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.Options" version="3.0.0" targetFramework="net471" />
  <package id="Microsoft.Extensions.Primitives" version="3.0.0" targetFramework="net471" />
  <package id="Newtonsoft.Json" version="12.0.3" targetFramework="net471" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net471" />
  <package id="System.ComponentModel.Annotations" version="4.6.0" targetFramework="net471" />
  <package id="System.IO" version="4.3.0" targetFramework="net471" />
  <package id="System.Memory" version="4.5.3" targetFramework="net471" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net471" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net471" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0" targetFramework="net471" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net471" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net471" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net471" />
</packages>

**Comment by ReubenBond** [comment] 2019-11-27 19:36
The call stack is exactly what I'm looking for. The method which ends up throwing that exception is the issue. Whatever assembly that method lives in needs to be updated and recompiled

**Comment by Hariongit** [comment] 2019-11-27 20:22
@ReubenBond, Thankyou for quickly sharing some ideas.
I was able to resolve the issue with assembly redirect on executable's app.config on "System.Net.Http" assembly as suggested in https://github.com/dotnet/corefx/issues/35656 this post.

**Comment by ReubenBond** [comment] 2019-11-27 20:58
Great :) feel free to close this issue if it's resolved

**Closed** 2019-11-27 22:10 UTC
