### ISSUE TITLE
Orleans fails to deliver the first message to client occasionally with "don't have any subscriber for that stream. Dropping on the floor"

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1254] opened 2016-01-08 18:34 UTC
Note I'm using [a stream provider](https://github.com/amamh/orleans-PipeStreamProvider) that keeps old messages and sends them always to new subscribers (recovery).  The error is not in the stream provider though, and I'll explain why.

#### Scenario:

- One message is sent on the stream
- A subscriber is added
- Subscriber expects to receive that message

#### Failure:

Sometimes, a new subscriber doesn't receive anything. This happens completely at random, there doesn't seem to be anything to force that error to occur.

#### How to reproduce:

I made a [sample project](https://incraved.cloudapp.net/owncloud/index.php/s/psLweltkCLd3W9S) that can reproduce that error.

- Run Redis\RUN.bat (needed by the stream provider)
- Run solution. This will run:
  - Silo
  - Producer (sends one message on a stream)
  - A Console client subscriber
- The console client will try to reproduce the error every second by creating a new subscriber and checking if it received the message or not. It takes maybe a minute or two until it happens. Sometimes it will occur on the first few tries. It seems to be affected by how fast the PC is and how much pressure there is on the server. A faster CPU/server will produce the error quicker.

You can also run multiple instances of the client to increase the chance of the failure happening.

#### Error message:

		[2016-01-08 17:06:26.393 GMT    18      WARNING 103407  StreamConsumerExtension
		127.0.0.1:0]    C127.0.0.1:0:-189968502*cli/36a6d0a5@10c86faa got an item for su
		bscription 7bec8598, but I don't have any subscriber for that stream. Dropping o
		n the floor.
		[2016-01-08 17:06:26.393 GMT    18      WARNING 103407  StreamConsumerExtension
		127.0.0.1:0]    C127.0.0.1:0:-189968502*cli/36a6d0a5@10c86faa got an item for su
		bscription 7bec8598, but I don't have any subscriber for that stream. Dropping o
		n the floor.

You should see the following:

![Console](http://i.imgur.com/skIh9UC.png)

#### Subscription code

In case you can't run the project atm, here is how I'm testing on the client side:

Main method:

            while (true)
            {
                var testObserver = new TestObserver();
                testObserver.Subscribe().Wait();
                var received = false;
                // wait for client to receive message
                for (int i = 0; i < 1000; i++)
                {
                    if (testObserver.ReceivedMessage)
                    {
                        received = true;
                        break;
                    }
                    Task.Delay(5).Wait();
                }
                //testObserver.Unsubscribe().Wait();
                if (!received)
                {
                    Console.WriteLine("Client did not receive the message.");
                    break;
                }

                Task.Delay(1500).Wait();
            }

Observer:

        public bool ReceivedMessage = false;

        public async Task Subscribe()
        {
            var ccGrain = GrainClient.GrainFactory.GetGrain<IPriceGrain>("IDUS.L");
            var stream = await ccGrain.GetStream();
            _handle = await stream.SubscribeAsync(this, new PipeStreamProvider.SimpleSequenceToken(0));
        }

        public Task OnNextAsync(IPrice item, StreamSequenceToken token = null)
        {
            Console.WriteLine($"I received {item}");
            ReceivedMessage = true;
            return TaskDone.Done;
        }

#### Notes:

- It seems like when I reduce server log from Verbose to Info, the failure happens much quicker.

- I know for sure that this problem is not caused by my custom stream provider because I can see in the log (when set to "Verbose") that:

  - IQueueCacheCursor.MoveNext is being called successfully returning "true" first time for the first message then "false" the second time because there is only one message.
  - IQueueCacheCursor.GetCurrent is being called successfuly returning the first message.
  - The error (quoted above) happens in StreamConsumerExtension.DeliverBatch inside Orleans itself after it has successfully received the message from my stream provider.

**Comment by jason-bragg** [comment] 2016-01-08 20:03
My suspicion is that this is the same issue as #1010.  Basically the streaming infrastructure has primarily been hardened using non-reentrant grain to grain calls.  The interleaving that can occur when called from reentrant grains, timer threads, or, in this case, Orleans client will break some assumptions in the code.

**Comment by amamh** [comment] 2016-01-08 20:06
This also happens if I manually subscribe in a UI client. In fact, this was originally a problem on the UI client where I would subscribe to different price tickers (each has its stream). I reduced it down to a console client that simulates what I was doing on the UI.

**Comment by angshuman-agarwal** [comment] 2016-01-09 00:41
@jason-bragg _PriceGrain_ is not a re-entrant grain. It's just a high frequency stream of Prices from the Tick Database which we are trying to persist (for snapshot replay) and if the tick happens for the same stock, we just want to update the persistent stream cache. So it is like a Dictionary-based Persistent Stream Provider which uses REDIS as the underlying physical Queue. But as @amamh said, the test for replaying just a single (only one) message, which is not even ticking randomly fails with that error (not consistent) when a client tries to subscribe.

**Comment by jason-bragg** [comment] 2016-01-09 00:59
@angshuman-agarwal 
Thanks for the details.  If I'm understanding the referenced code correctly, the reentrancy of the PriceGrain is not (necessarily) relevant as the stream is being subscribed to from an Orleans Client, which does not have the same reentrancy guarantees as grains do.  Am I mistaken here?  Is the subscribeAsync call being made in the context of an Orleans Client or Grain?

If the subscribe call is moved into the PriceGrain  and the output written to the log instead of console, does this behavior persist?

**Comment by angshuman-agarwal** [comment] 2016-01-09 01:03
> Is the subscribeAsync call being made in the context of an Orleans Client

It is made in context of the Client because we want to bind the output to a WPF Window eventually (example a ticking chart).
If we do the subscription in Grain, then how do we propagate as it will then run on server (SILO). Correct ?

>If the subscribe call is moved into the PriceGrain and the output written to the log instead of console, does this behavior persist?

Have not tried that. I can try that out.

**Comment by gabikliot** [comment] 2016-01-09 01:12
I am a bit confused.
The semantics you described are:

One message is sent on the stream
A subscriber is added
Subscriber expects to receive that message

This are NOT the semantics Orleans streaming provides. We guarantee that a msg that was produced AFTER subscription will be delivered, but we guarantee nothing about msgs produced before.
Neither SMS or Azure Queue provider guarantee what you are asking.

Are you saying that you implement a different steam provider that guarantee that? OK. Are you sure you implemented it correctly? Clearly, the IQueueCacheCursor and all that stuff needs to be implemented differently for that different scenario to work.

**Comment by jason-bragg** [comment] 2016-01-09 01:13
>If we do the subscription in Grain, then how do we propagate as it will then run on server (SILO). Correct?

Correct, I'm not (yet) proposing this as a workaround, only as a diagnostic measure.  We know that the stream infrastructure has issues when called from reentrant grains and timer callbacks because those allow interleaving.  From this, I consider it likely similar issues could manifest when streams are called from the Orleans Client, because it also has threading protections far less strict than non-reentrant grains.  If the issues you're seeing go away when subscribing from the PriceGrain, that would lend credibility to this theory.  Once we're confident we know what the issue is, we'll be in a better place to evaluate potential solutions.

**Comment by amamh** [comment] 2016-01-09 01:14
@gabikliot 

> Note I'm using a stream provider that keeps old messages and sends them always to new subscribers (recovery). T

**Comment by jason-bragg** [comment] 2016-01-09 01:15
@gabikliot 
The subscribe call has the sequence token for the start of the stream, so if messages at that sequence token are still in the cache, they should be delivered.

**Comment by gabikliot** [comment] 2016-01-09 01:15
Well, you can definitely try what @jason-bragg  suggested but I am not sure we are yet ready to suggest what is wrong. Fundamentally, there is a new stream provider, with different semantics. How do we even know it works correctly?

>I'm using a stream provider that keeps old messages and sends them always to new subscribers

How do you know it works correctly?

**Comment by gabikliot** [comment] 2016-01-09 01:17
@jason-bragg , he is using a different cache and different provider. Therefore:

> so if messages at that sequence token are still in the cache, they should be delivered

does not hold any more, right?

**Comment by jason-bragg** [comment] 2016-01-09 01:19
@amamh 
Please correct me if I'm mistaken, but you're using the PersistentStreamProvider with a custom adapter, correct?  You're not using an entirely new stream provider are you?

**Comment by gabikliot** [comment] 2016-01-09 01:20
Jason, he wrote above: he is using https://github.com/amamh/orleans-PipeStreamProvider.

**Comment by amamh** [comment] 2016-01-09 01:20
@jason-bragg 
yes, that's correct.

**Comment by gabikliot** [comment] 2016-01-09 01:22
https://github.com/amamh/orleans-PipeStreamProvider has its own DIFFERENT cache, right?
Its not SimpleCache any more?

**Comment by amamh** [comment] 2016-01-09 01:22
@gabikliot 

> How do you know it works correctly?

because:


>  I can see in the log (when set to "Verbose") that:

> IQueueCacheCursor.MoveNext is being called successfully returning "true" first time for the first message then "false" the second time because there is only one message.
> IQueueCacheCursor.GetCurrent is being called successfuly returning the first message.
> The error (quoted above) happens in StreamConsumerExtension.DeliverBatch inside Orleans itself after it has successfully received the message from my stream provider.

**Comment by gabikliot** [comment] 2016-01-09 01:25
Ohh, maybe I got something:

The error is on the client, right?
You need to root - store a reference to - TestObserver, in global var. Otherwise it is GCed.

**Comment by amamh** [comment] 2016-01-09 01:31
@gabikliot 
let me try that

**Comment by amamh** [comment] 2016-01-09 01:34
@gabikliot 

Nope, didn't work. I stored all observers in a List, but got the same error on the second try.

**Comment by angshuman-agarwal** [comment] 2016-01-09 01:36
@amamh : Can you please upload the sample on GitHub ? The site link what you provided is unsafe.

**Comment by gabikliot** [comment] 2016-01-09 01:39
So let me see I get it right:
1) you have 1 client producing events.
2) 2nd client subscribing to the stream.
3) no grain at all in the picture.
4) the event when published goes to the silo, into the stream provider cache, stored there and resend to the subscriber.
5) you see that the msg arrives to client 2, but is dropped inside Orleans code on the client, with 
"[2016-01-08 17:06:26.393 GMT    18      WARNING 103407  StreamConsumerExtension 127.0.0.1:0]    C127.0.0.1:0:-189968502*cli/36a6d0a5@10c86faa got an item for subscription 7bec8598, but I don't have any subscriber for that stream. Dropping on the floor."

**Comment by amamh** [comment] 2016-01-09 01:44
@gabikliot 
yes, also:

- 1st client only sends one message
- There is a grain but all it does is create a stream so that both clients can get the same stream that's it. Then the two clients use that stream directly. The grain doesn't do anything else so it's safe to ignore it.
- There is only ONE stream.
- That error comes up despite the fact that there is only one stream which does indeed have subscribers (the previous ones). So that error doesn't make sense if I understand it correctly.
- For some reason, changing log severity from Info to Verbose makes it less likely to happen which suggests it's some threading issue that depends on how much load there is on the server. (I think)

**Comment by amamh** [comment] 2016-01-09 01:44
@angshuman-agarwal 
http://expirebox.com/download/d29fc552d8e9d18011e8f2d41073a4f6.html

**Comment by angshuman-agarwal** [comment] 2016-01-09 01:45
@gabikliot 
1) you have 1 client producing events.
Yes.

>2) 2nd client subscribing to the stream.
> 3) no grain at all in the picture.
The client subscribes to the stream via the Grain. So when a new client subscribes, the stream is replayed.


```
var stream = await ccGrain.GetStream();
```


>4) the event when published goes to the silo, into the stream provider cache, stored there and resend to the subscriber.

Yes

**Comment by gabikliot** [comment] 2016-01-09 01:47
There is no such thing as "create stream". Stream are virtual, always exist. You probably mean that the grain returns the identity of the stream. Can you please exclude that from your scenario? Since grain is not playing any part in it, we don't need to complicate it. Just use the same stream Guid in both clients.

**Comment by amamh** [comment] 2016-01-09 01:48
@gabikliot 
yeah, it just returns the same stream to both clients. I can remove that.

**Comment by gabikliot** [comment] 2016-01-09 01:50
I can not download any zip files. Please put all code on GH, in public open repository. I can only look at open source code on GH. And please remove the grain.

**Comment by gabikliot** [comment] 2016-01-09 01:51
@jason-bragg , I now tend to think that you are right and it is maybe the same issue as #1010 - non-atomic subscription.

**Comment by amamh** [comment] 2016-01-09 01:55
@gabikliot 
Removed the grain and now I get the same stream on both clients directly. Exact same error as before with the same notes as before.

**Comment by amamh** [comment] 2016-01-09 02:02
@gabikliot 
https://github.com/amamh/PersistentStreamFail

**Comment by amamh** [comment] 2016-01-09 02:09
@gabikliot 

> If I have a clear code that I can run (without any external dependencies, like installing Redis) and I can reproduce the bug, I am pretty sure I will be able to fix it during the weekend.

You don't need to install redis, you just need to run the .bat file in the redis folder, it's self contained.
The dll for my provider is also contained in the repo.

You should be able to run my repo without any problems:

- Run Redis\RUN.bat
- Run solution.

**Comment by angshuman-agarwal** [comment] 2016-01-09 02:26
@gabikliot @jason-bragg  - Will be great if you are also able to review the Provider code. I liked the idea of #1245 _PooledCache_. Will try to modify the cache implementation on similar lines as the requirements are pretty much same (except purging). I reckon the current provider cache will have performance degradation due to garbage collection (GEN2) as it will be growing & storing gigs of price data for the whole day (~8 hours).

**Comment by gabikliot** [comment] 2016-01-09 07:23
I think I fixed it in #1261.
Even before it is merged you can try to take this commit, build a private set of Orleans dlls and check if it indeed fixes your setup. The fix applies only to Orleans.dll but I recommend you take all dlls, since there may be some incompatible changes between 1.1.0 nuget and latest master.

**Comment by amamh** [comment] 2016-01-09 10:18
Great, I'll check it

**Comment by amamh** [comment] 2016-01-09 16:30
@gabikliot 

is there a way to quickly replace all NuGet Orleans packages with dlls from my own Orleans source? I tried adding NuGet folder in Orleans as a local source for NuGet but that didn't work.

**Comment by veikkoeeva** [comment] 2016-01-09 17:10
@amamh You can [add a new local source](https://docs.nuget.org/create/hosting-your-own-nuget-feeds) or add a [local Nuget configuration file](https://docs.nuget.org/consume/nuget-config-file) (it does basically the same as adding the another source). You need to remove the Orleans Nuget packages from the project `packages` to be able to load the newly build packages and maybe to remove Orleans packages from the cache at `%USERPROFILE%\.nuget\packages`.

**Comment by amamh** [comment] 2016-01-09 19:03
@veikkoeeva 

Why can't I add Orleans\src\NuGet as a local source?

**Comment by amamh** [comment] 2016-01-09 20:06
@gabikliot  Sorry, I'm having some trouble testing at the moment. I'm faced with another random error so I can't even run my project any more with/without your change:

		Named type "Entities.Price" is invalid: Type string "Entities.Price" cannot be resolved.
		Exception = System.TypeAccessException: Named type "Entities.Price" is invalid: Type string "Entities.Price" cannot be resolved.

Which doesn't make sense because I do have my project Entities as a reference.

It might be related to the warning thrown by the compiler:

			Severity	Code	Description	Project	File	Line	Suppression State
			Warning		Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.FixAnalyzers.CSharpFixerWithFixAllAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'Microsoft.CodeAnalysis.Analyzers.FixAnalyzers.FixerWithFixAllAnalyzer`1' threw an exception.'.	Producer	D:\Code\PersistentStreamFail\Producer\CSC		



Looks like it's related code generation.

**Comment by gabikliot** [comment] 2016-01-09 20:15
Yes, this part didn't work for me too. I just changed it to int. You can try fixing it by adding known type/ known assembly. It was added recently, look on git hub. Anyway, that is totally unrelated, let's not confuse this issue with it.

**Comment by amamh** [comment] 2016-01-09 20:17
@gabikliot 

I wonder why it didn't happen before. It works now after deleting "[Immutable]" attribute

**Comment by veikkoeeva** [comment] 2016-01-09 20:20
@amamh Mm, I may have phrased it poorly. You should be able to add `Orleans\src\NuGet` as your source. In fact, you must. What I mean about removing is that when you "press F5" to build and debug, you naturally would like to have your custom built Orleans binaries to be loaded from the `packages`. Because they have the same version number and they exist, they are not updated. So, you remove them and they get reloaded from your local source. Though it might so happen they get loaded from the cache and not from `Orleans\src\NuGet`, this is just a precaution if it looks like nothing happens.

You can get the the same effect by copying the appropriate `.dll` and `.pdb` files from your local Orleans project to either `packages` or to `bin\<configuration>`, but personally I just usually throw away the Orleans directories from `packages`. I don't know if there's a more straightforward way (maybe using a local Nuget configuration file).

**Comment by amamh** [comment] 2016-01-09 20:26
@veikkoeeva  Why can't I see any packages in NuGet manager if I select that folder as my source?

**Comment by amamh** [comment] 2016-01-09 20:36
@gabikliot 

After finally sorting out my issues, **applying your change to 1.1.0 and replacing Orleans.dll only on the 2nd client (receiver) side** seems to have fixed the issue.

**Comment by gabikliot** [comment] 2016-01-09 21:16
Great! That validates the fix. The fix is indeed only needed on the receiving client.

**Comment by angshuman-agarwal** [comment] 2016-01-09 23:17
Thanks @gabikliot!!

>I wonder why it didn't happen before. It works now after deleting "[Immutable]" attribute. Maybe I should open another issue about this later..

Is this still an issue?

**Comment by amamh** [comment] 2016-01-11 09:34
@gabikliot I've done some further testing and I'm pretty sure now that your fix works. Hopefully we can have this fix in the next stable release.

@angshuman-agarwal I'm still not sure what was causing that problem, it works fine on my other computer. I will open another issue about it with another reproducible project.

**Closed** 2016-01-11 09:34 UTC
Labels: under-investigation

**Comment by angshuman-agarwal** [comment] 2016-01-11 10:22
:+1: great !

**Comment by jason-bragg** [comment] 2016-01-11 18:45
@angshuman-agarwal  
>I liked the idea of #1245 PooledCache. Will try to modify the cache implementation on similar lines as the requirements are pretty much same (except purging). 

Modifying the cache to not purge should not be hard.  Simply use an ObjectPool instead of a FixedSizeObjectPool to allocate FixedSizeBuffers.  However, this will load data forever and will eventually cause the server to crash.  Alternatives are to set the pool size to roughly the maximum memory available for caching on the silo, or implement a custom daily purge.

**Comment by jason-bragg** [comment] 2016-01-11 18:46
@gabikliot 
Great work.  Thanks!

**Comment by angshuman-agarwal** [comment] 2016-01-11 19:21
@jason-bragg 
Thanks for the inputs - I have basically 3 different Stream Provider reqs -
1. _Time-bound cache_ (10 mins of Sliding Window i.e. keep history of latest 10 mins always )
2. _Load everything_ (here the data per day will be ~8GB RAM and at EOD evrything will be wiped out). It will be a Dictionary-based cache which will replace existing keys' values. 
3. _SMS Provider_ i.e. do not cache anything. Just fire what is being streamed.Simple and straightforward.

So, preferably, will use the PooledCache for point 1 (i.e. roughly map the time constraint to how much bytes I will receive in that time interval at peak load) and for point 2 - (what you suggested). Hope it makes more sense now. 

Thanks again for reading through and suggesting. We are rigorously prototyping various scenarios with Orleans and coming up with all sorts of silly questions.

**Comment by jason-bragg** [comment] 2016-01-11 20:38
@angshuman-agarwal
Your approach makes sense.  The GC issues may not be a problem for you, depending on your perf needs, but if they do show up, porting to the PooledCache should help.

Glad to see you guys banging on the streaming tech.  We developed a lot of tech rapidly and not all use cases have been hardened.  Glad to see you all getting value from it, and hope you all can find time to contribute fixes back as you find issues.

**Comment by angshuman-agarwal** [comment] 2016-01-12 07:20
Thanks @jason-bragg

**Comment by gabikliot** [comment] 2016-01-13 03:25
Fixed via #1261.
