### ISSUE TITLE
Handling multiple environments / versions of a cluster

### ISSUE THREAD

**Issue by rore** [dotnet/orleans#320] opened 2015-04-12 18:22 UTC
Hi 

We're struggling with questions around handling versioning and environments of an Orleans application (details ahead), and I'm hoping there might be some directions or tips on how to handle this. If there was already a discussion about this (I didn't find one), please point me to it. 

The situation in question:

You (we) have an Orleans application, and there are state-full grains in it. 
Now we want to deploy a new version of the application. There are two main steps for deploying a new version: 
1. Upload the new version to a staging environment. In this phase the old and the new version lives side by side, and the new version is being tested.
2. Deploy the new version to production. Since this requires a cluster restart, it actually means deploy the new version to a new cluster, and then "switch" between the old and new clusters.

Both this steps contain a bag of problems with handling grains and their states.
For the sake of the example, lets assume we have in the application a _UserGrain_ that represents the state of a user. 

So while in staging, if the same user switches between staging and production, there may be a conflict between the states in each environment. Since there's a _UserGrain_ for the user in each environment, each holding its own state, they will be different (even if it gets persisted, the other grain in the second cluster does not know it needs to refresh its state).

A different flavor of the problem appears when switching between the old and new versions. This is never a "singular point in time" event (unless you can sustain downtime, which you normally can't). This means that there might be requests that are still handled by the old version while the new version is already up. So again - a _UserGrain_ of a user might change state in the old version while this not being recognized by the new version. 

This can be potentially handled by "streaming" all changes from the old version to the new version, but this seems to be a huge overhead and complication to the system. 

Are there any best practices for handling this? How do you handle production changes?

**Comment by sergeybykov** [comment] 2015-04-13 14:51
There are two key cases here: 

1) Non-breaking change to implementation.
2) Breaking change to grain interfaces and/or implementation.

Case 1) is obviously much simpler and allows for a rolling in-place upgrade with no downtime where one update domain is upgraded and restarted at a time. Orleans Membership treats such restarts as silo failures and reacts accordingly.

Case 2) where you cannot have silos with different versions of code running in a single cluster is naturally more complicated. The only option with no downtime today is a VIP swap to a staging deployment, as you mentioned. You are correct that in such a case you may end up with two activations of a grain in two deployments. There are two problems with that.

1. Conflicting updates. They are usually prevented via the standard eTag-based versioning technique. Event sourcing is another option.

2. Reads that return stale data. Strategies here depend on application's tolerance of staleness. In some cases it's totally okay if such state is an eventually consistent approximation. In other cases bounded staleness (and hence state refresh) is required. The extreme case is serving every request with a read from storage, which defeats the purpose of the grain being stateful.

We started thinking through the story of in-place versioning/upgrade that wouldn't require VIP swapping between production and staging. But this thinking is in its infancy at the moment.

**Comment by rore** [comment] 2015-04-13 15:08
Thank you for the answer. 

Just to note, even in case 1, where there's no breaking change, you probably want to test the new version in a staging environment (and not as part of your production cluster). So the problem with duplicate activations across different deployments can still appear.

**Comment by sergeybykov** [comment] 2015-04-13 15:20
Wouldn't you test staging against a set of test/fake users that wouldn't overlap with the real ones? Otherwise, you are right - it's the same problem.

**Comment by rore** [comment] 2015-04-13 15:33
Sometimes yes, but there are patterns of doing "canary" deployments where you want to test with a fraction of your traffic to verify the version. So you might have users that will switch between environments at some point.

**Comment by sergeybykov** [comment] 2015-04-13 15:37
That's one of the reasons we are looking at the in-place versioning/upgrade story.

**Comment by gabikliot** [comment] 2015-04-13 16:41
@rore , just out of curiosity, how were you handling those scenarios before Orleans? Seems like the problem is generic and is not Orleans-specific.

**Comment by rore** [comment] 2015-04-13 18:33
@gabikliot , true, in a sense it's a generic problem, but it's less central in non-Orleans applications. In a regular distributed stateless application you don't have a concept of a "cluster singleton" that keeps its state. Requests can go to any server, so you always read the state and persist, either to a DB or more commonly to a shared cache (like memcached). 

You can, of course, do the same in Orleans. But that defeats the whole purpose of the single-activation grain, which is one of the biggest advantages of Orleans.

**Comment by weitaolee** [comment] 2015-04-14 03:13
CQRS maybe one choice. at least , you can update it with a available queue side.

**Comment by gabikliot** [comment] 2015-04-14 05:04
That makes sense @rore.

**Comment by yaronthurm** [comment] 2015-05-11 07:17
As for the cluster switch problem, what do you think about the following solution:

During the migration process from the old cluster to the new one, we will maintain a persistent list of all grains that have already been migrated (at first the list will be empty).
Any new activation in the new cluster will have to first check the list to see whether or not the newly activated grain has been migrated.
If the grain is in the list, activation can proceed as normal.
If the grain is not in the list (which is expected), activation should send a "migration request" to the "twin" grain in the old cluster (probably via an intermittent service that receives migration requests from the new cluster and forwards them to the corresponding grain in the old cluster) and `await` the response.
When the grain in the old cluster receives the "migration request" it will do whatever clean-up tasks it has to do, mark itself as migrated (so that any future messages will be rejected) and add itself to the list of migrated grains (so that any new activation will know that the grain was migrated). It will then return an *Ack* response
When the grain in the new cluster receives the *Ack* response it can safely proceed with it's normal activation flow.

With that process, we can simply configure our front-end servers to diverge traffic from the old cluster to the new one until 100% of the traffic hits the new cluster.
We should wait until all pending tasks from the old cluster finish, and then shut the old cluster down and end the migration process.

Open issues:
1. Requests to the old cluster may hit a grain that has already been migrated. Should we fail the request or should we "redirect" it to the new cluster?
2. We need a way to gracefully shut the old cluster cluster down, so any non-migrated grains will have a chance to do whatever clean-up job (i.e. flushing the state, disposing any pending timers).

**Comment by gabikliot** [comment] 2015-05-11 20:14
@yaronthurm , what you have described is essentially what @sergeybykov wrote above: "We started thinking through the story of in-place versioning/upgrade that wouldn't require VIP swapping between production and staging."

The design would indeed work something like you described. Of course, there are a lot of next level details to handle. But in general sounds like this should be possible. Of course, if you now add a requirement to roll back if there is a bug in the new version and you detected it while rolling forward, then this becomes even more complicated.

For your questions:
1. Yes, we have to fail the request to the old one and forward to the new clsuter, right? Otherwise, we will be back at 2 activations. So you need some kind of "don't create any more new activations state" in the old cluster and forward to the new cluster logic.
2. Sure, we need a way to gracefully shut the old cluster. We need this even unrelated to the version upgrade problem. There is already an open issue on that:https://github.com/dotnet/orleans/issues/381

How about we strike a deal: we will do graceful shutdown and you guys will do the in-place upgrade along the lines that you have suggested?  :-)

**Comment by yaronthurm** [comment] 2015-05-13 06:57
@gabikliot,
That sounds like a fair deal.
I will give it a try.

Thanks.

**Comment by gabikliot** [comment] 2015-06-05 00:26
@yaronthurm, graceful shutdown has been implemented. Issue #381 is now closed.

**Comment by wizzard0** [comment] 2017-07-16 20:46
Was there any updates on this? Documentation is still very shy on versioning issues and best practices, and we're considering this as a serious issue before adopting Orleans in production

**Comment by sergeybykov** [comment] 2017-07-18 20:16
There's been some progress on versioning recently: http://dotnet.github.io/orleans/Documentation/Grain-Versioning/Grain-versioning.html and http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Heterogeneous-Silos.html.

**Comment by ReubenBond** [comment] 2021-04-06 18:31
I'll close this since Orleans supports heterogeneous clusters. Some teams use rolling upgrades and other use blue/green deployments, and some use a mix. #2653 covers version-tolerant serialization, which is another aspect of this. We can open other issues for specific concerns as they arise.

**Closed by ReubenBond** 2021-04-06 18:31 UTC
Labels: P2, enhancement
