### ISSUE TITLE
QueueCacheMissException

### ISSUE THREAD

**Issue by Merroy** [dotnet/orleans#844] opened 2015-09-25 15:41 UTC
```
ERROR 103315 PullingAgentSystemTarget/FF/10c6da8d-Reader1 10.3.5.21:11111] !!!!!!!!!! Ignored RunConsumerCursor Error Exc level 0: Orleans.Streams.QueueCacheMissException: Item not found in cache. Requested: [EventSequenceToken: SeqNum=239, EventIndex=0], Low: [EventSequenceToken: SeqNum=242, EventIndex=0], High: [EventSequenceToken: SeqNum=274, EventIndex=0] в Orleans.Providers.Streams.Common.SimpleQueueCache.InitializeCursor(SimpleQueueCacheCursor cursor, StreamSequenceToken sequenceToken) в Orleans.Providers.Streams.Common.SimpleQueueCache.TryGetNextMessage(SimpleQueueCacheCursor cursor, IBatchContainer& batch) в Orleans.Providers.Streams.Common.SimpleQueueCacheCursor.MoveNext() в Orleans.Streams.PersistentStreamPullingAgent.<RunConsumerCursor>d__46.MoveNext()
```

Wanted to raise a discussion on the topic `QueueCacheMissException`
The situation in which this error occurs is this:
I run silo. I send a packet of data for processing in the stream (or multiple streams which are independent of each other, but more on that later), for example is 250 messages of type string.
Everything works fine, all messages processed. The queue and the stream is empty. 
Then, again I send this packet in the stream and get the error described above.
Why?
A data package in my opinion is not big and processed it quickly.
Changing cache size didn't help.
And if I understand correctly then for some reason knocks the cursor.

**Comment by Merroy** [comment] 2015-09-25 15:57
About multiple related streams, I have the following structure:
I have one producer who takes all and the message and puts it in the stream, and there is one consumer who has subscribed to the stream (before there began to be reported), he receives the message and shares (in parallel), depending on certain characteristic of several streams.
Шn other words, in the second step I have a one producer, several streams, and one consumer on a every of the streams.

**Comment by Merroy** [comment] 2015-09-25 16:40
By the way I'm using RabbitMQ, the implementation can be found here
https://github.com/Merroy/Orleans/tree/master/Orleans.StreamProviders
Implemented by analogy with AQ, published in a hurry, will edit later repository

**Comment by gabikliot** [comment] 2015-09-25 17:12
@Merroy , lets tackle those issue one by one.
The first issue. Let me verify the scenario:
1) we are talking about Persistent Stream Provider with your own custom Queue Adapter (RabbitMQ) right?
2) There is only 1 stream
3) 1 consumer - is it explicit or implicit consumer?
4) 1 producer.
The order of events is:
a) Consumer subscribes to a stream (if it is an explicit consumer).
b) Producer produces.
c) Consumer get the meg
d) Producer produces the 2nd time.
e) you get the above error and the consumer never gets anything.

Is all I described above correct?

**Comment by Merroy** [comment] 2015-09-25 17:26
1)Yes
2)Almost, in the first step - Yes, but then the consumer that processed the message "call" another stream
3)explicit 
4)Yes (almost, see paragraph 2, after processing the message by the consumer, pecet turn to another producer, who works with another stream)

Yes, except that after item "c" is followed by another stream after the second stream "finished his work" go to step "d"

**Comment by gabikliot** [comment] 2015-09-25 17:32
Sorry, I don't understand the scenario now. I don't understand what "Yes, except that after item "c" is followed by another stream after the second stream "finished his work" go to step "d"" means.
Can you please describe the full scenario step by step, in detail.

**Comment by Merroy** [comment] 2015-09-25 17:41
0) I send a message to the Producer1
1) Consumer1 subscribes to a Stream1
2) Producer1 produces
3) Consumer1 get the message
4) Сonsumer1 transmits the message Producer1
5) Consumer2 subscribes to a Stream2
6) Producer2 produces
7) Consumer2 get the message
8) The end of processing
9) I send a message to the Producer1
10) I get the error

**Comment by Merroy** [comment] 2015-09-25 17:54
![default](https://cloud.githubusercontent.com/assets/4007564/10108091/a46f46e8-63c7-11e5-8404-78757ef3441b.png)

**Comment by gabikliot** [comment] 2015-09-25 18:16
>4) Сonsumer1 transmits the message Producer1
Is that a typo? Should it be to Producer 2?

Can we simplify the scenario and cut the 2nd part: cut Producer 2 and consumers 2 from the scenario, just for testing?
So do 1 to 3 and then 9 and 10.
Does that still result in error?

**Comment by Merroy** [comment] 2015-09-25 18:19
> 4) Сonsumer1 transmits the message Producer1
> Is that a typo? Should it be to Producer 2?
yes, I fixed, there Producer 2

**Comment by Merroy** [comment] 2015-09-25 18:28
>Can we simplify the scenario and cut the 2nd part: cut Producer 2 and consumers 2 from the >scenario, just for testing?
>So do 1 to 3 and then 9 and 10.
>Does that still result in error?

there is no error, all right

**Comment by gabikliot** [comment] 2015-09-25 18:35
OK, so the streams that producer 2 produces to, those are different streams (different stream id)? But in the same stream provider and go via the same queue?

**Comment by Merroy** [comment] 2015-09-25 18:45
if we consider a chain of producer2 - consumer2, stream ID are the same, but the namespace is different. Yes

**Comment by Merroy** [comment] 2015-09-25 21:13
I made a different ID of the stream, and it seems the problem is gone (continue testing)
is there a difference? as I understand it in my previous version ID + namespace anyway given the uniqueness

**Comment by gabikliot** [comment] 2015-09-25 21:41
Indeed, Guid +string namespace together are supposed to be unique, and there should not be a difference between changing the string or the Guid. But maybe there is a bug somewhere, either in Orleans or in your adapter (maybe in the stream queue mapper?). I will take a look at your adapter code later on. Perhaps I will spot something. 
Its hard for me to debug this issue since it is not in Azure Queue adapter, so I cannot run it. If you could re-create the problem with AQ provider and submit a test to GH, that would be a huge help, and will most certainly allow us to find the bug. On the other hand, if you will try to re-create the problem with AQ provider but would not be to re-create it, it will point out in the Rabbit MQ adapter potential bug.

**Comment by Merroy** [comment] 2015-09-25 22:01
I have some time I will recheck everything and test, especially adapter, and tomorrow, in any case, I will write a more detailed response on this issue
once again I would like to clarify: do I understand correctly that the idea of orleans:
guid1 + string1
guid1 + string2
guid2 + string1
guid2 + string2
this is a totally different unrelated streams?

**Comment by jason-bragg** [comment] 2015-09-25 22:04
One possibility is that a queue was moved from one silo to another while your test was running.  Not a likely scenario, but possible.  A couple more questions, if you don't mind.

How many silos are you running in your test?
How many queues are you using?
What queue balancer do you have configured?  If not configured, just say default.
Are you running the test <2 minutes after the silos start?

**Comment by jason-bragg** [comment] 2015-09-25 22:08
"... this is a totally different unrelated streams?"
Yes, those should all be treated as unique streams.

The default queue mapper will place all the streams with the same streamGuid on the same queue, so the first two streams you described would be serviced by the same receiver and end up in the same cache, but that should not matter to consumers or producers.

**Comment by Merroy** [comment] 2015-09-25 22:18
1)3 silo
2)18 queues 
3)what do you mean "queue balancer" ?
4)I have different tests that I can run immediately after the start, an hour later, one test may last several hours

**Comment by jason-bragg** [comment] 2015-09-25 22:36
When using persistent stream providers, the queues readers are distributed across all of the running silos.  So in your case about 6 queues per silo.

The algorithm for how to balance the queues is call the "QueueBalancer".

The reason I was asking about is that when the cluster is spinning up, depending on which queue balancer you're using, the queues may be shuffled around.  If a queue starts delivering events to a grain, and then the queue moves, it could cause a cache miss.

This would only be an issue around startup or if there is a silo outage, so it's not likely the cause.  I just wanted to rule it out.

**Comment by Merroy** [comment] 2015-09-25 22:53
Interesting, I certainly noticed when a silo becomes responsible for a certain line, but did not think and did not come across information that it is possible to configure.
Can you direct me a link to an article or documentation with which I could become more familiar and to explore this topic in more detail?

**Comment by Merroy** [comment] 2015-09-25 23:10
```
_streamQueueMapper = new HashRingBasedStreamQueueMapper(_numQueues, providerName);

public async Task QueueMessageBatchAsync<T>(Guid streamGuid, string streamNamespace, IEnumerable<T> events, StreamSequenceToken token, Dictionary<string, object> requestContext)
        {
            var queueId = _streamQueueMapper.GetQueueForStream(streamGuid, streamNamespace);
..
```
I noticed that if different combinations streamGuid and streamNamespace I can get the same queueId, is this correct?

**Comment by jason-bragg** [comment] 2015-09-25 23:15
"if you take one message and pass through this circuit once, then everything is fine, if re-send the message from client, it will error
 if at the same time in a row to send multiple messages at a time when the stream is still working, then everything is fine, if you wait until all messages will pass the entire chain and re-send them, it will error"

Hrmm..   I don't believe this is an issue in you're adapter.  To reduce the time messages are kept in the cache, hence allowing us to free them up in the underlying queue (good for Azure Queues) quickly, we've recently made the cache purge data very aggressively.  I don't think we've covered all the edge cases for this behavior sufficiently.

I'll add a test to confirm this, but I suspect that the cache cursor for the first stream is becoming inactive while there is data still being delivered on the second stream.  Since data is being delivered on the second stream the cache is moving forward in time and when we try to refresh the cache cursor for the first stream, it is older than any of the data in the cache, so it throws a cache miss.

**Comment by Merroy** [comment] 2015-09-25 23:28
why "good for Azure Queues"? if in RabbitMQ and AQ all boils down to three operations: get, add, delete. At least I haven't noticed RabbitMQ was working with them for a long time.
on all threads a single cursor, is this normal? or I not so understood something?

**Comment by jason-bragg** [comment] 2015-09-26 00:07
'Good for azure queues'
If messages read from azure queue are not deleted in a timely manner, they will show up again.  When messages are purged from the cache, they are considered 'free for deletion'.  So if messages are held in the cache too long duplicates will show up from Azure Queue.

In the PersistentStreamPullingAgent, which is the component that delivers messages to consumers, each consumer has it's own cursor into the cache that notes where it was reading from.  When there is no more data to deliver to a consumer on a stream the consumer's cursor goes 'inactive'.  When new data shows up the cursor will be 'refreshed' and start delivering events again from the last point it knew of.  With the more aggressive purging, the point in the cache where the inactive cursor was last pointing is no longer valid, so when it is 'refreshed' it will throw a cache miss exception. 

As stated, this is my theory, I still need to create a repro to verify.

**Comment by jason-bragg** [comment] 2015-09-26 01:15
plz see pull request QueueCacheMissException #844 Fix #849 
Contains repro and fix

**Comment by jason-bragg** [comment] 2015-09-26 01:19
@Merroy  Thanks for finding this issue.
We're working on more comprehensive test coverage that should reduce the likelihood of such issues in the future.

**Comment by Merroy** [comment] 2015-09-26 07:34
Do I understand correctly that this will be fixed in Nuget only in 1.0.11 ?

**Comment by gabikliot** [comment] 2015-09-26 17:31
It will be fixed soon, the official signed Nuget will indeed be 1.0.11 (later on), but you can always build everything locally by just running Build.cmd, it produces local nugets and you can just drop them into your app.

**Comment by Merroy** [comment] 2015-09-26 19:11
thanks, I look forward to the fixes

**Comment by gabikliot** [comment] 2015-09-30 19:12
@Merroy , #849 has been merged.
Can you please validate that it indeed fixes your problem? Thanks.

**Comment by Merroy** [comment] 2015-09-30 19:21
@gabikliot Okay, I'll check in soon

**Comment by Merroy** [comment] 2015-10-05 18:52
judging by the first tests everything works, but in practice it is noticed that the stream is slower (perhaps thought)

**Comment by jason-bragg** [comment] 2015-10-05 19:53
The fix should not have effected performance.
Given that the topology you described requires two hops through storage, the cost of the grain calls and stream infrastructure should not be significant.
There are things that can be done to optimize the Orleans streaming cost (prefer local grains, implicit subscriptions, ..) but if you're confident in the correctness and are moving to optimization, I'd suggest adding performance metrics to identify where time is being spent.

**Comment by Merroy** [comment] 2015-10-05 20:12
I think this thread can be closed. problems not yet revealed.
questions on stream I'm gonna ask a little later in the topic https://github.com/dotnet/orleans/issues/850

**Closed** 2015-10-05 20:25 UTC
Labels: bug, question, under-investigation
