### ISSUE TITLE
Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#6488] opened 2020-04-16 14:15 UTC
We have a lot of ConnectionResetException errors on localy and production environment.
On production we use service fabric. On each node installed both  silo as stateless service and clients as docker web applications. We use the azure table cluster provider.
This error began to appear on recent versions of Orleans
Localy the client and silo run on the same machine. 
How to get rid of them?

Thanks

```
Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<ProcessReceives>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Networking.Shared.SocketConnection.<DoReceive>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Orleans.Runtime.Messaging.Connection.<ProcessIncoming>d__55.MoveNext()

```

**Comment by ifle** [comment] 2020-04-17 16:30
Forgot to note that we use .net 472

**Comment by BenjaminGibbsMorris** [comment] 2020-04-30 03:31
I am seeing the same issue.

We upgraded our application from from 2.x to 3.x and we are seeing the same issue. We are running on Service Fabric as well, as stateless workers like you @ifle.

We are currently on Orleans 3.1.6

**Comment by ReubenBond** [comment] 2020-04-30 15:30
I believe this is probably being caused by some other issue (eg, silo being killed), rather than something in the networking layer, so other logs are helpful

**Comment by ifle** [comment] 2020-04-30 19:12
This error caused also when silo is not being killed. Small example from Application Insights log. 
As you can see between log entries there are not any errors related to killed silos.

![image](https://user-images.githubusercontent.com/1140474/80748924-5e980900-8b2e-11ea-8ec9-5bf1d917c646.png)
 
Unfortunaly, only following error writed to log
```
Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<ProcessReceives>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Networking.Shared.SocketConnection.<DoReceive>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Orleans.Runtime.Messaging.Connection.<ProcessIncoming>d__55.MoveNext()

```

**Comment by ifle** [comment] 2020-05-01 12:13
This error we have on local environment when silo being started
```
[12:29:42 WRN] Exception while processing messages from remote endpoint 127.0.0.1:1390: Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<ProcessReceives>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<DoReceive>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Orleans.Runtime.Messaging.Connection.<ProcessIncoming>d__55.MoveNext()
Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<ProcessReceives>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<DoReceive>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Orleans.Runtime.Messaging.Connection.<ProcessIncoming>d__55.MoveNext()

```

**Comment by ReubenBond** [comment] 2020-05-01 13:08
The exception says "An existing connection was forcibly closed by the remote host", so you ought to see other logs (from the "remote host" / other silo) detailing why it's closing the connection.

**Comment by ifle** [comment] 2020-05-01 13:33
Last example of error dtom localhost one silo cluster. 
It try to connext to port 1390. Strange.127.0.0.1:1390

**Comment by ReubenBond** [comment] 2020-05-01 13:36
Is clustering misconfigured, perhaps? Could you show the clustering table?

**Comment by ifle** [comment] 2020-05-01 16:39
For clarification. 
Following error I have on my local dev machine. Localhost cluster, one silo. It caused during starting of silo. Silo continue loading and all working as expexted. I have not any configuration with port 1390. 

```
[12:29:42 WRN] Exception while processing messages from remote endpoint 127.0.0.1:1390: Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<ProcessReceives>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<DoReceive>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Orleans.Runtime.Messaging.Connection.<ProcessIncoming>d__55.MoveNext()
Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<ProcessReceives>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<DoReceive>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Orleans.Runtime.Messaging.Connection.<ProcessIncoming>d__55.MoveNext()


````


This one we have on production environment on SF with azure table clusrer. 

```
Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Orleans.Networking.Shared.SocketAwaitableEventArgs.GetResult()
   at Orleans.Networking.Shared.SocketConnection.<ProcessReceives>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Networking.Shared.SocketConnection.<DoReceive>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Orleans.Runtime.Messaging.Connection.<ProcessIncoming>d__55.MoveNext()

```

**Comment by ReubenBond** [comment] 2020-05-01 17:02
Can you dump the OrleansSiloInstances table from Azure Table Storage and send it to me?

**Comment by ifle** [comment] 2020-05-01 17:22
@ReubenBond 
I sent you dump the OrleansSiloInstances table from Azure.

Thanks

**Comment by ReubenBond** [comment] 2020-05-01 17:27
Thank you. Looking at the table, I do see that silos were voted dead.

My hunch is that is unrelated to these particular exceptions. I would be interested to see logs from those silos.

**Comment by ifle** [comment] 2020-05-01 18:02
Unfortunaly we write to log warnings and errors only. No inforamtion severity level

**Comment by ifle** [comment] 2020-05-02 14:14
@ReubenBond 

I sent to you the silo log file from my local environment. I hope this could help

Thanks

**Comment by ReubenBond** [comment] 2020-05-02 17:56
Thanks, I see in this case that the error is just a normal connection reset by a client that's connecting

**Comment by ifle** [comment] 2020-05-19 06:18
This error is very noisy. Is there any option to disable it?

![image](https://user-images.githubusercontent.com/1140474/82291309-6c181480-99b1-11ea-976a-795b168af65f.png)

**Comment by ReubenBond** [comment] 2021-04-06 18:05
Closing since this noise has been substantially reduced now, in 3.4.2. See #6762 & #7006

**Closed by ReubenBond** 2021-04-06 18:05 UTC
