### ISSUE TITLE
Adding [PreferLocalPlacement] to grains causes placement timeout exceptions

### ISSUE THREAD

**Issue by creyke** [dotnet/orleans#2272] opened 2016-10-07 16:25 UTC
As per the issue title.

When we try and prefer local placement we large numbers of both of the below placement exceptions:

Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: NewPlacement Request S192.168.57.169:22222:213551971*grn/BEA129CD/00000000@fc94258e->S192.168.57.192:22222:213552014*grn/2C1481B1/00000000@6f9046bf #30721: global::Orleans.Streams.IStreamConsumerExtension:DeliverImmutable(). Target History is: <S192.168.57.192:22222:213552014:*grn/2C1481B1/00000000:@6f9046bf>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.

Orleans.Runtime.Catalog+DuplicateActivationException: DuplicateActivationException

**Comment by jdom** [comment] 2016-10-07 16:40
You are seeing this only when you upgrated to 1.3.0-beta2?
You are using the multi-cluster feature, correct? Do you experience the same thing when only 1 cluster is active?
Any more contextual information would be very valuable

**Comment by sergeybykov** [comment] 2016-10-07 18:58
`DuplicateActivationException` is by design, should be reported as an Info event. That's how racing activation requests are resolved.

The first one is a bit unclear. Is silo 192.168.57.192:22222 actually part of the cluster when this error is logged?

**Comment by creyke** [comment] 2016-10-08 19:04
No info on previous versions I'm afraid. First time we've used the attribute. Will check whether had joined Monday but we basically ran exactly the same code (other than without the attribute) multiple times both with and without it and only get these errors with it each time.

**Comment by sebastianburckhardt** [comment] 2016-10-10 13:48
I think this is a bug in `PreferLocalPlacementDirector.OnAddActivation`. Unlike the `RandomPlacementDirector.OnAddActivation`, it does not check if the local silo is actually active, thus it may place a new activation on a silo that is shutting down. This is consistent with the text of the error message (the silo being shut down cannot  create the new instance).  

My proposed fix #2276 is to revert to random placement if the local silo is not active.

**Comment by sebastianburckhardt** [comment] 2016-10-10 19:11
@creyke, if you want to test if this actually fixes your problem (perhaps it only fixes a symptom) use the branch https://github.com/sebastianburckhardt/orleans/tree/geo-samples-2272.

It's the same as the geo-samples branch but with this fix cherry-picked.

**Comment by creyke** [comment] 2016-10-11 07:32
Thanks @sebastianburckhardt - we are now doing this.

**Comment by sergeybykov** [comment] 2016-10-12 17:14
Resolved via #2276.

**Closed by sergeybykov** 2016-10-12 17:14 UTC
