### ISSUE TITLE
RegisterStorageProvider using AdoNetStorageProvider

### ISSUE THREAD

**Issue by NicklasNielsen** [dotnet/orleans#2389] opened 2016-11-04 09:32 UTC
I'm trying to register my Local MSSQL database as my StorageProvider for my Grain State following the dokumentation from: [https://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Grain-Persistence.html#ADONETPersistenceRationale](url)
I also added the [StorageProvider(ProviderName = "MyStorageProvider")] to my grain with the state
```
Props[AdoNetStorageProvider.DataConnectionStringPropertyName] =
                @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=test;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;";
Props[AdoNetStorageProvider.DataConnectionInvariantPropertyName] =
                @"MyConnection";
                
config.Globals.RegisterStorageProvider<AdoNetStorageProvider>("MyStorageProvider", Props);

config.Globals.RegisterStreamProvider("Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProvider", "MyStream");
```

I get the following error:

```
ERROR Exception initializing provider Name=MyStorageProvider Type=[MyStorageProvider, Orleans.Storage.AdoNetStorageProvider]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.SqlUtils.DbConnectionFactory.GetFactory(String invariantName)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.SqlUtils.DbConnectionFactory.CreateConnection(String invariantName, String connectionString)
   at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior)
   at Orleans.Storage.AdoNetStorageProvider.<Init>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.ProviderLoader`1.<InitProviders>d__7.MoveNext()
```

I found this on StackOverflow:
[http://stackoverflow.com/questions/36454272/using-sql-server-as-orleans-storage](url)

But it seems like this is outdated as it uses Orleans 1.1.3 and I'm using 1.3.0, and also the StateMapFactory isn't a part of SQLUTIL anymore (or atleast not what I'm aware of)

**Comment by veikkoeeva** [comment] 2016-11-04 22:00
@NicklasNielsen It looks like the problem is `Props[AdoNetStorageProvider.DataConnectionInvariantPropertyName] = @"MyConnection";` This tells the storage provider your vendor would be `MyConnection`. If you leave it empty, a default of `AdoNetStorageProviderDefaultAdoInvariantInvariantPropertyName` will be chosen, which is `AdoInvariants.InvariantNameSqlServer = "System.Data.SqlClient"`. I believe this removes the problem you're seeing.

By the way, I don't see that in the instructions you linked. Also beware the binary serialization isn't robust with regards data versioning.

**Comment by veikkoeeva** [comment] 2016-11-04 22:11
Also, there's an improved error message on this exact situation merged at https://github.com/dotnet/orleans/pull/2306.

**Closed** 2016-11-09 16:50 UTC
