### ISSUE TITLE
Inserting ADO.NET reminders throw an exception when using Npgsql 6.0+

### ISSUE THREAD

**Issue by Rohansi** [dotnet/orleans#7424] opened 2021-12-04 14:11 UTC
Using Orleans 3.5.1 and Npgsql 6.0.1 with an existing project. I just set up a fresh DB on my machine and reminders fail to insert with the following error.

```
          Severity: ERROR
          SqlState: 42883
          MessageText: function upsert_reminder_row(text, text, text, timestamp with time zone, integer, integer) does not exist
          Hint: No function matches the given name and argument types. You might need to add explicit type casts.
          Position: 20
          File: parse_func.c
          Line: 636
          Routine: ParseFuncOrColumn
```

The `upsert_reminder_row` function created by the SQL in this repo has two differences:
1. `StartTimeArg` is a timestamp **without** timezone
2. `PeriodArg` is a big integer instead of just an integer

I confirmed that the timestamp difference for `StartTimeArg` is the problem by changing `upsert_reminder_row` to use `timestamp with time zone` instead of `timestamp without time zone` for `StartTimeArg`.

Npgsql 6.0 has breaking changes related to timestamp timezone behavior so that should be the trigger -> https://www.npgsql.org/doc/release-notes/6.0.html#major-changes-to-timestamp-mapping

**Comment by EdeMeijer** [comment] 2021-12-08 16:57
For whoever's looking into this, please consider my PR that was recently merged (https://github.com/dotnet/orleans/pull/7402). There, I also changed the reminder table column to `timestamp with time zone`, but did not consider these stored procedures (because I replaced them with my own queries that don't use any stored procedures). Again following standard advice, I'd say this stored procedure should be updated to accept `timestamp with time zone` as argument and use that everywhere.

**Comment by Rohansi** [comment] 2021-12-08 17:13
Thanks @EdeMeijer. The stored procedures pull data types from the table column types themselves so I think your PR should be good for this too. Only concern is this requires updating the DB for existing systems so there will at least need to be instructions on how to do this.

**Comment by EdeMeijer** [comment] 2021-12-08 21:54
You're right, that's a nice coincidence. So an actual migration would need something like

```sql
BEGIN;

ALTER TABLE OrleansRemindersTable
ALTER COLUMN StartTime TYPE TIMESTAMPTZ USING StartTime AT TIME ZONE 'UTC'; -- Or whatevever the actual time zone is

DROP FUNCTION upsert_reminder_row;

CREATE FUNCTION upsert_reminder_row(
    ServiceIdArg    OrleansRemindersTable.ServiceId%TYPE,
    GrainIdArg      OrleansRemindersTable.GrainId%TYPE,
    ReminderNameArg OrleansRemindersTable.ReminderName%TYPE,
    StartTimeArg    OrleansRemindersTable.StartTime%TYPE,
    PeriodArg       OrleansRemindersTable.Period%TYPE,
    GrainHashArg    OrleansRemindersTable.GrainHash%TYPE
  )
  RETURNS TABLE(version integer) AS
$func$
DECLARE
    VersionVar int := 0;
BEGIN

    INSERT INTO OrleansRemindersTable
    (
        ServiceId,
        GrainId,
        ReminderName,
        StartTime,
        Period,
        GrainHash,
        Version
    )
    SELECT
        ServiceIdArg,
        GrainIdArg,
        ReminderNameArg,
        StartTimeArg,
        PeriodArg,
        GrainHashArg,
        0
    ON CONFLICT (ServiceId, GrainId, ReminderName)
        DO UPDATE SET
            StartTime = excluded.StartTime,
            Period = excluded.Period,
            GrainHash = excluded.GrainHash,
            Version = OrleansRemindersTable.Version + 1
    RETURNING
        OrleansRemindersTable.Version INTO STRICT VersionVar;

    RETURN QUERY SELECT VersionVar AS versionr;

END
$func$ LANGUAGE plpgsql;

COMMIT;
```
Didn't test this, but something like this might be useful for people running into this.

**Comment by suraciii** [comment] 2021-12-15 09:23
According to [this](https://www.npgsql.org/doc/types/datetime.html#timestamps-and-timezones), there's a compatibility switch to opt out this behaviour:
`AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);`

But I think it's better to fix the pgsql schema like @EdeMeijer said

**Comment by ReubenBond** [comment] 2022-01-06 19:32
@EdeMeijer do we need to update the stored procedures as well?

**Comment by EdeMeijer** [comment] 2022-01-06 19:51
I *think* not because as far as I saw, the stored procedures reference the column types of the tables in their definitions. However, I did not test them, as I replaced the insert/update/delete queries with plain SQL statements for our application (because CockroachDB does not support stored procedures). So it might be a good idea to test it with a PG server to be 100% sure.

**Comment by EdeMeijer** [comment] 2022-01-06 19:53
But like stated above, also supplying some pre packaged migration SQL might be nice.

**Comment by dave-b-code** [comment] 2022-01-11 18:11
Anecdotal so feel free to disregard but after applying #7402 to silos running on 3.5.1, I've had no issues running reminders on a standard instance of postgres 14. It doesn't appear there's any issues with stored procedures from what I can tell. I did attempt this on a fresh instance however, so don't know how smoothly a migration would work.

**Comment by ReubenBond** [comment] 2022-01-12 00:33
Please correct me if I'm misunderstanding:
* @EdeMeijer's PR (#7402) solves this issue for new deployments (by updating the setup SQL script)
* Existing deployments will need to migrate their tables to change the column datatypes in order to continue working

If that's the case, I think we close this PR (since the core issue is fixed) and hope for a PR to add a migration script for the users with existing deployments.

Does that sound reasonable?

**Comment by EdeMeijer** [comment] 2022-01-12 11:18
You are right, and here you go: https://github.com/dotnet/orleans/pull/7490

I did run the original SQL and then the migration SQL on a postgres database, but did not test it with an Orleans app. However, since it applies the exact changes from my previous PR and @dave-b-code confirmed it works for them, I'm confident this will work fine.

**Comment by ReubenBond** [comment] 2022-01-12 18:35
Many thanks, @EdeMeijer! Merged and I'll close this. I'll cherry pick your PR and create the 3.6.0 build now - hoping that nothing else comes along

**Closed by ReubenBond** 2022-01-12 18:35 UTC
Labels: area-persistence
